import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk3.pdf";
export const lessonHsk3L11SourceRef = (printedPages, pdfPages) => `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
const sourceRef = lessonHsk3L11SourceRef("95-103", "107-115");
const art = (scene) => ({ image: group3AssetPath(`/assets/group3/lesson-hsk3-l11-${scene}-v1.webp`), imageSrcSet: `${group3AssetPath(`/assets/group3/lesson-hsk3-l11-${scene}-720w-v1.webp`)} 720w, ${group3AssetPath(`/assets/group3/lesson-hsk3-l11-${scene}-v1.webp`)} 1400w` });
const line = (ref, value) => ({ ...value, reading: value.pinyin, sourceRef: ref });
const visual = (zh, th, focus) => ({ zh, th, focus });

const vocabularyRows = [
  [1, "会议", "huìyì", "n.", "meeting; conference", "การประชุม", 96, 108], [2, "经理", "jīnglǐ", "n.", "manager", "ผู้จัดการ", 96, 108], [3, "开会", "kāihuì", "v.", "have a meeting", "ประชุม", 96, 108], [4, "后天", "hòutiān", "n.", "the day after tomorrow", "วันมะรืน", 96, 108], [5, "地点", "dìdiǎn", "n.", "place; location", "สถานที่", 96, 108], [6, "室", "shì", "n.", "room", "ห้อง", 96, 108], [7, "发", "fā", "v.", "send", "ส่ง", 96, 108], [8, "笔记本（电脑）", "bǐjìběn (diànnǎo)", "n.", "laptop", "คอมพิวเตอร์โน้ตบุ๊ก", 96, 108], [9, "或者", "huòzhě", "conj.", "or", "หรือ", 96, 108],
  [10, "声音", "shēngyīn", "n.", "sound", "เสียง", 98, 110], [11, "看来", "kànlái", "phrase", "it seems", "ดูเหมือนว่า", 98, 110], [12, "办法", "bànfǎ", "n.", "method; way", "วิธี", 98, 110], [13, "解决", "jiějué", "v.", "solve", "แก้ไข", 98, 110], [14, "只能", "zhǐ néng", "phrase", "can only", "ทำได้เพียง", 98, 110], [15, "别人", "biérén", "pron.", "someone else; other people", "คนอื่น", 98, 110],
  [16, "请假", "qǐngjià", "v.", "ask for leave", "ลางาน", 99, 111], [17, "同事", "tóngshì", "n.", "colleague", "เพื่อนร่วมงาน", 99, 111], [18, "休假", "xiūjià", "v.", "take a vacation", "พักร้อน", 99, 111], [19, "怕", "pà", "v.", "be afraid; fear", "กลัว", 99, 111], [20, "邮箱", "yóuxiāng", "n.", "email address; mailbox", "กล่องอีเมล", 99, 111],
  [21, "愿意", "yuànyì", "modal", "be willing", "เต็มใจ", 101, 113], [22, "生活", "shēnghuó", "n./v.", "life; live", "ชีวิต / ใช้ชีวิต", 101, 113], [23, "城市", "chéngshì", "n.", "city", "เมือง", 101, 113], [24, "离开", "líkāi", "v.", "leave", "จากไป", 101, 113], [25, "机会", "jīhuì", "n.", "opportunity", "โอกาส", 101, 113], [26, "为", "wèi", "prep.", "for", "เพื่อ", 101, 113], [27, "或", "huò", "conj.", "or", "หรือ", 101, 113],
];
const vocabulary = vocabularyRows.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({ index, hanzi, pinyin, type, en, th: thAid, thAid, page, translationKind: "editorial-aid", sourceRef: lessonHsk3L11SourceRef(String(page), String(pdfPage)) }));
const meetingRef = lessonHsk3L11SourceRef("96", "108");
const computerRef = lessonHsk3L11SourceRef("98", "110");
const workloadRef = lessonHsk3L11SourceRef("99", "111");

const characters = {
  wang: { hanzi: "王一雪", pinyin: "Wáng Yìxuě", nameTh: "หวังอี้เสวี่ย", nameEn: "Wang Yixue", ...art("meeting"), imageFocus: "34% center" },
  yang: { hanzi: "杨同乐", pinyin: "Yáng Tónglè", nameTh: "หยางถงเล่อ", nameEn: "Yang Tongle", ...art("meeting"), imageFocus: "66% center" },
};

const scenes = [
  {
    id: "h3l11-meeting", number: "01", glyph: "会", title: "讨论会议安排", titleTh: "คุยเรื่องกำหนดการประชุม", titleEn: "Discussing the meeting schedule", place: "办公室",
    placePy: "bàngōngshì", placeTh: "สำนักงาน", ...art("meeting"), source: "Text 1 · หน้าเล่ม 96 · PDF หน้า 108", sourcePage: "96", sourceRef: meetingRef,
    imageAlt: { zh: "办公室会议场景", th: "หวังอี้เสวี่ยกับหยางถงเล่อคุยเรื่องประชุม", en: "Wang Yixue and Yang Tongle discussing a meeting" }, context: "在办公室里，王一雪跟杨同乐讨论工作。", contextTh: "ในสำนักงาน หวังอี้เสวี่ยกับหยางถงเล่อคุยเรื่องงาน", contextEn: "In the office, Wang Yixue and Yang Tongle discussed work.",
    characters: [{ role: "A", profile: "wang", noteZh: "询问会议安排的人", noteTh: "ผู้ถามกำหนดการประชุม", noteEn: "The person asking about the meeting" }, { role: "B", profile: "yang", noteZh: "说明新安排的人", noteTh: "ผู้แจ้งกำหนดการใหม่", noteEn: "The person explaining the new arrangement" }],
    lines: [
      line(meetingRef, { role: "A", speaker: "王一雪", hanzi: "会议下午几点开始？", pinyin: "Huìyì xiàwǔ jǐ diǎn kāishǐ?", en: "What time does the meeting start this afternoon?", th: "การประชุมช่วงบ่ายเริ่มกี่โมง?", visual: visual("会议几点开始", "ประชุมเริ่มกี่โมง", "34% center") }),
      line(meetingRef, { role: "B", speaker: "杨同乐", hanzi: "今天下午经理不在，不开会了。", pinyin: "Jīntiān xiàwǔ jīnglǐ bú zài, bù kāihuì le.", en: "The manager will not be here this afternoon, so the meeting is canceled.", th: "บ่ายวันนี้ผู้จัดการไม่อยู่ จึงไม่ประชุมแล้ว", visual: visual("经理不在", "ผู้จัดการไม่อยู่", "66% center") }),
      line(meetingRef, { role: "A", speaker: "王一雪", hanzi: "那什么时候开会？", pinyin: "Nà shénme shíhou kāihuì?", en: "Then when will the meeting be?", th: "งั้นจะประชุมเมื่อไร?", visual: visual("什么时候开会", "ประชุมเมื่อไร", "36% center") }),
      line(meetingRef, { role: "B", speaker: "杨同乐", hanzi: "后天上午十点，会议地点换到第一会议室。我正要给大家发邮件。", pinyin: "Hòutiān shàngwǔ shí diǎn, huìyì dìdiǎn huàn dào dì-yī huìyìshì. Wǒ zhèng yào gěi dàjiā fā yóujiàn.", en: "At ten the morning after tomorrow. The location has changed to Meeting Room One. I am about to email everyone.", th: "สิบโมงเช้าวันมะรืน สถานที่เปลี่ยนเป็นห้องประชุมหนึ่ง ฉันกำลังจะส่งอีเมลให้ทุกคน", visual: visual("换到第一会议室", "เปลี่ยนเป็นห้องประชุมหนึ่ง", "64% center") }),
      line(meetingRef, { role: "A", speaker: "王一雪", hanzi: "开会的时候，我们用会议室的电脑还是自己的笔记本电脑？", pinyin: "Kāihuì de shíhou, wǒmen yòng huìyìshì de diànnǎo háishi zìjǐ de bǐjìběn diànnǎo?", en: "For the meeting, should we use the meeting-room computer or our own laptops?", th: "ตอนประชุมเราใช้คอมพิวเตอร์ห้องประชุมหรือโน้ตบุ๊กของตัวเอง?", visual: visual("还是自己的电脑", "หรือคอมพิวเตอร์ของตัวเอง", "38% center") }),
      line(meetingRef, { role: "B", speaker: "杨同乐", hanzi: "会议室的电脑或者自己的电脑都可以。", pinyin: "Huìyìshì de diànnǎo huòzhě zìjǐ de diànnǎo dōu kěyǐ.", en: "Either the meeting-room computer or your own computer is fine.", th: "ใช้คอมพิวเตอร์ห้องประชุมหรือของตัวเองก็ได้ทั้งคู่", visual: visual("或者……都可以", "อย่างใดก็ได้", "62% center") }),
      line(meetingRef, { role: "A", speaker: "王一雪", hanzi: "那到时候咱们早点儿过去，你帮我把电脑接好吧。", pinyin: "Nà dào shíhou zánmen zǎodiǎnr guòqu, nǐ bāng wǒ bǎ diànnǎo jiē hǎo ba.", en: "Then let us go over early, and please help me set up the computer.", th: "ถึงตอนนั้นเราไปเร็วหน่อย ช่วยฉันต่อคอมพิวเตอร์ให้เรียบร้อยนะ", visual: visual("把电脑接好", "ต่อคอมพิวเตอร์ให้เรียบร้อย", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "会议改到什么时候？", th: "การประชุมเปลี่ยนเป็นเมื่อไร?", en: "When was the meeting moved to?" }, options: [{ value: "后天上午十点", zh: "后天上午十点", pinyin: "hòutiān shàngwǔ shí diǎn", th: "สิบโมงเช้าวันมะรืน" }, { value: "今天下午", zh: "今天下午", pinyin: "jīntiān xiàwǔ", th: "บ่ายวันนี้" }, { value: "明天晚上", zh: "明天晚上", pinyin: "míngtiān wǎnshang", th: "เย็นพรุ่งนี้" }], correct: "后天上午十点", evidence: "杨同乐：后天上午十点。", evidenceTh: "หยางถงเล่อ: สิบโมงเช้าวันมะรืน", sourceRef: meetingRef },
    builder: { prompt: { zh: "重组选择问句", th: "เรียงประโยคคำถามแบบเลือก", en: "Rebuild the choice question" }, answer: ["我们用", "会议室的电脑", "还是", "自己的笔记本电脑"], tiles: ["还是", "自己的笔记本电脑", "我们用", "会议室的电脑"], gloss: { 我们用: "เราใช้", 会议室的电脑: "คอมพิวเตอร์ห้องประชุม", 还是: "หรือ", 自己的笔记本电脑: "โน้ตบุ๊กของตัวเอง" }, translationTh: "เราใช้คอมพิวเตอร์ห้องประชุมหรือโน้ตบุ๊กของตัวเอง?", translationEn: "Should we use the meeting-room computer or our own laptops?", evidence: "Text 1 · หน้าเล่ม 96", sourceRef: meetingRef },
  },
  {
    id: "h3l11-computer", number: "02", glyph: "解", title: "检查电脑问题", titleTh: "ตรวจปัญหาคอมพิวเตอร์", titleEn: "Checking a computer problem", place: "会议室", placeTh: "ห้องประชุม", ...art("computer"), source: "Text 2 · หน้าเล่ม 98 · PDF หน้า 110", sourcePage: "98", sourceRef: computerRef,
    imageAlt: { zh: "会议室电脑场景", th: "ตรวจคอมพิวเตอร์ก่อนประชุม", en: "Checking a computer in the meeting room" }, context: "在会议室，王一雪跟杨同乐做会前准备。", contextTh: "ในห้องประชุม ทั้งสองเตรียมงานก่อนประชุม", contextEn: "In the meeting room, they prepared for the meeting.", characters: [{ role: "A", profile: "wang", noteZh: "测试电脑的人", noteTh: "ผู้ทดสอบคอมพิวเตอร์", noteEn: "The person testing the computer" }, { role: "B", profile: "yang", noteZh: "检查问题的人", noteTh: "ผู้ตรวจปัญหา", noteEn: "The person checking the problem" }],
    lines: [
      line(computerRef, { role: "A", speaker: "王一雪", hanzi: "电脑接好了吗？", pinyin: "Diànnǎo jiē hǎo le ma?", en: "Is the computer set up?", th: "ต่อคอมพิวเตอร์เรียบร้อยหรือยัง?", visual: visual("电脑接好了吗", "ต่อคอมพิวเตอร์หรือยัง", "34% center") }),
      line(computerRef, { role: "B", speaker: "杨同乐", hanzi: "已经接好了，您开机看看有没有问题。", pinyin: "Yǐjīng jiē hǎo le, nín kāijī kànkan yǒu méiyǒu wèntí.", en: "It is set up. Turn it on and see whether there is a problem.", th: "ต่อแล้ว ลองเปิดเครื่องดูว่ามีปัญหาไหม", visual: visual("开机看看", "ลองเปิดเครื่องดู", "66% center") }),
      line(computerRef, { role: "A", speaker: "王一雪", hanzi: "现在什么都看不见。", pinyin: "Xiànzài shénme dōu kàn bu jiàn.", en: "I cannot see anything now.", th: "ตอนนี้มองไม่เห็นอะไรเลย", visual: visual("什么都看不见", "มองไม่เห็นอะไรเลย", "36% center") }),
      line(computerRef, { role: "B", speaker: "杨同乐", hanzi: "我检查一下哪里出问题了……您再试一下。", pinyin: "Wǒ jiǎnchá yíxià nǎli chū wèntí le... Nín zài shì yíxià.", en: "I will check where the problem is... Please try again.", th: "ฉันจะตรวจว่าปัญหาอยู่ตรงไหน... ลองอีกครั้งนะ", visual: visual("再试一下", "ลองอีกครั้ง", "64% center") }),
      line(computerRef, { role: "A", speaker: "王一雪", hanzi: "看见了，但是听不见声音。", pinyin: "Kànjiàn le, dànshì tīng bu jiàn shēngyīn.", en: "I can see it, but I cannot hear any sound.", th: "มองเห็นแล้ว แต่ไม่ได้ยินเสียง", visual: visual("听不见声音", "ไม่ได้ยินเสียง", "38% center") }),
      line(computerRef, { role: "B", speaker: "杨同乐", hanzi: "现在呢？", pinyin: "Xiànzài ne?", en: "How about now?", th: "ตอนนี้ล่ะ?", visual: visual("现在呢", "ตอนนี้ล่ะ", "62% center") }),
      line(computerRef, { role: "A", speaker: "王一雪", hanzi: "听得见声音，但是声音有点儿小，听不清楚。", pinyin: "Tīng de jiàn shēngyīn, dànshì shēngyīn yǒudiǎnr xiǎo, tīng bu qīngchu.", en: "I can hear sound, but it is a little quiet and unclear.", th: "ได้ยินเสียงแล้ว แต่เสียงเบาไปหน่อย ฟังไม่ชัด", visual: visual("声音有点儿小", "เสียงเบาไปหน่อย", "40% center") }),
      line(computerRef, { role: "B", speaker: "杨同乐", hanzi: "看来我没办法解决这个问题，只能找别人来帮帮忙了。", pinyin: "Kànlái wǒ méi bànfǎ jiějué zhège wèntí, zhǐ néng zhǎo biérén lái bāngbang máng le.", en: "It seems I cannot solve this problem. I can only ask someone else to help.", th: "ดูเหมือนฉันจะแก้ปัญหานี้ไม่ได้ คงต้องหาคนอื่นมาช่วย", visual: visual("看来没办法解决", "ดูเหมือนจะแก้ไม่ได้", "60% center") }),
    ],
    qte: { after: 4, prompt: { zh: "最后电脑还有什么问题？", th: "สุดท้ายคอมพิวเตอร์ยังมีปัญหาอะไร?", en: "What problem did the computer still have?" }, options: [{ value: "声音太小", zh: "声音太小", pinyin: "shēngyīn tài xiǎo", th: "เสียงเบาเกินไป" }, { value: "不能开机", zh: "不能开机", pinyin: "bù néng kāijī", th: "เปิดเครื่องไม่ได้" }, { value: "没有网络", zh: "没有网络", pinyin: "méiyǒu wǎngluò", th: "ไม่มีอินเทอร์เน็ต" }], correct: "声音太小", evidence: "王一雪：声音有点儿小，听不清楚。", evidenceTh: "หวังอี้เสวี่ย: เสียงเบาไปหน่อย ฟังไม่ชัด", sourceRef: computerRef },
    builder: { prompt: { zh: "重组“看来”句", th: "เรียงประโยค 看来", en: "Rebuild the 看来 sentence" }, answer: ["看来", "我没办法", "解决", "这个问题"], tiles: ["这个问题", "解决", "看来", "我没办法"], gloss: { 看来: "ดูเหมือนว่า", 我没办法: "ฉันไม่มีทาง", 解决: "แก้ไข", 这个问题: "ปัญหานี้" }, translationTh: "ดูเหมือนฉันจะแก้ปัญหานี้ไม่ได้", translationEn: "It seems I cannot solve this problem.", evidence: "Text 2 · หน้าเล่ม 98", sourceRef: computerRef },
  },
  {
    id: "h3l11-workload", number: "03", glyph: "工", title: "忙着完成工作", titleTh: "เร่งทำงานให้เสร็จ", titleEn: "Finishing the workload", place: "办公室",
    placePy: "bàngōngshì", placeTh: "สำนักงาน", ...art("workload"), source: "Text 3 · หน้าเล่ม 99 · PDF หน้า 111", sourcePage: "99", sourceRef: workloadRef,
    imageAlt: { zh: "办公室工作场景", th: "คุยเรื่องเพื่อนร่วมงานลาและงานที่ค้าง", en: "Discussing colleagues on leave and unfinished work" }, context: "在办公室里，王一雪跟杨同乐聊天儿。", contextTh: "ในสำนักงาน หวังอี้เสวี่ยกับหยางถงเล่อคุยกัน", contextEn: "In the office, Wang Yixue and Yang Tongle chatted.", characters: [{ role: "A", profile: "wang", noteZh: "担心工作做不完的人", noteTh: "ผู้กังวลว่างานจะไม่เสร็จ", noteEn: "The person worried about unfinished work" }, { role: "B", profile: "yang", noteZh: "提出一起完成工作的人", noteTh: "ผู้เสนอช่วยทำงาน", noteEn: "The person offering to help" }],
    lines: [
      line(workloadRef, { role: "A", speaker: "王一雪", hanzi: "同乐，你看见老张了吗？", pinyin: "Tónglè, nǐ kànjiàn Lǎo Zhāng le ma?", en: "Tongle, have you seen Lao Zhang?", th: "ถงเล่อ เธอเห็นเหล่าจางไหม?", visual: visual("看见老张了吗", "เห็นเหล่าจางไหม", "34% center") }),
      line(workloadRef, { role: "B", speaker: "杨同乐", hanzi: "老张没来。他说家里有点儿事，所以请假了。", pinyin: "Lǎo Zhāng méi lái. Tā shuō jiāli yǒudiǎnr shì, suǒyǐ qǐngjià le.", en: "Lao Zhang did not come. He had something at home, so he took leave.", th: "เหล่าจางไม่มา เขาบอกว่าที่บ้านมีธุระจึงลางาน", visual: visual("所以请假了", "จึงลางาน", "66% center") }),
      line(workloadRef, { role: "A", speaker: "王一雪", hanzi: "好几个同事都休假了，开会前这么多工作我怕干不完。", pinyin: "Hǎo jǐ ge tóngshì dōu xiūjià le, kāihuì qián zhème duō gōngzuò wǒ pà gàn bu wán.", en: "Several colleagues are on leave. I am afraid I cannot finish so much work before the meeting.", th: "เพื่อนร่วมงานหลายคนพักร้อน ฉันกลัวว่าจะทำงานมากมายนี้ไม่เสร็จก่อนประชุม", visual: visual("怕干不完", "กลัวทำไม่เสร็จ", "36% center") }),
      line(workloadRef, { role: "B", speaker: "杨同乐", hanzi: "十二点多了，咱们先去吃饭吧。吃完饭，我跟您一起把这些工作做完。", pinyin: "Shí'èr diǎn duō le, zánmen xiān qù chīfàn ba. Chī wán fàn, wǒ gēn nín yìqǐ bǎ zhèxiē gōngzuò zuò wán.", en: "It is past twelve. Let us eat first. Afterward, I will finish this work with you.", th: "เที่ยงกว่าแล้ว ไปกินข้าวก่อนเถอะ กินเสร็จฉันจะช่วยทำงานเหล่านี้ให้เสร็จ", visual: visual("把工作做完", "ทำงานให้เสร็จ", "64% center") }),
      line(workloadRef, { role: "A", speaker: "王一雪", hanzi: "你先去吃，我想再干一会儿。明天开会前要发到公司的邮箱里。", pinyin: "Nǐ xiān qù chī, wǒ xiǎng zài gàn yíhuìr. Míngtiān kāihuì qián yào fā dào gōngsī de yóuxiāng li.", en: "You eat first. I want to work a little longer. It must be sent to the company mailbox before tomorrow's meeting.", th: "เธอไปกินก่อน ฉันขอทำต่ออีกหน่อย ต้องส่งเข้ากล่องอีเมลบริษัทก่อนประชุมพรุ่งนี้", visual: visual("发到公司的邮箱里", "ส่งเข้ากล่องอีเมลบริษัท", "38% center") }),
      line(workloadRef, { role: "B", speaker: "杨同乐", hanzi: "您没看到邮件吗？经理还没回来呢，下周才能开会。", pinyin: "Nín méi kàndào yóujiàn ma? Jīnglǐ hái méi huílai ne, xià zhōu cái néng kāihuì.", en: "Did you not see the email? The manager is not back; the meeting cannot happen until next week.", th: "คุณไม่เห็นอีเมลหรือ? ผู้จัดการยังไม่กลับ ต้องสัปดาห์หน้าถึงจะประชุมได้", visual: visual("下周才能开会", "สัปดาห์หน้าจึงจะประชุม", "62% center") }),
      line(workloadRef, { role: "A", speaker: "王一雪", hanzi: "那不着急了。走，吃饭去。", pinyin: "Nà bù zháojí le. Zǒu, chīfàn qù.", en: "Then there is no rush. Come on, let us eat.", th: "งั้นก็ไม่ต้องรีบแล้ว ไปกินข้าวกัน", visual: visual("不着急了", "ไม่ต้องรีบแล้ว", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "王一雪为什么担心？", th: "หวังอี้เสวี่ยกังวลเพราะอะไร?", en: "Why was Wang Yixue worried?" }, options: [{ value: "怕工作做不完", zh: "怕工作做不完", pinyin: "pà gōngzuò zuò bu wán", th: "กลัวทำงานไม่เสร็จ" }, { value: "找不到会议室", zh: "找不到会议室", pinyin: "zhǎo bu dào huìyìshì", th: "หาห้องประชุมไม่เจอ" }, { value: "忘了吃饭", zh: "忘了吃饭", pinyin: "wàng le chīfàn", th: "ลืมกินข้าว" }], correct: "怕工作做不完", evidence: "王一雪：这么多工作我怕干不完。", evidenceTh: "หวังอี้เสวี่ย: ฉันกลัวว่าจะทำงานมากมายนี้ไม่เสร็จ", sourceRef: workloadRef },
    builder: { prompt: { zh: "重组“把”字句", th: "เรียงประโยค 把", en: "Rebuild the 把 sentence" }, answer: ["我跟您一起", "把", "这些工作", "做完"], tiles: ["做完", "这些工作", "把", "我跟您一起"], gloss: { 我跟您一起: "ฉันกับคุณด้วยกัน", 把: "นำกรรมมาวางหน้า", 这些工作: "งานเหล่านี้", 做完: "ทำให้เสร็จ" }, translationTh: "ฉันจะช่วยคุณทำงานเหล่านี้ให้เสร็จ", translationEn: "I will finish this work with you.", evidence: "Text 3 · หน้าเล่ม 99", sourceRef: workloadRef },
  },
];

export const LESSON_HSK3_L11 = {
  id: "hsk3-l11", slug: "lesson-11", level: "hsk3", number: 11, featured: false, sourceRef,
  source: { title: "新HSK教程 3 · New HSK Course 3", lesson: "Lesson 11 · 看来我没办法解决这个问题", printedPages: "95–103", pdfPages: "107–115", file: "hsk3.pdf", sourceRef },
  title: { zh: "看来我没办法解决这个问题", pinyin: "Kànlái wǒ méi bànfǎ jiějué zhège wèntí", en: "It seems I cannot solve this problem", thAid: "ดูเหมือนฉันจะแก้ปัญหานี้ไม่ได้" },
  summary: { zh: "交流工作和会议安排，讨论电脑问题与工作选择。", en: "Discuss work, meeting arrangements, computer problems, and career choices.", thAid: "พูดคุยเรื่องงาน กำหนดการประชุม ปัญหาคอมพิวเตอร์ และการเลือกงาน" }, translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并交流工作情况。", en: "Be able to understand and communicate about work situations.", thAid: "ฟังเข้าใจและสื่อสารเกี่ยวกับสถานการณ์การทำงาน", sourceRef: lessonHsk3L11SourceRef("95", "107") },
    { zh: "能听懂并谈论职业选择和工作感受。", en: "Be able to understand and discuss career choices and feelings about work.", thAid: "ฟังเข้าใจและพูดคุยเรื่องการเลือกอาชีพและความรู้สึกต่องาน", sourceRef: lessonHsk3L11SourceRef("95", "107") },
    { zh: "掌握“看来”的用法，能对事件进行推测和分析。", en: "Master 看来 to make inferences and analyze events.", thAid: "ใช้ 看来 เพื่อคาดคะเนและวิเคราะห์เหตุการณ์", sourceRef: lessonHsk3L11SourceRef("95", "107") },
  ],
  contents: [{ number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "95", route: "/home/hsk3/lesson-11/preface/", sourceRef: lessonHsk3L11SourceRef("95", "107") }, { number: "01", title: "讨论会议安排", titleTh: "คุยเรื่องกำหนดการประชุม", detail: "Text 1 · New Words 1–9", pages: "96–97", scene: 1, sourceRef: lessonHsk3L11SourceRef("96-97", "108-109") }, { number: "02", title: "检查电脑问题", titleTh: "ตรวจปัญหาคอมพิวเตอร์", detail: "Text 2 · New Words 10–15", pages: "97–98", scene: 2, sourceRef: lessonHsk3L11SourceRef("97-98", "109-110") }, { number: "03", title: "忙着完成工作", titleTh: "เร่งทำงานให้เสร็จ", detail: "Text 3 · New Words 16–20", pages: "99–100", scene: 3, sourceRef: lessonHsk3L11SourceRef("99-100", "111-112") }, { number: "04", title: "职业选择、练习与活动", titleTh: "การเลือกงาน แบบฝึก และกิจกรรม", detail: "Text 4 · Exercises · Activity", pages: "101–103", sourceRef: lessonHsk3L11SourceRef("101-103", "113-115") }],
  vocabulary,
  grammarFocus: [
    { title: "“还是”和“或者”", titleEn: "Comparison of 还是 and 或者", explanationZh: "“还是”常用于疑问句提出选择；“或者”常用于陈述句说明可能选项。", explanationEn: "还是 presents alternatives in questions; 或者 connects alternatives in statements.", thAid: "还是 ใช้เสนอทางเลือกในคำถาม ส่วน 或者 ใช้เชื่อมทางเลือกในประโยคบอกเล่า", examples: ["我们用会议室的电脑还是自己的笔记本电脑？", "会议室的电脑或者自己的电脑都可以。"], sourceRef: lessonHsk3L11SourceRef("97", "109") },
    { title: "固定短语“看来”", titleEn: "Set phrase 看来", explanationZh: "“看来”后接结论，表示说话人观察、思考后的分析或推测。", explanationEn: "看来 introduces a conclusion inferred from observation or reflection.", thAid: "看来 นำหน้าข้อสรุปที่เกิดจากการสังเกตหรือไตร่ตรอง", examples: ["看来我没办法解决这个问题。", "这么晚了，看来他今天不会来了。"], sourceRef: lessonHsk3L11SourceRef("98", "110") },
    { title: "“把”字句（3）", titleEn: "The 把 Sentence (3)", explanationZh: "结构“主语+把+宾语+动词+结果补语”强调动作使确定事物产生结果。", explanationEn: "Subject + 把 + object + verb + result complement emphasizes an action's result.", thAid: "ประธาน + 把 + กรรม + กริยา + ส่วนเสริมผลลัพธ์ เน้นผลที่เกิดกับสิ่งที่ชี้เฉพาะ", examples: ["我跟您一起把这些工作做完。", "妈妈把衣服洗干净了。"], sourceRef: lessonHsk3L11SourceRef("100", "112") },
  ],
  characters, scenes,
};
