import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk3.pdf";
export const lessonHsk3L17SourceRef = (printedPages, pdfPages) => `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
const sourceRef = lessonHsk3L17SourceRef("154-162", "166-174");
const art = (scene) => ({ image: group3AssetPath(`/assets/group3/lesson-hsk3-l17-${scene}-v1.webp`), imageSrcSet: `${group3AssetPath(`/assets/group3/lesson-hsk3-l17-${scene}-720w-v1.webp`)} 720w, ${group3AssetPath(`/assets/group3/lesson-hsk3-l17-${scene}-v1.webp`)} 1400w` });
const line = (ref, value) => ({ ...value, reading: value.pinyin, sourceRef: ref });
const visual = (zh, th, focus) => ({ zh, th, focus });
const vocabularyRows = [
  [1, "向", "xiàng", "prep.", "to; toward", "ไปทาง / ต่อ", 155, 167], [2, "楼梯", "lóutī", "n.", "stairs", "บันได", 155, 167], [3, "害怕", "hàipà", "v.", "fear; be afraid", "กลัว", 155, 167], [4, "生气", "shēngqì", "v.", "get angry", "โกรธ", 155, 167], [5, "常见", "chángjiàn", "adj.", "common", "พบบ่อย", 155, 167], [6, "聪明", "cōngming", "adj.", "smart; clever", "ฉลาด", 155, 167], [7, "错", "cuò", "n.", "mistake", "ความผิดพลาด", 155, 167], [8, "认为", "rènwéi", "v.", "think; consider", "คิดว่า", 155, 167],
  [9, "到处", "dàochù", "adv.", "everywhere", "ทุกที่", 157, 169], [10, "继续", "jìxù", "v.", "continue", "ดำเนินต่อ", 157, 169], [11, "同意", "tóngyì", "v.", "agree", "เห็นด้วย", 157, 169], [12, "可", "kě", "conj.", "but", "แต่", 157, 169], [13, "屋子", "wūzi", "n.", "room", "ห้อง", 157, 169], [14, "有关", "yǒuguān", "v./prep.", "have to do with; about", "เกี่ยวข้องกับ", 157, 169],
  [15, "关机", "guānjī", "v.", "turn off a mobile phone", "ปิดเครื่อง", 159, 171], [16, "前天", "qiántiān", "n.", "the day before yesterday", "เมื่อวานซืน", 159, 171], [17, "留学", "liúxué", "v.", "study abroad", "ศึกษาต่อต่างประเทศ", 159, 171], [18, "国家", "guójiā", "n.", "country", "ประเทศ", 159, 171], [19, "比如", "bǐrú", "v.", "for example", "ตัวอย่างเช่น", 159, 171], [20, "查", "chá", "v.", "look up; consult", "ค้นหา / ตรวจสอบ", 159, 171], [21, "有用", "yǒuyòng", "adj.", "useful", "มีประโยชน์", 159, 171],
  [22, "容易", "róngyì", "adj.", "easy", "ง่าย", 160, 172], [23, "回答", "huídá", "v.", "answer", "ตอบ", 160, 172], [24, "方向", "fāngxiàng", "n.", "direction", "ทิศทาง", 160, 172], [25, "只有", "zhǐyǒu", "conj.", "only", "มีเพียง / ก็ต่อเมื่อ", 160, 172], [26, "真正", "zhēnzhèng", "adv.", "really; indeed", "อย่างแท้จริง", 160, 172], [27, "难题", "nántí", "n.", "difficult problem", "ปัญหายาก", 160, 172],
];
const vocabulary = vocabularyRows.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({ index, hanzi, pinyin, type, en, th: thAid, thAid, page, translationKind: "editorial-aid", sourceRef: lessonHsk3L17SourceRef(String(page), String(pdfPage)) }));
const buildingRef = lessonHsk3L17SourceRef("155", "167");
const readingRef = lessonHsk3L17SourceRef("156-157", "168-169");
const campusRef = lessonHsk3L17SourceRef("158-159", "170-171");
const characters = {
  liuXiaoxue: { hanzi: "刘小雪", pinyin: "Liú Xiǎoxuě", nameTh: "หลิวเสี่ยวเสวี่ย", nameEn: "Liu Xiaoxue", ...art("teaching-building"), imageFocus: "30% center" },
  classmate: { hanzi: "同学", pinyin: "Tóngxué", nameTh: "เพื่อนร่วมชั้น", nameEn: "Classmate", ...art("teaching-building"), imageFocus: "70% center" },
  bai: { hanzi: "白家月", pinyin: "Bái Jiāyuè", nameTh: "ไป๋เจียเยว่", nameEn: "Bai Jiayue", ...art("reading-room"), imageFocus: "30% center" },
  chen: { hanzi: "陈天中", pinyin: "Chén Tiānzhōng", nameTh: "เฉินเทียนจง", nameEn: "Chen Tianzhong", ...art("campus"), imageFocus: "70% center" },
  liWen: { hanzi: "李文", pinyin: "Lǐ Wén", nameTh: "หลี่เหวิน", nameEn: "Li Wen", ...art("campus"), imageFocus: "30% center" },
};
const scenes = [
  {
    id: "h3l17-teaching-building", number: "01", glyph: "错", title: "别害怕见老师", titleTh: "อย่ากลัวที่จะพบครู", titleEn: "Do not be afraid to meet the teacher", place: "教学楼", placeTh: "อาคารเรียน", ...art("teaching-building"), source: "Text 1 · หน้าเล่ม 155 · PDF หน้า 167", sourcePage: "155", sourceRef: buildingRef,
    imageAlt: { zh: "教学楼走廊", th: "นักเรียนคุยกันในอาคารเรียน", en: "Students talking in a teaching building" }, context: "在教学楼里，刘小雪和同学边走边聊。", contextTh: "ในอาคารเรียน หลิวเสี่ยวเสวี่ยกับเพื่อนเดินไปคุยไป", contextEn: "In the teaching building, Liu Xiaoxue and her classmate talked while walking.", characters: [{ role: "A", profile: "liuXiaoxue", noteZh: "安慰同学的人", noteTh: "ผู้ปลอบเพื่อน", noteEn: "The reassuring classmate" }, { role: "B", profile: "classmate", noteZh: "害怕老师生气的人", noteTh: "ผู้กลัวว่าครูจะโกรธ", noteEn: "The worried student" }],
    lines: [
      line(buildingRef, { role: "A", speaker: "刘小雪", hanzi: "别再向前走了，李老师的办公室已经到了。", pinyin: "Bié zài xiàng qián zǒu le, Lǐ lǎoshī de bàngōngshì yǐjīng dào le.", en: "Do not keep walking forward. We have reached Teacher Li's office.", th: "อย่าเดินไปข้างหน้าอีก ถึงห้องทำงานครูหลี่แล้ว", visual: visual("别再向前走", "อย่าเดินไปข้างหน้าอีก", "30% center") }),
      line(buildingRef, { role: "B", speaker: "同学", hanzi: "你进去吧，我在楼梯那儿等你。我害怕见李老师。", pinyin: "Nǐ jìnqu ba, wǒ zài lóutī nàr děng nǐ. Wǒ hàipà jiàn Lǐ lǎoshī.", en: "You go in. I will wait by the stairs. I am afraid to see Teacher Li.", th: "เธอเข้าไปเถอะ ฉันรอตรงบันได ฉันกลัวพบครูหลี่", visual: visual("害怕见李老师", "กลัวพบครูหลี่", "70% center") }),
      line(buildingRef, { role: "A", speaker: "刘小雪", hanzi: "怎么回事？", pinyin: "Zěnme huí shì?", en: "What happened?", th: "เกิดอะไรขึ้น?", visual: visual("怎么回事", "เกิดอะไรขึ้น", "32% center") }),
      line(buildingRef, { role: "B", speaker: "同学", hanzi: "最近我做错了好几件事，我怕李老师生气。", pinyin: "Zuìjìn wǒ zuò cuò le hǎo jǐ jiàn shì, wǒ pà Lǐ lǎoshī shēngqì.", en: "Recently I made several mistakes, and I am afraid Teacher Li is angry.", th: "ช่วงนี้ฉันทำผิดหลายเรื่อง กลัวครูหลี่โกรธ", visual: visual("做错了好几件事", "ทำผิดหลายเรื่อง", "68% center") }),
      line(buildingRef, { role: "A", speaker: "刘小雪", hanzi: "你想多了，做错事情是很常见的。", pinyin: "Nǐ xiǎng duō le, zuò cuò shìqing shì hěn chángjiàn de.", en: "You are overthinking it. Making mistakes is common.", th: "เธอคิดมากไป การทำผิดเป็นเรื่องที่พบบ่อย", visual: visual("做错事情很常见", "การทำผิดเป็นเรื่องธรรมดา", "34% center") }),
      line(buildingRef, { role: "B", speaker: "同学", hanzi: "我把简单的事情做错了，李老师一定觉得我不认真。", pinyin: "Wǒ bǎ jiǎndān de shìqing zuò cuò le, Lǐ lǎoshī yídìng juéde wǒ bù rènzhēn.", en: "I got a simple task wrong. Teacher Li must think I am not serious.", th: "ฉันทำเรื่องง่าย ๆ ผิด ครูหลี่ต้องคิดว่าฉันไม่ตั้งใจแน่", visual: visual("觉得我不认真", "คิดว่าฉันไม่ตั้งใจ", "66% center") }),
      line(buildingRef, { role: "A", speaker: "刘小雪", hanzi: "有的人虽然很聪明，但是会在简单的事情中出错，因为他们认为事情简单，就不会认真去做了。", pinyin: "Yǒude rén suīrán hěn cōngming, dànshì huì zài jiǎndān de shìqing zhōng chū cuò, yīnwèi tāmen rènwéi shìqing jiǎndān, jiù bú huì rènzhēn qù zuò le.", en: "Some smart people make mistakes in simple tasks because they think the tasks are easy and do not work carefully.", th: "บางคนแม้ฉลาดแต่ผิดในเรื่องง่าย เพราะคิดว่าง่ายจึงไม่ตั้งใจทำ", visual: visual("在简单的事情中出错", "ผิดในเรื่องง่าย", "36% center") }),
      line(buildingRef, { role: "B", speaker: "同学", hanzi: "你说的就是我，以后我要多向认真的人学习。", pinyin: "Nǐ shuō de jiù shì wǒ, yǐhòu wǒ yào duō xiàng rènzhēn de rén xuéxí.", en: "You are describing me. From now on I should learn more from conscientious people.", th: "ที่เธอพูดก็คือฉัน ต่อไปฉันจะเรียนรู้จากคนที่ตั้งใจให้มากขึ้น", visual: visual("向认真的人学习", "เรียนรู้จากคนที่ตั้งใจ", "64% center") }),
    ],
    qte: { after: 3, prompt: { zh: "同学为什么害怕见李老师？", th: "ทำไมเพื่อนร่วมชั้นจึงกลัวพบครูหลี่?", en: "Why is the classmate afraid to see Teacher Li?" }, options: [{ value: "怕老师生气", zh: "怕老师生气", pinyin: "pà lǎoshī shēngqì", th: "กลัวครูโกรธ" }, { value: "走错了楼梯", zh: "走错了楼梯", pinyin: "zǒu cuò le lóutī", th: "ขึ้นบันไดผิด" }, { value: "忘了带书", zh: "忘了带书", pinyin: "wàng le dài shū", th: "ลืมนำหนังสือมา" }], correct: "怕老师生气", evidence: "同学：我怕李老师生气。", evidenceTh: "เพื่อนร่วมชั้น: ฉันกลัวครูหลี่โกรธ", sourceRef: buildingRef },
    builder: { prompt: { zh: "重组“向”字句", th: "เรียงประโยคที่ใช้ 向", en: "Rebuild the 向 sentence" }, answer: ["以后我要", "多向", "认真的人", "学习"], tiles: ["学习", "认真的人", "以后我要", "多向"], gloss: { 以后我要: "ต่อไปฉันจะ", 多向: "เรียนจาก...ให้มาก", 认真的人: "คนที่ตั้งใจ", 学习: "เรียนรู้" }, translationTh: "ต่อไปฉันจะเรียนรู้จากคนที่ตั้งใจให้มาก", translationEn: "From now on I will learn more from conscientious people.", evidence: "Text 1 · หน้าเล่ม 155", sourceRef: buildingRef },
  },
  {
    id: "h3l17-reading-room", number: "02", glyph: "学", title: "继续学习的方向", titleTh: "ทิศทางการเรียนต่อ", titleEn: "A direction for further study", place: "阅览室门口", placeTh: "หน้าห้องอ่านหนังสือ", ...art("reading-room"), source: "Text 2 · หน้าเล่ม 156–157 · PDF หน้า 168–169", sourcePage: "156-157", sourceRef: readingRef,
    imageAlt: { zh: "图书馆阅览室", th: "ห้องอ่านหนังสือในห้องสมุด", en: "A library reading room" }, context: "在阅览室门口，白家月碰到了陈天中。", contextTh: "หน้าห้องอ่านหนังสือ ไป๋เจียเยว่พบเฉินเทียนจง", contextEn: "At the reading room entrance, Bai Jiayue ran into Chen Tianzhong.", characters: [{ role: "A", profile: "bai", noteZh: "关心同学计划的人", noteTh: "ผู้สนใจแผนของเพื่อน", noteEn: "The friend asking about plans" }, { role: "B", profile: "chen", noteZh: "想继续学习的人", noteTh: "ผู้ที่อยากเรียนต่อ", noteEn: "The student considering further study" }],
    lines: [
      line(readingRef, { role: "A", speaker: "白家月", hanzi: "太阳从西边出来了？这几天怎么总是在图书馆看见你？", pinyin: "Tàiyáng cóng xībian chūlai le? Zhè jǐ tiān zěnme zǒngshì zài túshūguǎn kànjiàn nǐ?", en: "Has the sun risen in the west? Why do I keep seeing you at the library lately?", th: "พระอาทิตย์ขึ้นทางตะวันตกหรือ? ช่วงนี้ทำไมเห็นเธอที่ห้องสมุดตลอด?", visual: visual("太阳从西边出来了", "พระอาทิตย์ขึ้นทางตะวันตก", "30% center") }),
      line(readingRef, { role: "B", speaker: "陈天中", hanzi: "这有什么奇怪的？我是来学习的。", pinyin: "Zhè yǒu shénme qíguài de? Wǒ shì lái xuéxí de.", en: "What is strange about that? I came to study.", th: "แปลกตรงไหน? ฉันมาเรียน", visual: visual("我是来学习的", "ฉันมาเรียน", "70% center") }),
      line(readingRef, { role: "A", speaker: "白家月", hanzi: "你怎么还来图书馆学习？同学们都在到处找工作呢。", pinyin: "Nǐ zěnme hái lái túshūguǎn xuéxí? Tóngxuémen dōu zài dàochù zhǎo gōngzuò ne.", en: "Why are you still studying at the library? Our classmates are looking for jobs everywhere.", th: "ทำไมเธอยังมาเรียนที่ห้องสมุด? เพื่อน ๆ กำลังหางานกันทุกที่", visual: visual("到处找工作", "หางานทุกที่", "32% center") }),
      line(readingRef, { role: "B", speaker: "陈天中", hanzi: "我不想现在就工作，还想继续学习，我爸妈也同意。可我还没想好学什么，所以来图书馆看看。", pinyin: "Wǒ bù xiǎng xiànzài jiù gōngzuò, hái xiǎng jìxù xuéxí, wǒ bàmā yě tóngyì. Kě wǒ hái méi xiǎng hǎo xué shénme, suǒyǐ lái túshūguǎn kànkan.", en: "I do not want to work yet; I want to continue studying, and my parents agree. But I have not decided what to study, so I came to look around.", th: "ฉันยังไม่อยากทำงาน อยากเรียนต่อ พ่อแม่ก็เห็นด้วย แต่ยังไม่ตัดสินใจว่าจะเรียนอะไร จึงมาดูที่ห้องสมุด", visual: visual("还想继续学习", "ยังอยากเรียนต่อ", "68% center") }),
      line(readingRef, { role: "A", speaker: "白家月", hanzi: "你不是喜欢玩电脑吗？你可以去看看跟电脑有关系的书。", pinyin: "Nǐ bú shì xǐhuan wán diànnǎo ma? Nǐ kěyǐ qù kànkan gēn diànnǎo yǒu guānxi de shū.", en: "Do you not like computers? You could look at books related to computers.", th: "เธอชอบคอมพิวเตอร์ไม่ใช่หรือ? ลองดูหนังสือที่เกี่ยวข้องกับคอมพิวเตอร์สิ", visual: visual("跟电脑有关系的书", "หนังสือเกี่ยวกับคอมพิวเตอร์", "34% center") }),
      line(readingRef, { role: "B", speaker: "陈天中", hanzi: "你说得对，我记得那个屋子里有些跟电脑有关的书，我去找找。", pinyin: "Nǐ shuō de duì, wǒ jìde nàge wūzi li yǒuxiē gēn diànnǎo yǒuguān de shū, wǒ qù zhǎozhao.", en: "You are right. I remember there are computer-related books in that room. I will look for them.", th: "เธอพูดถูก ฉันจำได้ว่าห้องนั้นมีหนังสือเกี่ยวกับคอมพิวเตอร์ จะไปหา", visual: visual("去找找有关的书", "ไปหาหนังสือที่เกี่ยวข้อง", "66% center") }),
    ],
    qte: { after: 3, prompt: { zh: "陈天中为什么来图书馆？", th: "ทำไมเฉินเทียนจงมาห้องสมุด?", en: "Why did Chen Tianzhong come to the library?" }, options: [{ value: "想继续学习", zh: "想继续学习", pinyin: "xiǎng jìxù xuéxí", th: "อยากเรียนต่อ" }, { value: "马上找工作", zh: "马上找工作", pinyin: "mǎshàng zhǎo gōngzuò", th: "หางานทันที" }, { value: "等白家月", zh: "等白家月", pinyin: "děng Bái Jiāyuè", th: "รอไป๋เจียเยว่" }], correct: "想继续学习", evidence: "陈天中：还想继续学习。", evidenceTh: "เฉินเทียนจง: ยังอยากเรียนต่อ", sourceRef: readingRef },
    builder: { prompt: { zh: "重组反问句", th: "เรียงประโยคคำถามเชิงย้อน", en: "Rebuild the rhetorical question" }, answer: ["你不是", "喜欢玩电脑", "吗"], tiles: ["吗", "你不是", "喜欢玩电脑"], gloss: { 你不是: "เธอไม่ใช่ว่า", 喜欢玩电脑: "ชอบใช้คอมพิวเตอร์", 吗: "หรือ" }, translationTh: "เธอชอบคอมพิวเตอร์ไม่ใช่หรือ?", translationEn: "Do you not like computers?", evidence: "Text 2 · หน้าเล่ม 157", sourceRef: readingRef },
  },
  {
    id: "h3l17-campus", number: "03", glyph: "留", title: "留学去哪里", titleTh: "จะไปเรียนต่อต่างประเทศที่ไหน", titleEn: "Where to study abroad", place: "校园",
    placePy: "xiàoyuán", placeTh: "มหาวิทยาลัย", ...art("campus"), source: "Text 3 · หน้าเล่ม 158–159 · PDF หน้า 170–171", sourcePage: "158-159", sourceRef: campusRef,
    imageAlt: { zh: "校园谈留学场景", th: "คุยเรื่องเรียนต่อต่างประเทศในมหาวิทยาลัย", en: "Discussing study abroad on campus" }, context: "在校园里，李文和陈天中在聊天儿。", contextTh: "ในมหาวิทยาลัย หลี่เหวินกับเฉินเทียนจงคุยกัน", contextEn: "On campus, Li Wen and Chen Tianzhong were chatting.", characters: [{ role: "A", profile: "liWen", noteZh: "给留学建议的人", noteTh: "ผู้ให้คำแนะนำเรื่องเรียนต่อ", noteEn: "The friend giving advice" }, { role: "B", profile: "chen", noteZh: "考虑留学的人", noteTh: "ผู้กำลังพิจารณาเรียนต่อ", noteEn: "The prospective international student" }],
    lines: [
      line(campusRef, { role: "A", speaker: "李文", hanzi: "天中，你的手机怎么关机了？", pinyin: "Tiānzhōng, nǐ de shǒujī zěnme guānjī le?", en: "Tianzhong, why is your phone turned off?", th: "เทียนจง ทำไมโทรศัพท์เธอปิดเครื่อง?", visual: visual("手机怎么关机了", "ทำไมโทรศัพท์ปิดเครื่อง", "30% center") }),
      line(campusRef, { role: "B", speaker: "陈天中", hanzi: "我的手机没电了。你找我有事吗？", pinyin: "Wǒ de shǒujī méi diàn le. Nǐ zhǎo wǒ yǒu shì ma?", en: "My phone is out of power. Do you need me for something?", th: "โทรศัพท์ฉันแบตหมด เธอมีธุระกับฉันหรือ?", visual: visual("手机没电了", "โทรศัพท์แบตหมด", "70% center") }),
      line(campusRef, { role: "A", speaker: "李文", hanzi: "前天我看见家月了，她告诉我你打算继续留学？", pinyin: "Qiántiān wǒ kànjiàn Jiāyuè le, tā gàosu wǒ nǐ dǎsuàn jìxù liúxué?", en: "I saw Jiayue the day before yesterday. She said you plan to continue studying abroad?", th: "เมื่อวานซืนฉันพบเจียเยว่ เธอบอกว่าเธอวางแผนเรียนต่อต่างประเทศ?", visual: visual("打算继续留学", "วางแผนเรียนต่อต่างประเทศ", "32% center") }),
      line(campusRef, { role: "B", speaker: "陈天中", hanzi: "是，可是我还没想好学什么，更没想好去哪个国家。", pinyin: "Shì, kěshì wǒ hái méi xiǎng hǎo xué shénme, gèng méi xiǎng hǎo qù nǎge guójiā.", en: "Yes, but I have not decided what to study, much less which country to choose.", th: "ใช่ แต่ฉันยังไม่ตัดสินใจว่าจะเรียนอะไร ยิ่งยังไม่รู้ว่าจะไปประเทศไหน", visual: visual("更没想好去哪个国家", "ยิ่งยังไม่รู้ว่าจะไปประเทศไหน", "68% center") }),
      line(campusRef, { role: "A", speaker: "李文", hanzi: "你可以去中国学中文啊。比如可以去北京、上海这样的大城市，那里有很多好大学，也有很多留学生。", pinyin: "Nǐ kěyǐ qù Zhōngguó xué Zhōngwén a. Bǐrú kěyǐ qù Běijīng, Shànghǎi zhèyàng de dà chéngshì, nàli yǒu hěn duō hǎo dàxué, yě yǒu hěn duō liúxuéshēng.", en: "You could study Chinese in China—for example, in Beijing or Shanghai, where there are many good universities and international students.", th: "เธอไปเรียนภาษาจีนที่จีนได้ เช่นเมืองใหญ่อย่างปักกิ่งหรือเซี่ยงไฮ้ ที่นั่นมีมหาวิทยาลัยดีและนักศึกษาต่างชาติมาก", visual: visual("比如北京、上海", "เช่นปักกิ่ง เซี่ยงไฮ้", "34% center") }),
      line(campusRef, { role: "B", speaker: "陈天中", hanzi: "好，那我上网查一查。", pinyin: "Hǎo, nà wǒ shàngwǎng chá yì chá.", en: "All right, I will look it up online.", th: "ได้ งั้นฉันจะค้นทางอินเทอร์เน็ต", visual: visual("上网查一查", "ค้นทางอินเทอร์เน็ต", "66% center") }),
      line(campusRef, { role: "A", speaker: "李文", hanzi: "我给你介绍几个有用的网站。", pinyin: "Wǒ gěi nǐ jièshào jǐ ge yǒuyòng de wǎngzhàn.", en: "I will introduce a few useful websites to you.", th: "ฉันจะแนะนำเว็บไซต์ที่มีประโยชน์ให้เธอสักสองสามแห่ง", visual: visual("有用的网站", "เว็บไซต์ที่มีประโยชน์", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "陈天中为什么还没决定去哪个国家？", th: "ทำไมเฉินเทียนจงยังไม่ตัดสินใจว่าจะไปประเทศไหน?", en: "Why has Chen Tianzhong not chosen a country?" }, options: [{ value: "还没想好学什么", zh: "还没想好学什么", pinyin: "hái méi xiǎng hǎo xué shénme", th: "ยังไม่ตัดสินใจว่าจะเรียนอะไร" }, { value: "父母不同意", zh: "父母不同意", pinyin: "fùmǔ bù tóngyì", th: "พ่อแม่ไม่เห็นด้วย" }, { value: "手机没电", zh: "手机没电", pinyin: "shǒujī méi diàn", th: "โทรศัพท์แบตหมด" }], correct: "还没想好学什么", evidence: "陈天中：我还没想好学什么，更没想好去哪个国家。", evidenceTh: "เฉินเทียนจง: ยังไม่ตัดสินใจว่าจะเรียนอะไร ยิ่งยังไม่รู้ว่าจะไปประเทศไหน", sourceRef: campusRef },
    builder: { prompt: { zh: "重组递进复句", th: "เรียงประโยคความหมายเพิ่มระดับ", en: "Rebuild the progressive sentence" }, answer: ["我还没想好", "学什么", "更没想好", "去哪个国家"], tiles: ["去哪个国家", "更没想好", "学什么", "我还没想好"], gloss: { 我还没想好: "ฉันยังไม่ตัดสินใจ", 学什么: "ว่าจะเรียนอะไร", 更没想好: "ยิ่งยังไม่ตัดสินใจ", 去哪个国家: "ว่าจะไปประเทศไหน" }, translationTh: "ฉันยังไม่ตัดสินใจว่าจะเรียนอะไร ยิ่งยังไม่รู้ว่าจะไปประเทศไหน", translationEn: "I have not decided what to study, much less which country to choose.", evidence: "Text 3 · หน้าเล่ม 158", sourceRef: campusRef },
  },
];
export const LESSON_HSK3_L17 = {
  id: "hsk3-l17", slug: "lesson-17", level: "hsk3", number: 17, featured: false, sourceRef,
  source: { title: "新HSK教程 3 · New HSK Course 3", lesson: "Lesson 17 · 我要多向认真的人学习", printedPages: "154–162", pdfPages: "166–174", file: "hsk3.pdf", sourceRef },
  title: { zh: "我要多向认真的人学习", pinyin: "Wǒ yào duō xiàng rènzhēn de rén xuéxí", en: "I should learn more from conscientious people", thAid: "ฉันควรเรียนรู้จากคนที่ตั้งใจให้มากขึ้น" },
  summary: { zh: "谈面对错误、继续学习和选择留学方向。", en: "Discuss facing mistakes, further study, and choosing a study-abroad direction.", thAid: "พูดคุยเรื่องการเผชิญข้อผิดพลาด การเรียนต่อ และการเลือกทิศทางศึกษาต่างประเทศ" }, translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并表达内心难过、困惑、不满等情绪。", en: "Be able to understand and express emotions such as sadness, confusion, and dissatisfaction.", thAid: "ฟังเข้าใจและแสดงอารมณ์ภายใน เช่น ความเสียใจ ความสับสน และความไม่พอใจ", sourceRef: lessonHsk3L17SourceRef("154", "166") },
    { zh: "能听懂并使用反问句“不是……吗？”表达情感和语气。", en: "Be able to understand and use the rhetorical question 不是……吗？ to convey emotion and tone.", thAid: "ฟังเข้าใจและใช้คำถามเชิงย้อน 不是……吗？ เพื่อสื่ออารมณ์และน้ำเสียง", sourceRef: lessonHsk3L17SourceRef("154", "166") },
    { zh: "掌握“只有”的用法，能表达唯一条件和结果。", en: "Master 只有 to express the sole condition and its result.", thAid: "ใช้ 只有 เพื่อบอกเงื่อนไขเพียงหนึ่งเดียวและผลลัพธ์", sourceRef: lessonHsk3L17SourceRef("154", "166") },
  ],
  contents: [{ number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "154", route: "/home/hsk3/lesson-17/preface/", sourceRef: lessonHsk3L17SourceRef("154", "166") }, { number: "01", title: "别害怕见老师", titleTh: "อย่ากลัวที่จะพบครู", detail: "Text 1 · New Words 1–8", pages: "155–156", scene: 1, sourceRef: lessonHsk3L17SourceRef("155-156", "167-168") }, { number: "02", title: "继续学习的方向", titleTh: "ทิศทางการเรียนต่อ", detail: "Text 2 · New Words 9–14", pages: "156–157", scene: 2, sourceRef: readingRef }, { number: "03", title: "留学去哪里", titleTh: "จะไปเรียนต่อต่างประเทศที่ไหน", detail: "Text 3 · New Words 15–21", pages: "158–159", scene: 3, sourceRef: campusRef }, { number: "04", title: "选择方向、练习与活动", titleTh: "เลือกทิศทาง แบบฝึก และกิจกรรม", detail: "Text 4 · Exercises · Activity", pages: "159–162", sourceRef: lessonHsk3L17SourceRef("159-162", "171-174") }], vocabulary,
  grammarFocus: [
    { title: "介词“向”", titleEn: "Preposition 向", explanationZh: "后加代词、名词或名词性短语，表示动作的方向或对象。", explanationEn: "向 precedes a pronoun, noun, or noun phrase to mark the direction or target of an action.", thAid: "วางหน้าคำสรรพนามหรือนาม เพื่อบอกทิศทางหรือเป้าหมายของการกระทำ", examples: ["以后我要多向认真的人学习。", "孩子一看见妈妈，就向她跑过去了。"], sourceRef: lessonHsk3L17SourceRef("156", "168") },
    { title: "反问句“不是……吗？”", titleEn: "Rhetorical question 不是……吗？", explanationZh: "表达不理解、不满、提醒或确认，形式否定但表达肯定意思。", explanationEn: "The negative-form rhetorical question expresses confusion, dissatisfaction, reminder, or confirmation with affirmative force.", thAid: "คำถามเชิงย้อน รูปปฏิเสธแต่สื่อความหมายยืนยัน ใช้เตือน ย้ำ หรือแสดงความไม่เข้าใจ", examples: ["你不是喜欢玩电脑吗？", "考试不是下个月吗？"], sourceRef: lessonHsk3L17SourceRef("157", "169") },
    { title: "递进复句“……，更……”", titleEn: "Progressive complex sentence ……，更……", explanationZh: "第二个分句在程度上比前一个分句更深一层。", explanationEn: "The second clause increases the degree or force of the first.", thAid: "อนุประโยคที่สองเพิ่มระดับความหมายให้ลึกหรือหนักขึ้น", examples: ["我还没想好学什么，更没想好去哪个国家。", "想提高中文水平要多听多看，更要多说多练。"], sourceRef: lessonHsk3L17SourceRef("159", "171") },
  ], characters, scenes,
};
