import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk3.pdf";
export const lessonHsk3L13SourceRef = (printedPages, pdfPages) => `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
const sourceRef = lessonHsk3L13SourceRef("115-123", "127-135");
const art = (scene) => ({ image: group3AssetPath(`/assets/group3/lesson-hsk3-l13-${scene}-v1.webp`), imageSrcSet: `${group3AssetPath(`/assets/group3/lesson-hsk3-l13-${scene}-720w-v1.webp`)} 720w, ${group3AssetPath(`/assets/group3/lesson-hsk3-l13-${scene}-v1.webp`)} 1400w` });
const line = (ref, value) => ({ ...value, reading: value.pinyin, sourceRef: ref });
const visual = (zh, th, focus) => ({ zh, th, focus });
const vocabularyRows = [
  [1, "请客", "qǐngkè", "v.", "stand treat", "เลี้ยงอาหาร", 116, 128], [2, "南方", "nánfāng", "n.", "south", "ภาคใต้", 116, 128], [3, "北方", "běifāng", "n.", "north", "ภาคเหนือ", 116, 128], [4, "做法", "zuòfǎ", "n.", "way of doing or making", "วิธีทำ", 116, 128], [5, "不同", "bù tóng", "adj.", "different", "แตกต่าง", 116, 128], [6, "加", "jiā", "v.", "add", "เพิ่ม", 116, 128], [7, "的话", "de huà", "phrase", "if", "ถ้า", 116, 128], [8, "做客", "zuòkè", "v.", "be a guest", "ไปเป็นแขก", 116, 128],
  [9, "邻居", "línjū", "n.", "neighbor", "เพื่อนบ้าน", 118, 130], [10, "放心", "fàngxīn", "v.", "feel at ease", "วางใจ", 118, 130], [11, "酒", "jiǔ", "n.", "alcoholic drink; wine", "เหล้า / ไวน์", 118, 130], [12, "放", "fàng", "v.", "put", "วาง / ใส่", 118, 130], [13, "客人", "kèrén", "n.", "guest", "แขก", 118, 130],
  [14, "晚会", "wǎnhuì", "n.", "evening party", "งานเลี้ยงตอนเย็น", 120, 132], [15, "礼物", "lǐwù", "n.", "gift; present", "ของขวัญ", 120, 132], [16, "画家", "huàjiā", "n.", "painter", "จิตรกร", 120, 132], [17, "盘子", "pánzi", "n.", "plate", "จาน", 120, 132], [18, "一边", "yìbiān", "adv.", "at the same time", "ไปพร้อมกัน", 120, 132], [19, "聊天儿", "liáotiānr", "v.", "chat", "พูดคุย", 120, 132],
  [20, "来自", "láizì", "v.", "come from", "มาจาก", 122, 134], [21, "夫妻", "fūqī", "n.", "husband and wife", "คู่สามีภรรยา", 122, 134], [22, "直到", "zhídào", "prep.", "until", "จนกระทั่ง", 122, 134], [23, "地图", "dìtú", "n.", "map", "แผนที่", 122, 134], [24, "点", "diǎn", "n.", "dot; spot", "จุด", 122, 134], [25, "感到", "gǎndào", "v.", "feel", "รู้สึก", 122, 134], [26, "东方", "dōngfāng", "n.", "East", "ตะวันออก", 122, 134], [27, "文化", "wénhuà", "n.", "culture", "วัฒนธรรม", 122, 134],
];
const vocabulary = vocabularyRows.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({ index, hanzi, pinyin, type, en, th: thAid, thAid, page, translationKind: "editorial-aid", sourceRef: lessonHsk3L13SourceRef(String(page), String(pdfPage)) }));
const restaurantRef = lessonHsk3L13SourceRef("116", "128");
const prepRef = lessonHsk3L13SourceRef("118", "130");
const birthdayRef = lessonHsk3L13SourceRef("119", "131");
const characters = {
  yang: { hanzi: "杨同乐", pinyin: "Yáng Tónglè", nameTh: "หยางถงเล่อ", nameEn: "Yang Tongle", ...art("restaurant"), imageFocus: "30% center" },
  wang: { hanzi: "王一雪", pinyin: "Wáng Yìxuě", nameTh: "หวังอี้เสวี่ย", nameEn: "Wang Yixue", ...art("restaurant"), imageFocus: "50% center" },
  colleague: { hanzi: "同事", pinyin: "Tóngshì", nameTh: "เพื่อนร่วมงาน", nameEn: "Colleague", ...art("restaurant"), imageFocus: "70% center" },
  liu: { hanzi: "刘明", pinyin: "Liú Míng", nameTh: "หลิวหมิง", nameEn: "Liu Ming", ...art("party-prep"), imageFocus: "66% center" },
  liuXiaoming: { hanzi: "刘小明", pinyin: "Liú Xiǎomíng", nameTh: "หลิวเสี่ยวหมิง", nameEn: "Liu Xiaoming", ...art("birthday"), imageFocus: "66% center" },
};
const scenes = [
  {
    id: "h3l13-restaurant", number: "01", glyph: "客", title: "请同事吃饭", titleTh: "เลี้ยงอาหารเพื่อนร่วมงาน", titleEn: "Treating colleagues to dinner", place: "饭馆",
    placePy: "fànguǎn", placeTh: "ร้านอาหาร", ...art("restaurant"), source: "Text 1 · หน้าเล่ม 116 · PDF หน้า 128", sourcePage: "116", sourceRef: restaurantRef,
    imageAlt: { zh: "饭馆请客场景", th: "หยางถงเล่อเลี้ยงอาหารเพื่อนร่วมงาน", en: "Yang Tongle treating colleagues to dinner" }, context: "在饭馆，杨同乐请同事吃饭。", contextTh: "ที่ร้านอาหาร หยางถงเล่อเลี้ยงอาหารเพื่อนร่วมงาน", contextEn: "At a restaurant, Yang Tongle treated his colleagues to dinner.", characters: [{ role: "A", profile: "yang", noteZh: "今天请客的人", noteTh: "เจ้าภาพของมื้อนี้", noteEn: "The host" }, { role: "B", profile: "wang", noteZh: "受邀的同事", noteTh: "เพื่อนร่วมงานที่ได้รับเชิญ", noteEn: "An invited colleague" }, { role: "C", profile: "colleague", noteZh: "不常吃南方菜的同事", noteTh: "เพื่อนร่วมงานที่ไม่ค่อยกินอาหารใต้", noteEn: "A colleague unfamiliar with southern cuisine" }],
    lines: [
      line(restaurantRef, { role: "A", speaker: "杨同乐", hanzi: "今天我请客，你们想吃什么就点什么！", pinyin: "Jīntiān wǒ qǐngkè, nǐmen xiǎng chī shénme jiù diǎn shénme!", en: "It is my treat today. Order whatever you want!", th: "วันนี้ฉันเลี้ยง อยากกินอะไรก็สั่งเลย!", visual: visual("今天我请客", "วันนี้ฉันเลี้ยง", "30% center") }),
      line(restaurantRef, { role: "B", speaker: "王一雪", hanzi: "那我就不客气了。听说这家饭馆的鱼做得很特别？", pinyin: "Nà wǒ jiù bú kèqi le. Tīngshuō zhè jiā fànguǎn de yú zuò de hěn tèbié?", en: "Then I will help myself. I heard this restaurant prepares fish in a special way?", th: "งั้นฉันไม่เกรงใจแล้ว ได้ยินว่าร้านนี้ทำปลาพิเศษมากใช่ไหม?", visual: visual("鱼做得很特别", "ทำปลาได้พิเศษ", "50% center") }),
      line(restaurantRef, { role: "A", speaker: "杨同乐", hanzi: "对，南方菜跟你们北方菜的做法不同。除了鱼，你们还想吃什么？", pinyin: "Duì, nánfāng cài gēn nǐmen běifāng cài de zuòfǎ bù tóng. Chúle yú, nǐmen hái xiǎng chī shénme?", en: "Yes. Southern cooking differs from northern cooking. Besides fish, what else would you like?", th: "ใช่ วิธีทำอาหารใต้ต่างจากอาหารเหนือ นอกจากปลาแล้วอยากกินอะไรอีก?", visual: visual("做法不同", "วิธีทำต่างกัน", "70% center") }),
      line(restaurantRef, { role: "C", speaker: "同事", hanzi: "我不常吃南方菜，还是你决定吧。", pinyin: "Wǒ bù cháng chī nánfāng cài, háishi nǐ juédìng ba.", en: "I do not often eat southern food, so you decide.", th: "ฉันไม่ค่อยกินอาหารใต้ ให้เธอตัดสินใจเถอะ", visual: visual("还是你决定吧", "ให้เธอตัดสินใจ", "34% center") }),
      line(restaurantRef, { role: "A", speaker: "杨同乐", hanzi: "好，那再加一个鸡肉。", pinyin: "Hǎo, nà zài jiā yí ge jīròu.", en: "All right, then let us add a chicken dish.", th: "ได้ งั้นเพิ่มเมนูไก่อีกหนึ่งอย่าง", visual: visual("再加一个鸡肉", "เพิ่มเมนูไก่", "66% center") }),
      line(restaurantRef, { role: "B", speaker: "王一雪", hanzi: "咱们就三个人，别点那么多。", pinyin: "Zánmen jiù sān ge rén, bié diǎn nàme duō.", en: "There are only three of us; do not order so much.", th: "เรามีแค่สามคน อย่าสั่งมากขนาดนั้น", visual: visual("就三个人", "มีแค่สามคน", "38% center") }),
      line(restaurantRef, { role: "A", speaker: "杨同乐", hanzi: "好，那先来这几个菜。", pinyin: "Hǎo, nà xiān lái zhè jǐ ge cài.", en: "All right, we will start with these dishes.", th: "ได้ งั้นเอาเมนูเหล่านี้ก่อน", visual: visual("先来这几个菜", "เอาเมนูเหล่านี้ก่อน", "62% center") }),
      line(restaurantRef, { role: "B", speaker: "王一雪", hanzi: "对了，下周我儿子过生日，你们有时间的话，就来我家做客，我给你们做北京菜。", pinyin: "Duì le, xià zhōu wǒ érzi guò shēngrì, nǐmen yǒu shíjiān de huà, jiù lái wǒ jiā zuòkè, wǒ gěi nǐmen zuò Běijīng cài.", en: "By the way, it is my son's birthday next week. If you have time, come to my home and I will cook Beijing food.", th: "จริงสิ สัปดาห์หน้าลูกชายฉันเกิด ถ้ามีเวลาก็มาที่บ้าน ฉันจะทำอาหารปักกิ่งให้", visual: visual("有时间的话就来", "ถ้ามีเวลาก็มา", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "王一雪为什么请同事来家里？", th: "ทำไมหวังอี้เสวี่ยจึงชวนเพื่อนร่วมงานมาบ้าน?", en: "Why did Wang Yixue invite her colleagues home?" }, options: [{ value: "儿子过生日", zh: "儿子过生日", pinyin: "érzi guò shēngrì", th: "ลูกชายฉลองวันเกิด" }, { value: "搬新家", zh: "搬新家", pinyin: "bān xīn jiā", th: "ย้ายบ้านใหม่" }, { value: "练习做菜", zh: "练习做菜", pinyin: "liànxí zuò cài", th: "ฝึกทำอาหาร" }], correct: "儿子过生日", evidence: "王一雪：下周我儿子过生日。", evidenceTh: "หวังอี้เสวี่ย: สัปดาห์หน้าลูกชายฉันเกิด", sourceRef: restaurantRef },
    builder: { prompt: { zh: "重组假设复句", th: "เรียงประโยคเงื่อนไข", en: "Rebuild the hypothetical sentence" }, answer: ["你们有时间", "的话", "就来", "我家做客"], tiles: ["我家做客", "你们有时间", "就来", "的话"], gloss: { 你们有时间: "พวกคุณมีเวลา", 的话: "ถ้า", 就来: "ก็มา", 我家做客: "เป็นแขกที่บ้านฉัน" }, translationTh: "ถ้าพวกคุณมีเวลาก็มาที่บ้านฉัน", translationEn: "If you have time, come visit my home.", evidence: "Text 1 · หน้าเล่ม 116", sourceRef: restaurantRef },
  },
  {
    id: "h3l13-party-prep", number: "02", glyph: "备", title: "准备生日会", titleTh: "เตรียมงานวันเกิด", titleEn: "Preparing the birthday party", place: "家里", placeTh: "ที่บ้าน", ...art("party-prep"), source: "Text 2 · หน้าเล่ม 118 · PDF หน้า 130", sourcePage: "118", sourceRef: prepRef,
    imageAlt: { zh: "家庭生日会准备场景", th: "เตรียมบ้านต้อนรับแขกงานวันเกิด", en: "Preparing the home for birthday guests" }, context: "在家里，王一雪和刘明为生日会做准备。", contextTh: "ที่บ้าน หวังอี้เสวี่ยกับหลิวหมิงเตรียมงานวันเกิด", contextEn: "At home, Wang Yixue and Liu Ming prepared for the birthday party.", characters: [{ role: "A", profile: "wang", noteZh: "担心准备不周的人", noteTh: "ผู้กังวลว่าเตรียมไม่พร้อม", noteEn: "The worried host" }, { role: "B", profile: "liu", noteZh: "帮忙检查准备的人", noteTh: "ผู้ช่วยตรวจความพร้อม", noteEn: "The person checking preparations" }],
    lines: [
      line(prepRef, { role: "A", speaker: "王一雪", hanzi: "第一次请新邻居来做客，总是担心有什么没准备好。", pinyin: "Dì-yī cì qǐng xīn línjū lái zuòkè, zǒngshì dānxīn yǒu shénme méi zhǔnbèi hǎo.", en: "It is our first time inviting the new neighbors, so I keep worrying something is not ready.", th: "นี่เป็นครั้งแรกที่เชิญเพื่อนบ้านใหม่มา จึงกังวลอยู่เสมอว่ามีอะไรยังไม่พร้อม", visual: visual("第一次请新邻居", "เชิญเพื่อนบ้านใหม่ครั้งแรก", "34% center") }),
      line(prepRef, { role: "B", speaker: "刘明", hanzi: "放心吧，我帮你看了，都已经准备好了。", pinyin: "Fàngxīn ba, wǒ bāng nǐ kàn le, dōu yǐjīng zhǔnbèi hǎo le.", en: "Do not worry. I checked for you; everything is ready.", th: "วางใจเถอะ ฉันตรวจให้แล้ว ทุกอย่างพร้อมแล้ว", visual: visual("都准备好了", "ทุกอย่างพร้อมแล้ว", "66% center") }),
      line(prepRef, { role: "A", speaker: "王一雪", hanzi: "我记得刚才已经把饮料拿出来了，怎么不见了？", pinyin: "Wǒ jìde gāngcái yǐjīng bǎ yǐnliào ná chūlai le, zěnme bú jiàn le?", en: "I remember taking the drinks out just now. Why are they gone?", th: "ฉันจำได้ว่าเมื่อครู่เอาเครื่องดื่มออกมาแล้ว ทำไมไม่เห็นแล้ว?", visual: visual("把饮料拿出来", "เอาเครื่องดื่มออกมา", "36% center") }),
      line(prepRef, { role: "B", speaker: "刘明", hanzi: "我把饮料和酒都放进冰箱里了，客人来了再拿出来。", pinyin: "Wǒ bǎ yǐnliào hé jiǔ dōu fàng jìn bīngxiāng li le, kèrén lái le zài ná chūlai.", en: "I put the drinks and wine in the refrigerator. We can take them out when the guests arrive.", th: "ฉันใส่เครื่องดื่มกับไวน์ไว้ในตู้เย็น แขกมาแล้วค่อยเอาออก", visual: visual("放进冰箱里", "ใส่ไว้ในตู้เย็น", "64% center") }),
      line(prepRef, { role: "A", speaker: "王一雪", hanzi: "音乐的声音合适吗？", pinyin: "Yīnyuè de shēngyīn héshì ma?", en: "Is the music volume suitable?", th: "เสียงดนตรีเหมาะไหม?", visual: visual("声音合适吗", "ระดับเสียงเหมาะไหม", "38% center") }),
      line(prepRef, { role: "B", speaker: "刘明", hanzi: "你把声音开得太大了，我去关小一点儿。", pinyin: "Nǐ bǎ shēngyīn kāi de tài dà le, wǒ qù guān xiǎo yìdiǎnr.", en: "You turned it up too loud. I will lower it a little.", th: "เธอเปิดเสียงดังเกินไป ฉันจะไปลดลงหน่อย", visual: visual("把声音开得太大", "เปิดเสียงดังเกินไป", "62% center") }),
      line(prepRef, { role: "A", speaker: "王一雪", hanzi: "好，那我们就等客人来吧。", pinyin: "Hǎo, nà wǒmen jiù děng kèrén lái ba.", en: "All right, then let us wait for the guests.", th: "ได้ งั้นเรารอแขกมากันเถอะ", visual: visual("等客人来", "รอแขกมา", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "刘明把饮料放在哪里？", th: "หลิวหมิงเอาเครื่องดื่มไว้ที่ไหน?", en: "Where did Liu Ming put the drinks?" }, options: [{ value: "冰箱里", zh: "冰箱里", pinyin: "bīngxiāng li", th: "ในตู้เย็น" }, { value: "桌子上", zh: "桌子上", pinyin: "zhuōzi shang", th: "บนโต๊ะ" }, { value: "车里", zh: "车里", pinyin: "chē li", th: "ในรถ" }], correct: "冰箱里", evidence: "刘明：我把饮料和酒都放进冰箱里了。", evidenceTh: "หลิวหมิง: ฉันใส่เครื่องดื่มกับไวน์ไว้ในตู้เย็น", sourceRef: prepRef },
    builder: { prompt: { zh: "重组“把”字句", th: "เรียงประโยค 把", en: "Rebuild the 把 sentence" }, answer: ["我把", "饮料和酒", "都放进", "冰箱里了"], tiles: ["冰箱里了", "饮料和酒", "我把", "都放进"], gloss: { 我把: "ฉันนำ", 饮料和酒: "เครื่องดื่มและไวน์", 都放进: "ใส่ทั้งหมดเข้า", 冰箱里了: "ในตู้เย็นแล้ว" }, translationTh: "ฉันใส่เครื่องดื่มกับไวน์ไว้ในตู้เย็นแล้ว", translationEn: "I put the drinks and wine in the refrigerator.", evidence: "Text 2 · หน้าเล่ม 118", sourceRef: prepRef },
  },
  {
    id: "h3l13-birthday", number: "03", glyph: "礼", title: "参加生日晚会", titleTh: "ร่วมงานเลี้ยงวันเกิด", titleEn: "At the birthday party", place: "家里", placeTh: "ที่บ้าน", ...art("birthday"), source: "Text 3 · หน้าเล่ม 119 · PDF หน้า 131", sourcePage: "119", sourceRef: birthdayRef,
    imageAlt: { zh: "家庭生日晚会", th: "งานวันเกิดของหลิวเสี่ยวหมิง", en: "Liu Xiaoming's birthday party" }, context: "在家里，王一雪和刘明办生日会。", contextTh: "ที่บ้าน หวังอี้เสวี่ยกับหลิวหมิงจัดงานวันเกิด", contextEn: "At home, Wang Yixue and Liu Ming held a birthday party.", characters: [{ role: "A", profile: "wang", noteZh: "生日会主人", noteTh: "เจ้าภาพงานวันเกิด", noteEn: "The party host" }, { role: "B", profile: "yang", noteZh: "带来礼物的客人", noteTh: "แขกที่นำของขวัญมา", noteEn: "The guest bringing a present" }, { role: "C", profile: "liuXiaoming", noteZh: "收到画具的寿星", noteTh: "เจ้าของวันเกิดผู้ได้รับอุปกรณ์วาดภาพ", noteEn: "The birthday child receiving art supplies" }],
    lines: [
      line(birthdayRef, { role: "A", speaker: "王一雪", hanzi: "谢谢你们来参加我儿子的生日晚会，希望大家今晚玩得开心。", pinyin: "Xièxie nǐmen lái cānjiā wǒ érzi de shēngrì wǎnhuì, xīwàng dàjiā jīnwǎn wán de kāixīn.", en: "Thank you for coming to my son's birthday party. I hope everyone has fun tonight.", th: "ขอบคุณที่มางานวันเกิดลูกชายฉัน หวังว่าคืนนี้ทุกคนจะสนุก", visual: visual("参加生日晚会", "ร่วมงานวันเกิด", "34% center") }),
      line(birthdayRef, { role: "B", speaker: "杨同乐", hanzi: "小明，生日快乐！我准备了一个小礼物，希望你喜欢！", pinyin: "Xiǎomíng, shēngrì kuàilè! Wǒ zhǔnbèi le yí ge xiǎo lǐwù, xīwàng nǐ xǐhuan!", en: "Happy birthday, Xiaoming! I prepared a small gift and hope you like it!", th: "เสี่ยวหมิง สุขสันต์วันเกิด! ฉันเตรียมของขวัญเล็ก ๆ หวังว่าเธอจะชอบ", visual: visual("准备了小礼物", "เตรียมของขวัญ", "66% center") }),
      line(birthdayRef, { role: "C", speaker: "刘小明", hanzi: "谢谢您，我可以打开吗？", pinyin: "Xièxie nín, wǒ kěyǐ dǎkāi ma?", en: "Thank you. May I open it?", th: "ขอบคุณครับ ผมเปิดได้ไหม?", visual: visual("可以打开吗", "เปิดได้ไหม", "36% center") }),
      line(birthdayRef, { role: "B", speaker: "杨同乐", hanzi: "当然可以，你妈妈说你跟姐姐一样，都喜欢画画，对吗？", pinyin: "Dāngrán kěyǐ, nǐ māma shuō nǐ gēn jiějie yíyàng, dōu xǐhuan huàhuà, duì ma?", en: "Of course. Your mother said you and your sister both like painting, right?", th: "ได้แน่นอน แม่บอกว่าเธอกับพี่สาวชอบวาดรูปเหมือนกัน ใช่ไหม?", visual: visual("都喜欢画画", "ชอบวาดรูปทั้งคู่", "64% center") }),
      line(birthdayRef, { role: "C", speaker: "刘小明", hanzi: "对，我想做一名画家。啊！画板和画笔，这正是我需要的。我太喜欢了。", pinyin: "Duì, wǒ xiǎng zuò yì míng huàjiā. A! Huàbǎn hé huàbǐ, zhè zhèng shì wǒ xūyào de. Wǒ tài xǐhuan le.", en: "Yes, I want to be a painter. Ah, a drawing board and brushes—exactly what I need. I love them!", th: "ใช่ ผมอยากเป็นจิตรกร อ๊ะ! กระดานวาดรูปกับพู่กัน นี่คือสิ่งที่ผมต้องการพอดี ชอบมาก!", visual: visual("想做一名画家", "อยากเป็นจิตรกร", "38% center") }),
      line(birthdayRef, { role: "A", speaker: "王一雪", hanzi: "我去把盘子拿过来，咱们一边吃蛋糕，一边聊天儿吧。", pinyin: "Wǒ qù bǎ pánzi ná guòlai, zánmen yìbiān chī dàngāo, yìbiān liáotiānr ba.", en: "I will bring the plates. Let us eat cake while chatting.", th: "ฉันจะไปเอาจานมา เรากินเค้กไปคุยไปกันเถอะ", visual: visual("一边吃一边聊天", "กินไปคุยไป", "62% center") }),
    ],
    qte: { after: 3, prompt: { zh: "杨同乐送了什么礼物？", th: "หยางถงเล่อให้ของขวัญอะไร?", en: "What gift did Yang Tongle give?" }, options: [{ value: "画板和画笔", zh: "画板和画笔", pinyin: "huàbǎn hé huàbǐ", th: "กระดานวาดรูปและพู่กัน" }, { value: "地图", zh: "地图", pinyin: "dìtú", th: "แผนที่" }, { value: "词典", zh: "词典", pinyin: "cídiǎn", th: "พจนานุกรม" }], correct: "画板和画笔", evidence: "刘小明：画板和画笔，这正是我需要的。", evidenceTh: "หลิวเสี่ยวหมิง: กระดานวาดรูปกับพู่กันคือสิ่งที่ผมต้องการพอดี", sourceRef: birthdayRef },
    builder: { prompt: { zh: "重组“一边……一边……”句", th: "เรียงประโยคทำสองอย่างพร้อมกัน", en: "Rebuild the simultaneous-action sentence" }, answer: ["咱们", "一边吃蛋糕", "一边", "聊天儿吧"], tiles: ["聊天儿吧", "一边", "咱们", "一边吃蛋糕"], gloss: { 咱们: "พวกเรา", 一边吃蛋糕: "กินเค้กไป", 一边: "พร้อมกันก็", 聊天儿吧: "คุยกันเถอะ" }, translationTh: "พวกเรากินเค้กไปคุยไปกันเถอะ", translationEn: "Let us eat cake while chatting.", evidence: "Text 3 · หน้าเล่ม 119", sourceRef: birthdayRef },
  },
];
export const LESSON_HSK3_L13 = {
  id: "hsk3-l13", slug: "lesson-13", level: "hsk3", number: 13, featured: false, sourceRef,
  source: { title: "新HSK教程 3 · New HSK Course 3", lesson: "Lesson 13 · 我的新邻居来自英国", printedPages: "115–123", pdfPages: "127–135", file: "hsk3.pdf", sourceRef },
  title: { zh: "我的新邻居来自英国", pinyin: "Wǒ de xīn línjū láizì Yīngguó", en: "My new neighbors come from the UK", thAid: "เพื่อนบ้านใหม่ของฉันมาจากอังกฤษ" },
  summary: { zh: "谈请客、做客、生日会和不同地区的生活习惯。", en: "Discuss hosting, visiting, birthday parties, and different living customs.", thAid: "พูดคุยเรื่องการเลี้ยงแขก ไปเป็นแขก งานวันเกิด และวัฒนธรรมการใช้ชีวิตที่ต่างกัน" }, translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并谈论不同地区生活习惯的差异。", en: "Be able to understand and discuss differences in living habits across regions.", thAid: "ฟังเข้าใจและพูดคุยความแตกต่างของวิถีชีวิตในแต่ละพื้นที่", sourceRef: lessonHsk3L13SourceRef("115", "127") },
    { zh: "能听懂并使用感谢、祝福和夸赞等礼貌用语。", en: "Be able to understand and use polite expressions of gratitude, good wishes, and compliments.", thAid: "ฟังเข้าใจและใช้ถ้อยคำสุภาพเพื่อขอบคุณ อวยพร และชื่นชม", sourceRef: lessonHsk3L13SourceRef("115", "127") },
    { zh: "掌握“一边……，一边……”的用法，能描述同时进行的动作。", en: "Master 一边……，一边…… to describe actions occurring simultaneously.", thAid: "ใช้ 一边……，一边…… เพื่อบรรยายการกระทำที่เกิดขึ้นพร้อมกัน", sourceRef: lessonHsk3L13SourceRef("115", "127") },
  ],
  contents: [{ number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "115", route: "/home/hsk3/lesson-13/preface/", sourceRef: lessonHsk3L13SourceRef("115", "127") }, { number: "01", title: "请同事吃饭", titleTh: "เลี้ยงอาหารเพื่อนร่วมงาน", detail: "Text 1 · New Words 1–8", pages: "116–117", scene: 1, sourceRef: lessonHsk3L13SourceRef("116-117", "128-129") }, { number: "02", title: "准备生日会", titleTh: "เตรียมงานวันเกิด", detail: "Text 2 · New Words 9–13", pages: "117–119", scene: 2, sourceRef: lessonHsk3L13SourceRef("117-119", "129-131") }, { number: "03", title: "参加生日晚会", titleTh: "ร่วมงานวันเกิด", detail: "Text 3 · New Words 14–19", pages: "119–121", scene: 3, sourceRef: lessonHsk3L13SourceRef("119-121", "131-133") }, { number: "04", title: "新邻居、练习与活动", titleTh: "เพื่อนบ้านใหม่ แบบฝึก และกิจกรรม", detail: "Text 4 · Exercises · Activity", pages: "121–123", sourceRef: lessonHsk3L13SourceRef("121-123", "133-135") }], vocabulary,
  grammarFocus: [
    { title: "假设复句“……的话，就……”", titleEn: "Hypothetical complex sentence", explanationZh: "前一分句表示假设，后一分句表示由此产生的结果，多用于口语。", explanationEn: "The first clause gives a hypothesis and the second its result, mainly in speech.", thAid: "อนุประโยคแรกตั้งเงื่อนไข ส่วนหลังบอกผลที่ตามมา มักใช้ในภาษาพูด", examples: ["你们有时间的话，就来我家做客。", "明天天气好的话，我就去爬山。"], sourceRef: lessonHsk3L13SourceRef("117", "129") },
    { title: "“把”字句（4）", titleEn: "The 把 Sentence (4)", explanationZh: "动词后使用趋向补语或状态补语，表示事物位置或状态发生变化。", explanationEn: "A directional or state complement after the verb shows a change in position or state.", thAid: "ใช้ส่วนเสริมทิศทางหรือสภาพหลังกริยา เพื่อบอกการเปลี่ยนตำแหน่งหรือสภาพ", examples: ["你把声音开得太大了。", "他把球踢进去了吗？"], sourceRef: lessonHsk3L13SourceRef("118-119", "130-131") },
    { title: "并列复句“一边……，一边……”", titleEn: "Simultaneous-action sentence", explanationZh: "表示两个动作同时进行，也可缩为“边……边……”。", explanationEn: "The pattern marks two actions occurring simultaneously and can shorten to 边……边…….", thAid: "บอกการกระทำสองอย่างที่เกิดพร้อมกัน และย่อเป็น 边……边…… ได้", examples: ["咱们一边吃蛋糕，一边聊天儿吧。", "你不应该边开车边打电话。"], sourceRef: lessonHsk3L13SourceRef("120-121", "132-133") },
  ], characters, scenes,
};
