import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk3.pdf";
export const lessonHsk3L15SourceRef = (printedPages, pdfPages) => `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
const sourceRef = lessonHsk3L15SourceRef("133-143", "145-155");
const art = (scene) => ({ image: group3AssetPath(`/assets/group3/lesson-hsk3-l15-${scene}-v1.webp`), imageSrcSet: `${group3AssetPath(`/assets/group3/lesson-hsk3-l15-${scene}-720w-v1.webp`)} 720w, ${group3AssetPath(`/assets/group3/lesson-hsk3-l15-${scene}-v1.webp`)} 1400w` });
const line = (ref, value) => ({ ...value, reading: value.pinyin, sourceRef: ref });
const visual = (zh, th, focus) => ({ zh, th, focus });
const vocabularyRows = [
  [1, "蓝", "lán", "adj.", "blue", "สีน้ำเงิน", 134, 146], [2, "段", "duàn", "m.", "period; section", "ช่วง / ตอน", 134, 146], [3, "附近", "fùjìn", "n.", "nearby", "บริเวณใกล้เคียง", 134, 146], [4, "马路", "mǎlù", "n.", "road", "ถนน", 134, 146], [5, "平时", "píngshí", "n.", "usually; normal times", "ตามปกติ", 134, 146], [6, "放学", "fàngxué", "v.", "school lets out", "เลิกเรียน", 134, 146], [7, "游戏", "yóuxì", "n.", "game", "เกม", 134, 146], [8, "老人", "lǎorén", "n.", "elderly person", "ผู้สูงอายุ", 134, 146], [9, "根据", "gēnjù", "prep./v.", "according to; depend on", "ตาม / อิงจาก", 134, 146],
  [10, "了解", "liǎojiě", "v.", "understand; know", "เข้าใจ / รู้จัก", 136, 148], [11, "可是", "kěshì", "conj.", "but; yet", "แต่ทว่า", 136, 148], [12, "以上", "yǐshàng", "n.", "more than; over", "ขึ้นไป / มากกว่า", 136, 148], [13, "有名", "yǒumíng", "adj.", "famous", "มีชื่อเสียง", 136, 148], [14, "景点", "jǐngdiǎn", "n.", "scenic spot", "สถานที่ท่องเที่ยว", 136, 148], [15, "游客", "yóukè", "n.", "tourist", "นักท่องเที่ยว", 136, 148], [16, "外地", "wàidì", "n.", "other place", "ต่างถิ่น", 136, 148], [17, "聊", "liáo", "v.", "chat", "คุย", 136, 148], [18, "南京", "Nánjīng", "proper n.", "Nanjing", "หนานจิง", 136, 148],
  [19, "河", "hé", "n.", "river", "แม่น้ำ", 138, 150], [20, "关系", "guānxi", "n.", "relationship", "ความสัมพันธ์", 138, 150], [21, "养", "yǎng", "v.", "raise; keep", "เลี้ยงดู", 138, 150], [22, "黄河", "Huáng Hé", "proper n.", "the Yellow River", "แม่น้ำหวงเหอ", 138, 150],
];
const vocabulary = vocabularyRows.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({ index, hanzi, pinyin, type, en, th: thAid, thAid, page, translationKind: "editorial-aid", sourceRef: lessonHsk3L15SourceRef(String(page), String(pdfPage)) }));
const neighborhoodRef = lessonHsk3L15SourceRef("134", "146");
const nanjingRef = lessonHsk3L15SourceRef("136", "148");
const riverRef = lessonHsk3L15SourceRef("137-138", "149-150");
const characters = {
  yang: { hanzi: "杨同乐", pinyin: "Yáng Tónglè", nameTh: "หยางถงเล่อ", nameEn: "Yang Tongle", ...art("neighborhood"), imageFocus: "34% center" },
  wang: { hanzi: "王一雪", pinyin: "Wáng Yìxuě", nameTh: "หวังอี้เสวี่ย", nameEn: "Wang Yixue", ...art("neighborhood"), imageFocus: "66% center" },
  liuXiaoming: { hanzi: "刘小明", pinyin: "Liú Xiǎomíng", nameTh: "หลิวเสี่ยวหมิง", nameEn: "Liu Xiaoming", ...art("yellow-river"), imageFocus: "66% center" },
};
const scenes = [
  {
    id: "h3l15-neighborhood", number: "01", glyph: "蓝", title: "蓝天小区怎么样", titleTh: "ชุมชนหลานเทียนเป็นอย่างไร", titleEn: "Life in Lantian Community", place: "办公室",
    placePy: "bàngōngshì", placeTh: "สำนักงาน", ...art("neighborhood"), source: "Text 1 · หน้าเล่ม 134 · PDF หน้า 146", sourcePage: "134", sourceRef: neighborhoodRef,
    imageAlt: { zh: "蓝天小区环境", th: "สภาพแวดล้อมในชุมชนหลานเทียน", en: "The environment in Lantian Community" }, context: "在办公室里，王一雪和杨同乐在聊天儿。", contextTh: "ในสำนักงาน หวังอี้เสวี่ยกับหยางถงเล่อคุยกัน", contextEn: "In the office, Wang Yixue and Yang Tongle were chatting.", characters: [{ role: "A", profile: "yang", noteZh: "想了解小区的人", noteTh: "ผู้ที่อยากรู้จักชุมชน", noteEn: "The person asking about the community" }, { role: "B", profile: "wang", noteZh: "住在小区的人", noteTh: "ผู้อยู่อาศัยในชุมชน", noteEn: "A community resident" }],
    lines: [
      line(neighborhoodRef, { role: "A", speaker: "杨同乐", hanzi: "您搬到蓝天小区一段时间了，觉得怎么样？", pinyin: "Nín bān dào Lántiān Xiǎoqū yí duàn shíjiān le, juéde zěnmeyàng?", en: "You have lived in Lantian Community for a while. How do you find it?", th: "คุณย้ายมาอยู่ชุมชนหลานเทียนระยะหนึ่งแล้ว รู้สึกว่าเป็นอย่างไรบ้าง?", visual: visual("搬到蓝天小区", "ย้ายมาอยู่ชุมชนหลานเทียน", "34% center") }),
      line(neighborhoodRef, { role: "B", speaker: "王一雪", hanzi: "小区环境挺好的，附近买东西也很方便，过马路就是超市。", pinyin: "Xiǎoqū huánjìng tǐng hǎo de, fùjìn mǎi dōngxi yě hěn fāngbiàn, guò mǎlù jiù shì chāoshì.", en: "The community environment is good. Shopping nearby is convenient, and the supermarket is just across the road.", th: "สภาพแวดล้อมดีมาก ซื้อของใกล้ ๆ ก็สะดวก ข้ามถนนก็ถึงซูเปอร์มาร์เก็ต", visual: visual("过马路就是超市", "ข้ามถนนก็ถึงซูเปอร์มาร์เก็ต", "66% center") }),
      line(neighborhoodRef, { role: "A", speaker: "杨同乐", hanzi: "平时孩子们在哪儿玩？", pinyin: "Píngshí háizimen zài nǎr wán?", en: "Where do the children usually play?", th: "ปกติเด็ก ๆ เล่นที่ไหน?", visual: visual("孩子们在哪儿玩", "เด็ก ๆ เล่นที่ไหน", "36% center") }),
      line(neighborhoodRef, { role: "B", speaker: "王一雪", hanzi: "小区里有很多树，孩子们放学后就在树下做游戏。你想买房子吗？", pinyin: "Xiǎoqū li yǒu hěn duō shù, háizimen fàngxué hòu jiù zài shù xià zuò yóuxì. Nǐ xiǎng mǎi fángzi ma?", en: "There are many trees here, and children play under them after school. Are you thinking of buying a home?", th: "ในชุมชนมีต้นไม้มาก เด็ก ๆ เลิกเรียนแล้วก็เล่นใต้ต้นไม้ คุณอยากซื้อบ้านหรือ?", visual: visual("放学后做游戏", "เลิกเรียนแล้วเล่นเกม", "64% center") }),
      line(neighborhoodRef, { role: "A", speaker: "杨同乐", hanzi: "是。我想买一个大房子，让我爸妈过来跟我一起住。", pinyin: "Shì. Wǒ xiǎng mǎi yí ge dà fángzi, ràng wǒ bàmā guòlai gēn wǒ yìqǐ zhù.", en: "Yes. I want a large home so my parents can come live with me.", th: "ใช่ ฉันอยากซื้อบ้านหลังใหญ่ ให้พ่อแม่มาอยู่กับฉัน", visual: visual("跟我一起住", "มาอยู่ด้วยกัน", "38% center") }),
      line(neighborhoodRef, { role: "B", speaker: "王一雪", hanzi: "蓝天小区的老人挺多的，这几年小区根据他们的需要，有了很多变化。", pinyin: "Lántiān Xiǎoqū de lǎorén tǐng duō de, zhè jǐ nián xiǎoqū gēnjù tāmen de xūyào, yǒu le hěn duō biànhuà.", en: "Many elderly people live here. In recent years the community has changed a lot according to their needs.", th: "ชุมชนนี้มีผู้สูงอายุมาก หลายปีมานี้ชุมชนเปลี่ยนแปลงตามความต้องการของพวกเขามาก", visual: visual("根据他们的需要", "ตามความต้องการของพวกเขา", "62% center") }),
      line(neighborhoodRef, { role: "A", speaker: "杨同乐", hanzi: "真不错！过几天我去蓝天小区看看。", pinyin: "Zhēn búcuò! Guò jǐ tiān wǒ qù Lántiān Xiǎoqū kànkan.", en: "That sounds great! I will visit Lantian Community in a few days.", th: "ดีจริง ๆ! อีกไม่กี่วันฉันจะไปดูชุมชนหลานเทียน", visual: visual("过几天去看看", "อีกไม่กี่วันจะไปดู", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "蓝天小区附近买东西方便吗？", th: "ซื้อของใกล้ชุมชนหลานเทียนสะดวกไหม?", en: "Is shopping near Lantian Community convenient?" }, options: [{ value: "很方便", zh: "很方便", pinyin: "hěn fāngbiàn", th: "สะดวกมาก" }, { value: "不方便", zh: "不方便", pinyin: "bù fāngbiàn", th: "ไม่สะดวก" }, { value: "不知道", zh: "不知道", pinyin: "bù zhīdào", th: "ไม่ทราบ" }], correct: "很方便", evidence: "王一雪：附近买东西也很方便。", evidenceTh: "หวังอี้เสวี่ย: ซื้อของใกล้ ๆ ก็สะดวกมาก", sourceRef: neighborhoodRef },
    builder: { prompt: { zh: "重组“根据”句", th: "เรียงประโยคที่ใช้ 根据", en: "Rebuild the 根据 sentence" }, answer: ["小区", "根据他们的需要", "有了", "很多变化"], tiles: ["很多变化", "小区", "有了", "根据他们的需要"], gloss: { 小区: "ชุมชน", 根据他们的需要: "ตามความต้องการของพวกเขา", 有了: "เกิดขึ้นแล้ว", 很多变化: "การเปลี่ยนแปลงมากมาย" }, translationTh: "ชุมชนเกิดการเปลี่ยนแปลงมากมายตามความต้องการของพวกเขา", translationEn: "The community changed greatly according to their needs.", evidence: "Text 1 · หน้าเล่ม 134", sourceRef: neighborhoodRef },
  },
  {
    id: "h3l15-nanjing", number: "02", glyph: "宁", title: "介绍南京", titleTh: "แนะนำเมืองหนานจิง", titleEn: "Introducing Nanjing", place: "办公室",
    placePy: "bàngōngshì", placeTh: "สำนักงาน", ...art("nanjing"), source: "Text 2 · หน้าเล่ม 136 · PDF หน้า 148", sourcePage: "136", sourceRef: nanjingRef,
    imageAlt: { zh: "南京城市风景", th: "ทิวทัศน์เมืองหนานจิง", en: "A city view of Nanjing" }, context: "在办公室里，王一雪和杨同乐聊南京。", contextTh: "ในสำนักงาน ทั้งสองคุยเรื่องหนานจิง", contextEn: "In the office, Wang Yixue and Yang Tongle discussed Nanjing.", characters: [{ role: "A", profile: "wang", noteZh: "准备去南京旅游的人", noteTh: "ผู้วางแผนเที่ยวหนานจิง", noteEn: "The traveler" }, { role: "B", profile: "yang", noteZh: "熟悉南京的人", noteTh: "ผู้รู้จักหนานจิง", noteEn: "The person familiar with Nanjing" }],
    lines: [
      line(nanjingRef, { role: "A", speaker: "王一雪", hanzi: "假期我想去南京旅游，但是我不太了解那里。", pinyin: "Jiàqī wǒ xiǎng qù Nánjīng lǚyóu, dànshì wǒ bú tài liǎojiě nàli.", en: "I want to travel to Nanjing during the holiday, but I do not know it well.", th: "วันหยุดฉันอยากไปเที่ยวหนานจิง แต่ยังไม่ค่อยรู้จักที่นั่น", visual: visual("去南京旅游", "ไปเที่ยวหนานจิง", "34% center") }),
      line(nanjingRef, { role: "B", speaker: "杨同乐", hanzi: "我虽然不是南京人，可是我是在南京上的大学，可以说是半个南京人。", pinyin: "Wǒ suīrán bú shì Nánjīng rén, kěshì wǒ shì zài Nánjīng shàng de dàxué, kěyǐ shuō shì bàn ge Nánjīng rén.", en: "Although I am not from Nanjing, I attended university there, so I am half a Nanjing local.", th: "แม้ฉันไม่ใช่คนหนานจิง แต่เรียนมหาวิทยาลัยที่นั่น จึงเรียกได้ว่าเป็นคนหนานจิงครึ่งหนึ่ง", visual: visual("半个南京人", "คนหนานจิงครึ่งหนึ่ง", "66% center") }),
      line(nanjingRef, { role: "A", speaker: "王一雪", hanzi: "太好了！你快给我介绍一下南京吧。", pinyin: "Tài hǎo le! Nǐ kuài gěi wǒ jièshào yíxià Nánjīng ba.", en: "Great! Please introduce Nanjing to me.", th: "ยอดเลย! ช่วยแนะนำหนานจิงให้ฉันหน่อย", visual: visual("介绍一下南京", "แนะนำหนานจิง", "36% center") }),
      line(nanjingRef, { role: "B", speaker: "杨同乐", hanzi: "南京有两千年以上的历史，有老城、老街，还有很多有名的景点，每年去旅游的游客特别多。", pinyin: "Nánjīng yǒu liǎng qiān nián yǐshàng de lìshǐ, yǒu lǎochéng, lǎojiē, hái yǒu hěn duō yǒumíng de jǐngdiǎn, měinián qù lǚyóu de yóukè tèbié duō.", en: "Nanjing has over two thousand years of history, an old city, old streets, and many famous sights. Many tourists visit every year.", th: "หนานจิงมีประวัติศาสตร์กว่าสองพันปี มีเมืองเก่า ถนนเก่า และสถานที่ชื่อดังมากมาย ทุกปีมีนักท่องเที่ยวจำนวนมาก", visual: visual("两千年以上的历史", "ประวัติศาสตร์กว่าสองพันปี", "64% center") }),
      line(nanjingRef, { role: "A", speaker: "王一雪", hanzi: "除了这些以外，你再告诉我一些外地人不知道的地方。", pinyin: "Chúle zhèxiē yǐwài, nǐ zài gàosu wǒ yìxiē wàidìrén bù zhīdào de dìfang.", en: "Besides these, tell me about some places outsiders do not know.", th: "นอกจากสิ่งเหล่านี้ บอกสถานที่ที่คนต่างถิ่นไม่รู้จักให้ฉันอีกหน่อย", visual: visual("外地人不知道的地方", "ที่ที่คนต่างถิ่นไม่รู้", "38% center") }),
      line(nanjingRef, { role: "B", speaker: "杨同乐", hanzi: "那太多了，我得一点儿一点儿给您讲。", pinyin: "Nà tài duō le, wǒ děi yìdiǎnr yìdiǎnr gěi nín jiǎng.", en: "There are too many; I will have to tell you little by little.", th: "มีมากเกินไป ฉันต้องค่อย ๆ เล่าให้คุณฟัง", visual: visual("一点儿一点儿讲", "ค่อย ๆ เล่า", "62% center") }),
      line(nanjingRef, { role: "A", speaker: "王一雪", hanzi: "行，下班后我请你吃晚饭，咱们边吃边聊。", pinyin: "Xíng, xiàbān hòu wǒ qǐng nǐ chī wǎnfàn, zánmen biān chī biān liáo.", en: "All right. I will treat you to dinner after work, and we can talk while eating.", th: "ได้ หลังเลิกงานฉันเลี้ยงมื้อเย็น เรากินไปคุยไป", visual: visual("边吃边聊", "กินไปคุยไป", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "杨同乐为什么说自己是半个南京人？", th: "ทำไมหยางถงเล่อจึงบอกว่าเป็นคนหนานจิงครึ่งหนึ่ง?", en: "Why does Yang Tongle call himself half a Nanjing local?" }, options: [{ value: "在南京上大学", zh: "在南京上大学", pinyin: "zài Nánjīng shàng dàxué", th: "เรียนมหาวิทยาลัยที่หนานจิง" }, { value: "出生在南京", zh: "出生在南京", pinyin: "chūshēng zài Nánjīng", th: "เกิดที่หนานจิง" }, { value: "父母住南京", zh: "父母住南京", pinyin: "fùmǔ zhù Nánjīng", th: "พ่อแม่อยู่หนานจิง" }], correct: "在南京上大学", evidence: "杨同乐：我是在南京上的大学。", evidenceTh: "หยางถงเล่อ: ฉันเรียนมหาวิทยาลัยที่หนานจิง", sourceRef: nanjingRef },
    builder: { prompt: { zh: "重组数量重叠句", th: "เรียงประโยคที่ซ้ำวลีบอกจำนวน", en: "Rebuild the reduplicated quantity phrase" }, answer: ["我得", "一点儿一点儿", "给您", "讲"], tiles: ["讲", "给您", "一点儿一点儿", "我得"], gloss: { 我得: "ฉันต้อง", 一点儿一点儿: "ทีละน้อย", 给您: "ให้คุณ", 讲: "เล่า" }, translationTh: "ฉันต้องค่อย ๆ เล่าให้คุณฟัง", translationEn: "I must tell you little by little.", evidence: "Text 2 · หน้าเล่ม 136", sourceRef: nanjingRef },
  },
  {
    id: "h3l15-yellow-river", number: "03", glyph: "河", title: "黄河的名字", titleTh: "ที่มาของชื่อแม่น้ำหวงเหอ", titleEn: "The name of the Yellow River", place: "家里", placeTh: "ที่บ้าน", ...art("yellow-river"), source: "Text 3 · หน้าเล่ม 137–138 · PDF หน้า 149–150", sourcePage: "137-138", sourceRef: riverRef,
    imageAlt: { zh: "黄河景色", th: "ทิวทัศน์แม่น้ำหวงเหอ", en: "A view of the Yellow River" }, context: "在家里，王一雪和刘小明在聊天儿。", contextTh: "ที่บ้าน หวังอี้เสวี่ยกับหลิวเสี่ยวหมิงคุยกัน", contextEn: "At home, Wang Yixue and Liu Xiaoming were chatting.", characters: [{ role: "A", profile: "wang", noteZh: "给孩子讲黄河的人", noteTh: "ผู้เล่าเรื่องแม่น้ำหวงเหอ", noteEn: "The parent explaining the river" }, { role: "B", profile: "liuXiaoming", noteZh: "回答问题的孩子", noteTh: "เด็กที่ตอบคำถาม", noteEn: "The child answering questions" }],
    lines: [
      line(riverRef, { role: "A", speaker: "王一雪", hanzi: "小明，中国有一条大河，它的名字跟颜色有关系，你知道是什么河吗？", pinyin: "Xiǎomíng, Zhōngguó yǒu yì tiáo dà hé, tā de míngzi gēn yánsè yǒu guānxi, nǐ zhīdào shì shénme hé ma?", en: "Xiaoming, China has a great river whose name is related to a color. Do you know which river it is?", th: "เสี่ยวหมิง จีนมีแม่น้ำใหญ่สายหนึ่ง ชื่อสัมพันธ์กับสี รู้ไหมว่าแม่น้ำอะไร?", visual: visual("名字跟颜色有关系", "ชื่อสัมพันธ์กับสี", "34% center") }),
      line(riverRef, { role: "B", speaker: "刘小明", hanzi: "我知道，是黄河！", pinyin: "Wǒ zhīdào, shì Huáng Hé!", en: "I know—the Yellow River!", th: "ผมรู้ แม่น้ำหวงเหอ!", visual: visual("是黄河", "คือแม่น้ำหวงเหอ", "66% center") }),
      line(riverRef, { role: "A", speaker: "王一雪", hanzi: "你说对了。我再问问你，你知道它为什么叫黄河吗？", pinyin: "Nǐ shuō duì le. Wǒ zài wènwen nǐ, nǐ zhīdào tā wèishénme jiào Huáng Hé ma?", en: "Correct. Let me ask another question: do you know why it is called the Yellow River?", th: "ตอบถูกแล้ว ขอถามอีกข้อ รู้ไหมว่าทำไมจึงเรียกว่าแม่น้ำหวงเหอ?", visual: visual("为什么叫黄河", "ทำไมเรียกว่าหวงเหอ", "36% center") }),
      line(riverRef, { role: "B", speaker: "刘小明", hanzi: "因为河水看起来是黄色的，所以叫这个名字。黄河是中国最长的河吗？", pinyin: "Yīnwèi héshuǐ kàn qǐlai shì huángsè de, suǒyǐ jiào zhège míngzi. Huáng Hé shì Zhōngguó zuì cháng de hé ma?", en: "Because the water looks yellow, it has that name. Is it China's longest river?", th: "เพราะน้ำดูเป็นสีเหลืองจึงได้ชื่อนี้ แม่น้ำหวงเหอเป็นแม่น้ำที่ยาวที่สุดในจีนไหม?", visual: visual("河水看起来是黄色的", "น้ำดูเป็นสีเหลือง", "64% center") }),
      line(riverRef, { role: "A", speaker: "王一雪", hanzi: "不是。黄河虽然不是最长的河，可是在历史上很重要。", pinyin: "Bú shì. Huáng Hé suīrán bú shì zuì cháng de hé, kěshì zài lìshǐ shang hěn zhòngyào.", en: "No. Although it is not the longest river, it is very important in history.", th: "ไม่ใช่ แม้หวงเหอไม่ใช่แม่น้ำที่ยาวที่สุด แต่สำคัญมากในประวัติศาสตร์", visual: visual("在历史上很重要", "สำคัญในประวัติศาสตร์", "38% center") }),
      line(riverRef, { role: "B", speaker: "刘小明", hanzi: "这个我知道。很久以前，很多中国人都住在黄河边上。", pinyin: "Zhège wǒ zhīdào. Hěn jiǔ yǐqián, hěn duō Zhōngguó rén dōu zhù zài Huáng Hé biān shang.", en: "I know that. Long ago, many Chinese people lived along the Yellow River.", th: "ข้อนี้ผมรู้ นานมาแล้วคนจีนจำนวนมากอาศัยอยู่ริมแม่น้ำหวงเหอ", visual: visual("住在黄河边上", "อาศัยริมแม่น้ำหวงเหอ", "62% center") }),
      line(riverRef, { role: "A", speaker: "王一雪", hanzi: "对。在我们中国人看来，黄河像妈妈一样，养了我们几千年。", pinyin: "Duì. Zài wǒmen Zhōngguó rén kànlai, Huáng Hé xiàng māma yíyàng, yǎng le wǒmen jǐ qiān nián.", en: "Right. In the eyes of Chinese people, the Yellow River is like a mother who has nurtured us for thousands of years.", th: "ใช่ ในสายตาคนจีน หวงเหอเหมือนแม่ที่เลี้ยงดูเรามาหลายพันปี", visual: visual("在中国人看来", "ในสายตาคนจีน", "40% center") }),
    ],
    qte: { after: 3, prompt: { zh: "黄河为什么叫这个名字？", th: "ทำไมแม่น้ำหวงเหอจึงได้ชื่อนี้?", en: "Why is the Yellow River called by this name?" }, options: [{ value: "河水看起来是黄色的", zh: "河水看起来是黄色的", pinyin: "héshuǐ kàn qǐlai shì huángsè de", th: "น้ำดูเป็นสีเหลือง" }, { value: "河边有黄花", zh: "河边有黄花", pinyin: "hé biān yǒu huánghuā", th: "ริมแม่น้ำมีดอกไม้สีเหลือง" }, { value: "河很长", zh: "河很长", pinyin: "hé hěn cháng", th: "แม่น้ำยาวมาก" }], correct: "河水看起来是黄色的", evidence: "刘小明：因为河水看起来是黄色的。", evidenceTh: "หลิวเสี่ยวหมิง: เพราะน้ำดูเป็นสีเหลือง", sourceRef: riverRef },
    builder: { prompt: { zh: "重组“在……看来”句", th: "เรียงประโยคแสดงมุมมอง", en: "Rebuild the viewpoint sentence" }, answer: ["在我们中国人看来", "黄河", "像妈妈", "一样"], tiles: ["一样", "黄河", "在我们中国人看来", "像妈妈"], gloss: { 在我们中国人看来: "ในสายตาคนจีน", 黄河: "แม่น้ำหวงเหอ", 像妈妈: "เหมือนแม่", 一样: "เช่นเดียวกัน" }, translationTh: "ในสายตาคนจีน แม่น้ำหวงเหอเหมือนแม่", translationEn: "In the eyes of Chinese people, the Yellow River is like a mother.", evidence: "Text 3 · หน้าเล่ม 138", sourceRef: riverRef },
  },
];
export const LESSON_HSK3_L15 = {
  id: "hsk3-l15", slug: "lesson-15", level: "hsk3", number: 15, featured: false, sourceRef,
  source: { title: "新HSK教程 3 · New HSK Course 3", lesson: "Lesson 15 · 我是半个南京人", printedPages: "133–143", pdfPages: "145–155", file: "hsk3.pdf", sourceRef },
  title: { zh: "我是半个南京人", pinyin: "Wǒ shì bàn ge Nánjīng rén", en: "I am half a Nanjing local", thAid: "ฉันเป็นคนหนานจิงครึ่งหนึ่ง" },
  summary: { zh: "谈社区生活、南京旅行和黄河文化。", en: "Discuss community life, travel in Nanjing, and Yellow River culture.", thAid: "พูดคุยเรื่องชีวิตในชุมชน การเที่ยวหนานจิง และวัฒนธรรมแม่น้ำหวงเหอ" }, translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并描述某地的位置和环境信息。", en: "Be able to understand and describe the location and environment of a place.", thAid: "ฟังเข้าใจและบรรยายข้อมูลด้านที่ตั้งและสภาพแวดล้อมของสถานที่หนึ่ง", sourceRef: lessonHsk3L15SourceRef("133", "145") },
    { zh: "能听懂并介绍某地的自然景观或历史文化。", en: "Be able to understand and introduce the natural scenery, history, or culture of a place.", thAid: "ฟังเข้าใจและแนะนำทิวทัศน์ธรรมชาติหรือประวัติศาสตร์วัฒนธรรมของสถานที่หนึ่ง", sourceRef: lessonHsk3L15SourceRef("133", "145") },
    { zh: "掌握“在……看来”短语，能表达个人或某个群体的观点。", en: "Master the phrase 在……看来 to express personal or group viewpoints.", thAid: "ใช้วลี 在……看来 เพื่อแสดงความคิดเห็นของตนเองหรือกลุ่มหนึ่ง", sourceRef: lessonHsk3L15SourceRef("133", "145") },
    { zh: "了解南京和黄河的基本情况。", en: "Learn about the basic facts of Nanjing and the Yellow River.", thAid: "เรียนรู้ข้อมูลพื้นฐานของเมืองหนานจิงและแม่น้ำหวงเหอ", sourceRef: lessonHsk3L15SourceRef("133", "145") },
  ],
  contents: [{ number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "133", route: "/home/hsk3/lesson-15/preface/", sourceRef: lessonHsk3L15SourceRef("133", "145") }, { number: "01", title: "蓝天小区怎么样", titleTh: "ชุมชนหลานเทียนเป็นอย่างไร", detail: "Text 1 · New Words 1–9", pages: "134–135", scene: 1, sourceRef: lessonHsk3L15SourceRef("134-135", "146-147") }, { number: "02", title: "介绍南京", titleTh: "แนะนำเมืองหนานจิง", detail: "Text 2 · New Words 10–17", pages: "135–136", scene: 2, sourceRef: lessonHsk3L15SourceRef("135-136", "147-148") }, { number: "03", title: "黄河的名字", titleTh: "ที่มาของชื่อแม่น้ำหวงเหอ", detail: "Text 3 · New Words 18–20", pages: "137–139", scene: 3, sourceRef: lessonHsk3L15SourceRef("137-139", "149-151") }, { number: "04", title: "练习与活动", titleTh: "แบบฝึกและกิจกรรม", detail: "Exercises · Activity", pages: "140–143", sourceRef: lessonHsk3L15SourceRef("140-143", "152-155") }], vocabulary,
  grammarFocus: [
    { title: "介词“根据”", titleEn: "Preposition 根据", explanationZh: "在句子中引出事情的依据或理由。", explanationEn: "根据 introduces the basis or reason for an action.", thAid: "ใช้เพื่อบอกหลักอ้างอิงหรือเหตุผลของการกระทำ", examples: ["小区根据他们的需要有了很多变化。", "老师根据学生的兴趣选择了不同的书。"], sourceRef: lessonHsk3L15SourceRef("135", "147") },
    { title: "数量重叠“数词+量词+数词+量词”", titleEn: "Reduplication of numeral-measure phrases", explanationZh: "数量短语重叠后作状语，表示动作的方式并使表达更形象。", explanationEn: "A reduplicated numeral-measure phrase acts as an adverbial describing how an action proceeds.", thAid: "ซ้ำวลีจำนวนเพื่อทำหน้าที่ขยายกริยา บอกลักษณะการกระทำอย่างชัดเจน", examples: ["我得一点儿一点儿给您讲。", "学生们的汉语水平一天一天地提高了。"], sourceRef: lessonHsk3L15SourceRef("136-137", "148-149") },
    { title: "固定短语“在……看来”", titleEn: "Set phrase 在……看来", explanationZh: "表示个人或某个群体的观点。", explanationEn: "在……看来 presents the viewpoint of an individual or group.", thAid: "ใช้แสดงมุมมองของบุคคลหรือกลุ่ม", examples: ["在我们中国人看来，黄河像妈妈一样。", "在我看来，每天读书是一种好习惯。"], sourceRef: lessonHsk3L15SourceRef("138", "150") },
  ], characters, scenes,
};
