import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk1-2.pdf";

export function lessonHsk1L6SourceRef(printedPages, pdfPages) {
  return `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
}

const sourceRef = lessonHsk1L6SourceRef("35-44", "51-60");

const characters = {
  bai: {
    hanzi: "白家月",
    pinyin: "Bái Jiāyuè",
    nameTh: "ไป๋เจียเยว่",
    nameEn: "Bai Jiayue",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp")} 1400w`,
    imageFocus: "50% center",
  },
  chen: {
    hanzi: "陈天中",
    pinyin: "Chén Tiānzhōng",
    nameTh: "เฉินเทียนจง",
    nameEn: "Chen Tianzhong",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-v1.webp")} 1400w`,
    imageFocus: "50% center",
  },
  liWen: {
    hanzi: "李文",
    pinyin: "Lǐ Wén",
    nameTh: "หลี่เหวิน",
    nameEn: "Li Wen",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp")} 1400w`,
    imageFocus: "74% center",
  },
  wang: {
    hanzi: "王一雪",
    pinyin: "Wáng Yīxuě",
    nameTh: "หวังอี้เสวี่ย",
    nameEn: "Wang Yixue",
    image: group3AssetPath("/assets/group3/shared/characters/character-wang-yixue.webp"),
    imageFocus: "50% center",
  },
  liu: {
    hanzi: "刘明",
    pinyin: "Liú Míng",
    nameTh: "หลิวหมิง",
    nameEn: "Liu Ming",
    image: group3AssetPath("/assets/group3/shared/characters/character-liu-ming.webp"),
    imageFocus: "50% center",
  },
  liuXiaoxue: {
    hanzi: "刘小雪",
    pinyin: "Liú Xiǎoxuě",
    nameTh: "หลิวเสี่ยวเสวี่ย",
    nameEn: "Liu Xiaoxue",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp")} 1400w`,
    imageFocus: "50% center",
  },
  liuXiaoming: {
    hanzi: "刘小明",
    pinyin: "Liú Xiǎomíng",
    nameTh: "หลิวเสี่ยวหมิง",
    nameEn: "Liu Xiaoming",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp")} 1400w`,
    imageFocus: "74% center",
  },
};

const vocabularyPages = [
  [1, "手机", "shǒujī", "n.", "cell phone", "โทรศัพท์มือถือ", 36, 52],
  [2, "电话", "diànhuà", "n.", "telephone (set); phone call", "โทรศัพท์ / สายโทร", 36, 52],
  [3, "号", "hào", "n.", "number", "หมายเลข", 36, 52],
  [4, "明天", "míngtiān", "n.", "tomorrow", "พรุ่งนี้", 37, 53],
  [5, "去", "qù", "v.", "go (to)", "ไป", 37, 53],
  [6, "哪儿", "nǎr", "pron.", "where", "ที่ไหน", 37, 53],
  [7, "想", "xiǎng", "mod.", "want to; think", "อยาก / คิดว่า", 37, 53],
  [8, "超市", "chāoshì", "n.", "supermarket", "ซูเปอร์มาร์เก็ต", 37, 53],
  [9, "买", "mǎi", "v.", "buy", "ซื้อ", 37, 53],
  [10, "东西", "dōngxi", "n.", "thing; goods", "ของ / สิ่งของ", 37, 53],
  [11, "些", "xiē", "m.", "some; a few", "บาง / จำนวนหนึ่ง", 37, 53],
  [12, "牛奶", "niúnǎi", "n.", "milk", "นม", 37, 53],
  [13, "吃", "chī", "v.", "eat; have", "กิน / ทาน", 39, 55],
  [14, "晚饭", "wǎnfàn", "n.", "dinner; supper", "อาหารเย็น", 39, 55],
  [15, "那边", "nàbiān", "pron.", "there", "ฝั่งนั้น / ที่นั่น", 39, 55],
  [16, "包子", "bāozi", "n.", "steamed stuffed bun", "ซาลาเปา", 39, 55],
  [17, "非常", "fēicháng", "adv.", "very; extremely", "มาก / ยิ่ง", 39, 55],
  [18, "好吃", "hǎochī", "adj.", "tasty; delicious", "อร่อย", 39, 55],
  [19, "米饭", "mǐfàn", "n.", "(cooked) rice", "ข้าวสวย", 39, 55],
  [20, "怎么", "zěnme", "pron.", "how", "อย่างไร", 39, 55],
  [21, "坐", "zuò", "v.", "take; travel by or on", "นั่ง / โดยสาร", 39, 55],
  [22, "出租车", "chūzūchē", "n.", "taxi", "แท็กซี่", 39, 55],
];

const vocabulary = vocabularyPages.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({
  index,
  hanzi,
  pinyin,
  type,
  en,
  th: thAid,
  thAid,
  page,
  translationKind: "editorial-aid",
  sourceRef: lessonHsk1L6SourceRef(String(page), String(pdfPage)),
}));

function line(source, value) {
  return { ...value, sourceRef: source };
}

const numberRef = lessonHsk1L6SourceRef("36", "52");
const supermarketRef = lessonHsk1L6SourceRef("37", "53");
const familyRef = lessonHsk1L6SourceRef("39", "55");

const scenes = [
  {
    id: "h1l6-number",
    number: "01",
    glyph: "号",
    title: "在校园里要手机号",
    titleTh: "ขอเบอร์โทรศัพท์ในมหาวิทยาลัย",
    titleEn: "Asking for a phone number on campus",
    place: "校园",
    placePy: "xiàoyuán",
    placeTh: "ในมหาวิทยาลัย",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-number-v1.webp")} 1400w`,
    imageAlt: {
      th: "หลี่เหวินและไป๋เจียเยว่แลกเบอร์โทรศัพท์กันในมหาวิทยาลัย",
      zh: "李文和白家月在校园里交换手机号码",
      en: "Li Wen and Bai Jiayue exchange phone numbers on campus",
    },
    source: "Text 1 · หน้าเล่ม 36 · PDF หน้า 52",
    sourcePage: "36",
    sourceRef: numberRef,
    context: "在校园里，李文向白家月要手机号。",
    contextTh: "ในมหาวิทยาลัย หลี่เหวินขอเบอร์โทรศัพท์จากไป๋เจียเยว่",
    contextEn: "On campus, Li Wen was asking Bai Jiayue for her cell phone number.",
    characters: [
      { role: "A", profile: "liWen", noteTh: "เพื่อนที่ขอเบอร์โทรศัพท์", noteZh: "要手机号的同学", noteEn: "The classmate asking for the phone number" },
      { role: "B", profile: "bai", noteTh: "เพื่อนที่ให้เบอร์โทรศัพท์", noteZh: "告诉电话号码的同学", noteEn: "The classmate sharing her phone number" },
    ],
    lines: [
      line(numberRef, { role: "A", speaker: "李文", pinyin: "jiāyuè, nǐ de shǒujīhào shì duōshao", hanzi: "家月，你的手机号是多少？", reading: "Jiāyuè, nǐ de shǒujīhào shì duōshao?", en: "Jiayue, what's your cell phone number?", th: "เจียเยว่ เบอร์โทรศัพท์ของคุณคืออะไร?", visual: { zh: "手机号是多少", th: "เบอร์โทรคืออะไร", focus: "26% center" } }),
      line(numberRef, { role: "B", speaker: "白家月", pinyin: "wǒ de shǒujīhào shì sān sān liù líng yāo sì jiǔ sān yāo jiǔ líng", hanzi: "我的手机号是33601493190。", reading: "Wǒ de shǒujīhào shì 33601493190.", en: "My cell phone number is 33601493190.", th: "เบอร์โทรของฉันคือ 33601493190", visual: { zh: "33601493190", th: "เบอร์ของฉัน", focus: "74% center" } }),
      line(numberRef, { role: "A", speaker: "李文", pinyin: "wǒ de shǒujīhào shì bā liù yāo sān wǔ wǔ èr qī èr yāo yāo liù líng", hanzi: "我的手机号是8613552721160。", reading: "Wǒ de shǒujīhào shì 8613552721160.", en: "My cell phone number is 8613552721160.", th: "เบอร์โทรของผมคือ 8613552721160", visual: { zh: "8613552721160", th: "เบอร์ของฉัน", focus: "26% center" } }),
      line(numberRef, { role: "B", speaker: "白家月", pinyin: "hǎo de", hanzi: "好的。", reading: "Hǎo de.", en: "Alright.", th: "ได้เลย", visual: { zh: "好的", th: "ได้เลย", focus: "74% center" } }),
    ],
    qte: {
      after: 2,
      prompt: { th: "白家月的手机号是什么?", zh: "白家月的手机号是多少？", en: "What is Bai Jiayue's phone number?" },
      options: [
        { value: "33601493190", zh: "33601493190", pinyin: "Sān sān liù líng yāo sì jiǔ sān yāo jiǔ líng", th: "33601493190" },
        { value: "8613552721160", zh: "8613552721160", pinyin: "Bā liù yāo sān wǔ wǔ èr qī èr yāo yāo liù líng", th: "8613552721160" },
        { value: "33601593190", zh: "33601593190", pinyin: "Sān sān liù líng yāo wǔ jiǔ sān yāo jiǔ líng", th: "33601593190" },
      ],
      correct: "33601493190",
      evidence: "白家月：我的手机号是33601493190。",
      evidenceTh: "ไป๋เจียเยว่: เบอร์โทรของฉันคือ 33601493190",
      sourceRef: numberRef,
    },
    builder: {
      prompt: { th: "เรียงคำถาม “เบอร์โทรศัพท์ของคุณคืออะไร”", zh: "重组“你的手机号是多少”", en: "Rebuild “What's your cell phone number”" },
      answer: ["你的", "手机号", "是", "多少？"],
      tiles: ["手机号", "是", "多少？", "你的"],
      gloss: { 你的: "ของคุณ", 手机号: "เบอร์โทรศัพท์", 是: "คือ", 多少: "เท่าไร" },
      translationTh: "เบอร์โทรศัพท์ของคุณคืออะไร?",
      translationEn: "What's your cell phone number?",
      evidence: "Text 1 · หน้าเล่ม 36",
      sourceRef: numberRef,
    },
  },
  {
    id: "h1l6-supermarket",
    number: "02",
    glyph: "想",
    title: "在教室里聊明天的计划",
    titleTh: "คุยแผนวันพรุ่งนี้ในห้องเรียน",
    titleEn: "Talking about tomorrow's plan in class",
    place: "教室",
    placePy: "jiàoshì",
    placeTh: "ห้องเรียน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-supermarket-v1.webp")} 1400w`,
    imageAlt: {
      th: "ไป๋เจียเยว่บอกเฉินเทียนจงว่าจะไปซูเปอร์มาร์เก็ตซื้อนม",
      zh: "白家月告诉陈天中她要去超市买牛奶",
      en: "Bai Jiayue tells Chen Tianzhong she plans to buy milk at the supermarket",
    },
    source: "Text 2 · หน้าเล่ม 37 · PDF หน้า 53",
    sourcePage: "37",
    sourceRef: supermarketRef,
    context: "在教室里，下课后，白家月和陈天中在聊天儿。",
    contextTh: "ในห้องเรียน หลังเลิกเรียน ไป๋เจียเยว่และเฉินเทียนจงคุยกัน",
    contextEn: "After class, Bai Jiayue and Chen Tianzhong were chatting in the classroom.",
    characters: [
      { role: "A", profile: "chen", noteTh: "เพื่อนที่ถามแผนพรุ่งนี้", noteZh: "询问明天计划的同学", noteEn: "The classmate asking about tomorrow's plan" },
      { role: "B", profile: "bai", noteTh: "เพื่อนที่บอกว่าจะไปซูเปอร์มาร์เก็ต", noteZh: "说自己要去超市的同学", noteEn: "The classmate who wants to go to the supermarket" },
    ],
    lines: [
      line(supermarketRef, { role: "A", speaker: "陈天中", pinyin: "jiāyuè, míngtiān nǐ qù nǎr", hanzi: "家月，明天你去哪儿？", reading: "Jiāyuè, míngtiān nǐ qù nǎr?", en: "Jiayue, where are you going tomorrow?", th: "เจียเยว่ พรุ่งนี้คุณจะไปที่ไหน?", visual: { zh: "去哪儿", th: "ไปที่ไหน", focus: "26% center" } }),
      line(supermarketRef, { role: "B", speaker: "白家月", pinyin: "wǒ xiǎng qù chāoshì mǎi dōngxi", hanzi: "我想去超市买东西。", reading: "Wǒ xiǎng qù chāoshì mǎi dōngxi.", en: "I want to go to the supermarket to buy groceries.", th: "ฉันอยากไปซูเปอร์มาร์เก็ตซื้อของ", visual: { zh: "去超市买东西", th: "ไปซุปเปอร์ฯ ซื้อของ", focus: "74% center" } }),
      line(supermarketRef, { role: "A", speaker: "陈天中", pinyin: "nǐ qù chāoshì mǎi shénme", hanzi: "你去超市买什么？", reading: "Nǐ qù chāoshì mǎi shénme?", en: "What are you going to buy at the supermarket?", th: "คุณจะไปซื้ออะไรที่ซูเปอร์มาร์เก็ต?", visual: { zh: "买什么", th: "ซื้ออะไร", focus: "26% center" } }),
      line(supermarketRef, { role: "B", speaker: "白家月", pinyin: "wǒ xiǎng mǎi xiē niúnǎi", hanzi: "我想买些牛奶。", reading: "Wǒ xiǎng mǎi xiē niúnǎi.", en: "I want to buy some milk.", th: "ฉันอยากซื้อนมสักหน่อย", visual: { zh: "买些牛奶", th: "ซื้อนม", focus: "74% center" } }),
    ],
    qte: {
      after: 4,
      prompt: { th: "白家月想买什么?", zh: "白家月想买什么？", en: "What does Bai Jiayue want to buy?" },
      options: [
        { value: "牛奶", zh: "牛奶", pinyin: "Niúnǎi", th: "นม" },
        { value: "菜", zh: "菜", pinyin: "Cài", th: "ผัก" },
        { value: "面条儿和牛奶", zh: "面条儿和牛奶", pinyin: "Miàntiáor hé niúnǎi", th: "เส้นกับนม" },
      ],
      correct: "牛奶",
      evidence: "白家月：我想买些牛奶。",
      evidenceTh: "ไป๋เจียเยว่: ฉันอยากซื้อนมสักหน่อย",
      sourceRef: supermarketRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “ฉันอยากไปซูเปอร์มาร์เก็ตซื้อของ”", zh: "重组“我想去超市买东西”", en: "Rebuild “I want to go to the supermarket to buy groceries”" },
      answer: ["我", "想", "去超市", "买东西。"],
      tiles: ["去超市", "买东西。", "想", "我"],
      gloss: { 我: "ฉัน", 想: "อยาก", 去超市: "ไปซูเปอร์มาร์เก็ต", 买东西: "ซื้อของ" },
      translationTh: "ฉันอยากไปซูเปอร์มาร์เก็ตซื้อของ",
      translationEn: "I want to go to the supermarket to buy groceries.",
      evidence: "Text 2 · หน้าเล่ม 37",
      sourceRef: supermarketRef,
    },
  },
  {
    id: "h1l6-family",
    number: "03",
    glyph: "吃",
    title: "星期天全家人去哪儿吃饭",
    titleTh: "วันอาทิตย์ทั้งครอบครัวจะไปกินข้าวที่ไหน",
    titleEn: "Where the family eats on Sunday",
    place: "家里",
    placeTh: "ที่บ้าน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l6-family-v1.webp")} 1400w`,
    imageAlt: {
      th: "ครอบครัวหวังอี้เสวี่ยเลือกว่าจะกินซาลาเปาหรือข้าวในวันอาทิตย์",
      zh: "王一雪一家商量星期天吃包子还是米饭",
      en: "Wang Yixue's family chooses between steamed buns and rice for Sunday dinner",
    },
    source: "Text 3 · หน้าเล่ม 39 · PDF หน้า 55",
    sourcePage: "39",
    sourceRef: familyRef,
    context: "在微信群里，王一雪一家商量星期天去哪儿吃晚饭。",
    contextTh: "ในกลุ่มแชต ครอบครัวหวังอี้เสวี่ยปรึกษากันว่าวันอาทิตย์จะไปกินข้าวเย็นที่ไหน",
    contextEn: "In the family chat, Wang Yixue's family discussed where to eat on Sunday.",
    characters: [
      { role: "A", profile: "wang", noteTh: "แม่ที่ถามแผนวันอาทิตย์", noteZh: "询问星期天计划的妈妈", noteEn: "The mother asking about Sunday's plan" },
      { role: "B", profile: "liu", noteTh: "พ่อที่อยากไปร้านอาหารซีอาน", noteZh: "想去西安饭店的爸爸", noteEn: "The father who wants to go to Xi'an Restaurant" },
      { role: "C", profile: "liuXiaoxue", noteTh: "ลูกสาวที่อยากกินซาลาเปา", noteZh: "想吃包子的女儿", noteEn: "The daughter who wants to eat steamed buns" },
      { role: "D", profile: "liuXiaoming", noteTh: "ลูกชายที่อยากกินข้าว", noteZh: "想吃米饭的儿子", noteEn: "The son who wants to eat rice" },
    ],
    lines: [
      line(familyRef, { role: "A", speaker: "王一雪", pinyin: "xīngqītiān wǒmen qù nǎr chī wǎnfàn", hanzi: "星期天我们去哪儿吃晚饭？", reading: "Xīngqītiān wǒmen qù nǎr chī wǎnfàn?", en: "Where are we going for dinner on Sunday?", th: "วันอาทิตย์พวกเราไปกินข้าวเย็นที่ไหน?", visual: { zh: "去哪儿吃晚饭", th: "ไปกินข้าวเย็นที่ไหน", focus: "26% center" } }),
      line(familyRef, { role: "B", speaker: "刘明", pinyin: "wǒ hái xiǎng qù xī'ān fàndiàn", hanzi: "我还想去西安饭店。", reading: "Wǒ hái xiǎng qù Xī'ān Fàndiàn.", en: "I'd like to go to Xi'an Restaurant again.", th: "ผมยังอยากไปร้านอาหารซีอานอีก", visual: { zh: "西安饭店", th: "ร้านอาหารซีอาน", focus: "74% center" } }),
      line(familyRef, { role: "C", speaker: "刘小雪", pinyin: "nàbiān de bāozi fēicháng hǎochī, wǒ xiǎng chī bāozi", hanzi: "那边的包子非常好吃，我想吃包子。", reading: "Nàbiān de bāozi fēicháng hǎochī, wǒ xiǎng chī bāozi.", en: "The steamed buns there are very delicious. I'd love to eat some.", th: "ซาลาเปาที่นั่นอร่อยมาก หนูอยากกินซาลาเปา", visual: { zh: "非常好吃", th: "อร่อยมาก", focus: "26% center" } }),
      line(familyRef, { role: "D", speaker: "刘小明", pinyin: "māma, wǒ xiǎng chī mǐfàn, bù xiǎng chī bāozi", hanzi: "妈妈，我想吃米饭，不想吃包子。", reading: "Māma, wǒ xiǎng chī mǐfàn, bù xiǎng chī bāozi.", en: "Mom, I'd rather have rice — not steamed buns.", th: "แม่ครับ ผมอยากกินข้าว ไม่กินซาลาเปา", visual: { zh: "想吃米饭", th: "อยากกินข้าว", focus: "74% center" } }),
      line(familyRef, { role: "A", speaker: "王一雪", pinyin: "hǎo de. wǒmen zěnme qù", hanzi: "好的。我们怎么去？", reading: "Hǎo de. Wǒmen zěnme qù?", en: "Alright. How shall we get there?", th: "ได้สิ แล้วพวกเราไปกันอย่างไร?", visual: { zh: "怎么去", th: "ไปอย่างไร", focus: "26% center" } }),
      line(familyRef, { role: "B", speaker: "刘明", pinyin: "zuò chūzūchē qù", hanzi: "坐出租车去。", reading: "Zuò chūzūchē qù.", en: "Let's take a taxi.", th: "นั่งแท็กซี่ไป", visual: { zh: "坐出租车", th: "นั่งแท็กซี่", focus: "74% center" } }),
    ],
    qte: {
      after: 6,
      prompt: { th: "พวกเขาจะไปร้านอาหารซีอานกันอย่างไร?", zh: "他们怎么去西安饭店？", en: "How will they go to Xi'an Restaurant?" },
      options: [
        { value: "坐出租车", zh: "坐出租车", pinyin: "Zuò chūzūchē", th: "นั่งแท็กซี่" },
        { value: "走路", zh: "走路", pinyin: "Zǒulù", th: "เดิน" },
        { value: "坐公共汽车", zh: "坐公共汽车", pinyin: "Zuò gōnggòngqìchē", th: "นั่งรถเมล์" },
      ],
      correct: "坐出租车",
      evidence: "刘明：坐出租车去。",
      evidenceTh: "หลิวหมิง: นั่งแท็กซี่ไป",
      sourceRef: familyRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “เราจะไปกันอย่างไร”", zh: "重组“我们怎么去”", en: "Rebuild “How shall we get there”" },
      answer: ["我们", "怎么", "去？"],
      tiles: ["怎么", "去？", "我们"],
      gloss: { 我们: "พวกเรา", 怎么: "อย่างไร", 去: "ไป" },
      translationTh: "พวกเราจะไปกันอย่างไร?",
      translationEn: "How shall we get there?",
      evidence: "Text 3 · หน้าเล่ม 39",
      sourceRef: familyRef,
    },
  },
];

export const LESSON_HSK1_L6 = {
  id: "hsk1-l6",
  slug: "lesson-6",
  level: "hsk1",
  number: 6,
  featured: false,
  source: {
    title: "新HSK教程 1 · New HSK Course 1",
    lesson: "Lesson 6 · 你的手机号是多少",
    printedPages: "35–44",
    pdfPages: "51–60",
    file: "hsk1-2.pdf",
    sourceRef,
  },
  sourceRef,
  title: {
    zh: "你的手机号是多少",
    pinyin: "Nǐ de shǒujīhào shì duōshao",
    en: "What's your cell phone number?",
    thAid: "เบอร์โทรศัพท์ของคุณคืออะไร",
  },
  summary: {
    zh: "从校园到家里，学会读手机号码，用“想”表达意愿，用连动句表达动作的目的或方式，用“怎么”询问方式。",
    en: "From campus to home, learn to read cell phone numbers digit by digit, to express intention with 想, to state the purpose or manner of an action with serial verb sentences, and to ask about manner with 怎么.",
    thAid: "ตั้งแต่ในมหาวิทยาลัยถึงที่บ้าน ฝึกอ่านเบอร์โทรศัพท์ ใช้ 想 บอกความต้องการ ใช้ประโยคกริยาเรียงสอง ใช้ 怎么 ถามวิธี",
  },
  translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂手机号码并使用号码拨打手机。", en: "Be able to understand cell phone numbers and use them to make calls.", thAid: "ฟังเบอร์โทรศัพท์แล้วกดโทรออกได้", sourceRef: lessonHsk1L6SourceRef("35", "51") },
    { zh: "能听懂并使用两个或多个动词性短语表达动作的目的或方式。", en: "Be able to understand and use two or more verbal phrases to express the purpose or manner of an action.", thAid: "เข้าใจและใช้กริยาวลีสองตัวขึ้นไปบอกจุดประสงค์หรือวิธีของเหตุการณ์", sourceRef: lessonHsk1L6SourceRef("35", "51") },
    { zh: "掌握能愿动词“想”的用法。", en: "Master the use of the modal verb 想.", thAid: "ใช้คำกริยาช่วย 想 (อยาก) ได้ถูกต้อง", sourceRef: lessonHsk1L6SourceRef("35", "51") },
    { zh: "掌握疑问代词“怎么”询问方式的用法。", en: "Master the use of the interrogative pronoun 怎么 to ask about manner.", thAid: "ใช้ 怎么 ถามถึงวิธีการได้ถูกต้อง", sourceRef: lessonHsk1L6SourceRef("35", "51") },
  ],
  contents: [
    { number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "35", route: "/home/hsk1/lesson-6/preface/", sourceRef: lessonHsk1L6SourceRef("35", "51") },
    { number: "01", title: "在校园里要手机号", titleTh: "ขอเบอร์โทรศัพท์ในมหาวิทยาลัย", detail: "Text 1 · New Words 1–3", pages: "36", scene: 1, sourceRef: lessonHsk1L6SourceRef("36", "52") },
    { number: "02", title: "在教室里聊明天的计划", titleTh: "คุยแผนวันพรุ่งนี้ในห้องเรียน", detail: "Text 2 · New Words 4–12", pages: "37", scene: 2, sourceRef: lessonHsk1L6SourceRef("37", "53") },
    { number: "03", title: "星期天全家人去哪儿吃饭", titleTh: "วันอาทิตย์ทั้งครอบครัวจะไปกินข้าวที่ไหน", detail: "Text 3 · New Words 13–22", pages: "39", scene: 3, sourceRef: lessonHsk1L6SourceRef("39", "55") },
    { number: "04", title: "综合练习与活动", titleTh: "แบบฝึกรวมและกิจกรรม", detail: "Comprehensive Exercises (source trail)", pages: "40–44", sourceRef: lessonHsk1L6SourceRef("40-44", "56-60") },
  ],
  vocabulary,
  grammarFocus: [
    { title: "连动句（1）", titleEn: "Serial Verb Sentences (1)", explanationZh: "连动句的谓语由两个或两个以上动词性短语构成，可以表示动作的目的，也可以表示动作的方式。例如：我想去超市买东西。", explanationEn: "A serial verb sentence consists of two or more verbal phrases in the predicate, expressing the purpose or the manner of an action. For example: 我想去超市买东西。", thAid: "ประโยคกริยาเรียงสอง เช่น 我想去超市买东西 (ฉันอยากไปซูเปอร์มาร์เก็ตซื้อของ) ใช้บอกจุดประสงค์หรือวิธี", examples: ["我想去超市买东西。", "我们去西安饭店吃晚饭。", "我们坐出租车去西安饭店。"], sourceRef: lessonHsk1L6SourceRef("40", "56") },
    { title: "疑问代词“怎么”", titleEn: "The Interrogative Pronoun 怎么", explanationZh: "疑问代词“怎么”用在动词前，询问动作的方式或方法。例如：我们怎么去？", explanationEn: "The interrogative pronoun 怎么 is used before a verb to ask about the manner or method of an action. For example: 我们怎么去？", thAid: "怎么 วางหน้า verb ใช้ถามวิธี เช่น 我们怎么去 (เราไปกันอย่างไร)", examples: ["我们怎么去？", "她怎么去超市？", "你们怎么去西安饭店？"], sourceRef: lessonHsk1L6SourceRef("41", "57") },
    { title: "能愿动词“想”", titleEn: "The Modal Verb 想", explanationZh: "“想”表示想做、打算做某事，结构：主语+想+动词短语。例如：我想去超市买东西。", explanationEn: "想 expresses the desire or intention to do something: Subject + 想 + Verb phrase. For example: 我想去超市买东西。", thAid: "想 บอกความอยาก/ตั้งใจทำ: ประธาน+想+กริยาวลี เช่น 我想去超市 (ฉันอยากไปซูเปอร์มาร์เก็ต)", examples: ["我想买些牛奶。", "我想吃包子。", "我不想吃包子。"], sourceRef: lessonHsk1L6SourceRef("37", "53") },
  ],
  characters,
  scenes,
};
