import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk1-2.pdf";

export function lessonHsk1L15SourceRef(printedPages, pdfPages) {
  return `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
}

const sourceRef = lessonHsk1L15SourceRef("112-119", "128-135");
const mealRef = lessonHsk1L15SourceRef("113", "129");
const travelRef = lessonHsk1L15SourceRef("114-115", "130-131");
const airportRef = lessonHsk1L15SourceRef("116-117", "132-133");

const characters = {
  liWen: {
    hanzi: "李文",
    pinyin: "Lǐ Wén",
    nameTh: "หลี่เหวิน",
    nameEn: "Li Wen",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp")} 1400w`,
    imageFocus: "24% center",
  },
  bai: {
    hanzi: "白家月",
    pinyin: "Bái Jiāyuè",
    nameTh: "ไป๋เจียเยว่",
    nameEn: "Bai Jiayue",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp")} 1400w`,
    imageFocus: "72% center",
  },
  chen: {
    hanzi: "陈天中",
    pinyin: "Chén Tiānzhōng",
    nameTh: "เฉินเทียนจง",
    nameEn: "Chen Tianzhong",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp")} 1400w`,
    imageFocus: "72% center",
  },
  annie: {
    hanzi: "安妮",
    pinyin: "Ānnī",
    nameTh: "แอนนี่",
    nameEn: "Annie",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp")} 1400w`,
    imageFocus: "27% center",
  },
  teacherWang: {
    hanzi: "王一飞",
    pinyin: "Wáng Yīfēi",
    nameTh: "อาจารย์หวังอี้เฟย",
    nameEn: "Teacher Wang Yifei",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-v1.webp")} 1400w`,
    imageFocus: "72% center",
  },
};

const vocabularyPages = [
  [1, "爱", "ài", "v.", "like; be fond of", "ชอบ / รัก", 113, 129],
  [2, "哪个", "nǎge", "pron.", "which", "อันไหน", 113, 129],
  [3, "去年", "qùnián", "n.", "last year", "ปีที่แล้ว", 115, 131],
  [4, "男朋友", "nánpéngyou", "n.", "boyfriend", "แฟนผู้ชาย", 115, 131],
  [5, "几", "jǐ", "num.", "a few; several", "กี่ / หลาย", 115, 131],
  [6, "年", "nián", "n.", "year", "ปี", 115, 131],
  [7, "好玩儿", "hǎowánr", "adj.", "fun; interesting", "สนุก / น่าสนใจ", 115, 131],
  [8, "飞机", "fēijī", "n.", "plane", "เครื่องบิน", 117, 133],
  [9, "要", "yào", "v.", "need; take", "ต้องใช้ / กินเวลา", 117, 133],
  [10, "小时", "xiǎoshí", "n.", "hour", "ชั่วโมง", 117, 133],
  [11, "家人", "jiārén", "n.", "family member", "คนในครอบครัว", 117, 133],
  [12, "时间", "shíjiān", "n.", "time; duration", "เวลา / ระยะเวลา", 117, 133],
  [13, "机场", "jīchǎng", "n.", "airport", "สนามบิน", 117, 133],
  [14, "接", "jiē", "v.", "meet; welcome", "ไปรับ / ต้อนรับ", 117, 133],
  [15, "住", "zhù", "v.", "live; stay", "อาศัย / พัก", 117, 133],
  [16, "早", "zǎo", "adj.", "early", "เช้า / เร็ว", 117, 133],
  [17, "那", "nà", "conj.", "then", "ถ้าอย่างนั้น", 117, 133],
  [18, "西安", "Xī'ān", "proper n.", "Xi'an", "ซีอาน", 115, 131],
  [19, "北京", "Běijīng", "proper n.", "Beijing", "ปักกิ่ง", 115, 131],
  [20, "大兴机场", "Dàxīng Jīchǎng", "proper n.", "Daxing Airport", "สนามบินต้าซิง", 117, 133],
];

const vocabulary = vocabularyPages.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({
  index,
  hanzi,
  pinyin,
  type,
  en,
  th: thAid,
  thAid,
  page,
  translationKind: "editorial-aid",
  sourceRef: lessonHsk1L15SourceRef(String(page), String(pdfPage)),
}));

function line(source, value) {
  return { ...value, sourceRef: source };
}

const scenes = [
  {
    id: "h1l15-meal",
    number: "01",
    glyph: "爱",
    title: "在李文家品尝中国菜",
    titleTh: "ชิมอาหารจีนที่บ้านหลี่เหวิน",
    titleEn: "Tasting Chinese food at Li Wen's home",
    place: "李文家",
    placeTh: "บ้านหลี่เหวิน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-meal-v1.webp")} 1400w`,
    imageAlt: { th: "หลี่เหวินต้อนรับไป๋เจียเยว่และเฉินเทียนจงด้วยอาหารจีนหลายจาน", zh: "李文用多道中国菜招待白家月和陈天中", en: "Li Wen serves Bai Jiayue and Chen Tianzhong a table of Chinese dishes" },
    source: "Text 1 · หน้าเล่ม 113 · PDF หน้า 129",
    sourcePage: "113",
    sourceRef: mealRef,
    context: "在李文家，李文邀请陈天中、白家月等朋友品尝中餐。",
    contextTh: "ที่บ้านหลี่เหวิน เขาเชิญเฉินเทียนจง ไป๋เจียเยว่ และเพื่อน ๆ มาชิมอาหารจีน",
    contextEn: "At Li Wen's home, he invited Chen Tianzhong, Bai Jiayue, and other friends to taste Chinese food.",
    characters: [
      { role: "A", profile: "liWen", noteTh: "เจ้าบ้านผู้ทำอาหารและชวนแขกกิน", noteZh: "做饭并劝客人多吃的主人", noteEn: "The host who cooked and invites everyone to eat" },
      { role: "B", profile: "bai", noteTh: "แขกผู้ชอบอาหารสองจาน", noteZh: "喜欢两个菜的客人", noteEn: "The guest who likes two dishes" },
      { role: "C", profile: "chen", noteTh: "แขกผู้ชมว่าอาหารอร่อยและสวย", noteZh: "称赞菜好吃好看的客人", noteEn: "The guest praising the dishes" },
    ],
    lines: [
      line(mealRef, { role: "A", speaker: "李文", pinyin: "nǐmen ài chī nǎge cài", hanzi: "你们爱吃哪个菜？", reading: "Nǐmen ài chī nǎge cài?", en: "Which dish do you like?", th: "พวกเธอชอบกินจานไหน?", visual: { zh: "爱吃哪个菜", th: "ชอบกินจานไหน", focus: "24% center" } }),
      line(mealRef, { role: "B", speaker: "白家月", pinyin: "wǒ xǐhuan zhège, yě xǐhuan nàge", hanzi: "我喜欢这个，也喜欢那个。", reading: "Wǒ xǐhuan zhège, yě xǐhuan nàge.", en: "I like this one, and I also like that one.", th: "ฉันชอบจานนี้ และก็ชอบจานนั้นด้วย", visual: { zh: "也喜欢那个", th: "ก็ชอบจานนั้นด้วย", focus: "72% center" } }),
      line(mealRef, { role: "C", speaker: "陈天中", pinyin: "zhèxiē cài dōu hǎochī, hái hěn hǎokàn", hanzi: "这些菜都好吃，还很好看。", reading: "Zhèxiē cài dōu hǎochī, hái hěn hǎokàn.", en: "All these dishes are delicious, and they look great too.", th: "อาหารเหล่านี้อร่อยทุกจาน แถมยังดูสวยมาก", visual: { zh: "都好吃，还很好看", th: "อร่อยทุกจานและดูสวย", focus: "72% center" } }),
      line(mealRef, { role: "A", speaker: "李文", pinyin: "wǒ ài chī zhōngguó cài, yě xǐhuan zuò. dàjiā duō chī diǎnr", hanzi: "我爱吃中国菜，也喜欢做。大家多吃点儿。", reading: "Wǒ ài chī Zhōngguó cài, yě xǐhuan zuò. Dàjiā duō chī diǎnr.", en: "I like eating Chinese food, and I also like cooking it. Everyone, eat more.", th: "ฉันชอบกินอาหารจีน และก็ชอบทำด้วย ทุกคนกินเยอะ ๆ นะ", visual: { zh: "大家多吃点儿", th: "ทุกคนกินเยอะ ๆ", focus: "24% center" } }),
    ],
    qte: {
      after: 4,
      prompt: { th: "เฉินเทียนจงชมอาหารว่าอย่างไร?", zh: "陈天中觉得这些菜怎么样？", en: "What does Chen Tianzhong think of the dishes?" },
      options: [
        { value: "好吃又好看", zh: "好吃又好看", pinyin: "Hǎochī yòu hǎokàn", th: "อร่อยและดูสวย" },
        { value: "不好吃", zh: "不好吃", pinyin: "Bù hǎochī", th: "ไม่อร่อย" },
        { value: "太少", zh: "太少", pinyin: "Tài shǎo", th: "น้อยเกินไป" },
      ],
      correct: "好吃又好看",
      evidence: "陈天中：这些菜都好吃，还很好看。",
      evidenceTh: "เฉินเทียนจง: อาหารเหล่านี้อร่อยทุกจาน แถมยังดูสวยมาก",
      sourceRef: mealRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “ฉันชอบจานนี้ และก็ชอบจานนั้นด้วย”", zh: "重组“我喜欢这个，也喜欢那个”", en: "Rebuild “I like this one, and also that one”" },
      answer: ["我", "喜欢这个，", "也", "喜欢那个。"],
      tiles: ["喜欢那个。", "我", "也", "喜欢这个，"],
      gloss: { 我: "ฉัน", 喜欢这个: "ชอบอันนี้", 也: "ก็...ด้วย", 喜欢那个: "ชอบอันนั้น" },
      translationTh: "ฉันชอบจานนี้ และก็ชอบจานนั้นด้วย",
      translationEn: "I like this one, and I also like that one.",
      evidence: "Text 1 · หน้าเล่ม 113",
      sourceRef: mealRef,
    },
  },
  {
    id: "h1l15-travel",
    number: "02",
    glyph: "京",
    title: "边吃饭边谈假期计划",
    titleTh: "คุยแผนวันหยุดระหว่างกินข้าว",
    titleEn: "Discussing holiday plans over a meal",
    place: "李文家",
    placeTh: "บ้านหลี่เหวิน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-travel-v1.webp")} 1400w`,
    imageAlt: { th: "หลี่เหวิน ไป๋เจียเยว่ และอันนี่คุยแผนเที่ยวปักกิ่งระหว่างกินข้าว", zh: "李文、白家月和安妮边吃饭边讨论北京旅行计划", en: "Li Wen, Bai Jiayue, and Annie discuss a Beijing trip over dinner" },
    source: "Text 2 · หน้าเล่ม 114–115 · PDF หน้า 130–131",
    sourcePage: "115",
    sourceRef: travelRef,
    context: "在李文家，大家边吃饭边谈论假期计划。",
    contextTh: "ที่บ้านหลี่เหวิน ทุกคนคุยเรื่องแผนวันหยุดระหว่างกินข้าว",
    contextEn: "At Li Wen's home, everyone discussed holiday plans while eating.",
    characters: [
      { role: "A", profile: "liWen", noteTh: "เจ้าบ้านผู้ถามแผนการเดินทาง", noteZh: "询问旅行计划的主人", noteEn: "The host asking about travel plans" },
      { role: "B", profile: "annie", noteTh: "ผู้เคยไปซีอานและอยากไปปักกิ่ง", noteZh: "去过西安并想去北京的人", noteEn: "The traveler who went to Xi'an and wants to visit Beijing" },
      { role: "C", profile: "bai", noteTh: "ผู้เคยไปซีอานเมื่อหลายปีก่อน", noteZh: "前几年去过西安的人", noteEn: "The traveler who visited Xi'an several years ago" },
    ],
    lines: [
      line(travelRef, { role: "A", speaker: "李文", pinyin: "nǐmen dōu xiǎng qù nǎr", hanzi: "你们都想去哪儿？", reading: "Nǐmen dōu xiǎng qù nǎr?", en: "Where do you all want to go?", th: "พวกเธอทุกคนอยากไปที่ไหน?", visual: { zh: "想去哪儿", th: "อยากไปที่ไหน", focus: "24% center" } }),
      line(travelRef, { role: "B", speaker: "安妮", pinyin: "qùnián wǒ hé nánpéngyou qùle xī'ān, jīnnián wǒ xiǎng qù běijīng", hanzi: "去年我和男朋友去了西安，今年我想去北京。", reading: "Qùnián wǒ hé nánpéngyou qùle Xī'ān, jīnnián wǒ xiǎng qù Běijīng.", en: "My boyfriend and I went to Xi'an last year. This year I want to go to Beijing.", th: "ปีที่แล้วฉันกับแฟนไปซีอาน ปีนี้ฉันอยากไปปักกิ่ง", visual: { zh: "今年我想去北京", th: "ปีนี้อยากไปปักกิ่ง", focus: "27% center" } }),
      line(travelRef, { role: "C", speaker: "白家月", pinyin: "qián jǐ nián wǒ qùle xī'ān, fēicháng hǎowánr. jīnnián wǒ yě xiǎng qù běijīng", hanzi: "前几年我去了西安，非常好玩儿。今年我也想去北京。", reading: "Qián jǐ nián wǒ qùle Xī'ān, fēicháng hǎowánr. Jīnnián wǒ yě xiǎng qù Běijīng.", en: "I went to Xi'an several years ago, and it was great fun. This year I also want to visit Beijing.", th: "หลายปีก่อนฉันไปซีอาน สนุกมาก ปีนี้ฉันก็อยากไปปักกิ่ง", visual: { zh: "也想去北京", th: "ก็อยากไปปักกิ่ง", focus: "72% center" } }),
      line(travelRef, { role: "A", speaker: "李文", pinyin: "wǒ hé wáng lǎoshī dōu shì běijīng rén, běijīng fēicháng piàoliang", hanzi: "我和王老师都是北京人，北京非常漂亮。", reading: "Wǒ hé Wáng lǎoshī dōu shì Běijīng rén, Běijīng fēicháng piàoliang.", en: "Teacher Wang and I are both from Beijing. Beijing is very beautiful.", th: "ผมกับอาจารย์หวังเป็นคนปักกิ่งทั้งคู่ ปักกิ่งสวยมาก", visual: { zh: "都是北京人", th: "เป็นคนปักกิ่งทั้งคู่", focus: "24% center" } }),
    ],
    qte: {
      after: 4,
      prompt: { th: "ปีนี้แอนนี่อยากไปที่ไหน?", zh: "安妮今年想去哪儿？", en: "Where does Annie want to go this year?" },
      options: [
        { value: "北京", zh: "北京", pinyin: "Běijīng", th: "ปักกิ่ง" },
        { value: "西安", zh: "西安", pinyin: "Xī'ān", th: "ซีอาน" },
        { value: "上海", zh: "上海", pinyin: "Shànghǎi", th: "เซี่ยงไฮ้" },
      ],
      correct: "北京",
      evidence: "安妮：今年我想去北京。",
      evidenceTh: "แอนนี่: ปีนี้ฉันอยากไปปักกิ่ง",
      sourceRef: travelRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “ปีนี้ฉันก็อยากไปปักกิ่ง”", zh: "重组“今年我也想去北京”", en: "Rebuild “This year I also want to go to Beijing”" },
      answer: ["今年", "我", "也想去", "北京。"],
      tiles: ["北京。", "今年", "也想去", "我"],
      gloss: { 今年: "ปีนี้", 我: "ฉัน", 也想去: "ก็อยากไป", 北京: "ปักกิ่ง" },
      translationTh: "ปีนี้ฉันก็อยากไปปักกิ่ง",
      translationEn: "This year I also want to go to Beijing.",
      evidence: "Text 2 · หน้าเล่ม 115",
      sourceRef: travelRef,
    },
  },
  {
    id: "h1l15-airport",
    number: "03",
    glyph: "飞",
    title: "谈论去北京旅行",
    titleTh: "คุยเรื่องเดินทางไปปักกิ่ง",
    titleEn: "Talking about traveling to Beijing",
    place: "教室外",
    placeTh: "นอกห้องเรียน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l15-airport-v1.webp")} 1400w`,
    imageAlt: { th: "อาจารย์หวังวางแผนให้ไป๋เจียเยว่และอันนี่พบพี่สาวที่สนามบินต้าซิง", zh: "王老师安排白家月和安妮在大兴机场与姐姐见面", en: "Teacher Wang arranges for Bai Jiayue and Annie to meet her sister at Daxing Airport" },
    source: "Text 3 · หน้าเล่ม 116–117 · PDF หน้า 132–133",
    sourcePage: "116",
    sourceRef: airportRef,
    context: "在教室外，白家月、安妮和王老师在谈论去北京旅游的事。",
    contextTh: "นอกห้องเรียน ไป๋เจียเยว่ แอนนี่ และอาจารย์หวังคุยเรื่องไปเที่ยวปักกิ่ง",
    contextEn: "Outside the classroom, Bai Jiayue, Annie, and Teacher Wang discussed traveling to Beijing.",
    characters: [
      { role: "A", profile: "teacherWang", noteTh: "อาจารย์ผู้เสนอให้พี่สาวไปรับ", noteZh: "安排姐姐去机场接人的老师", noteEn: "The teacher arranging an airport pickup" },
      { role: "B", profile: "bai", noteTh: "นักเรียนผู้บอกเวลาเดินทางและกล่าวขอบคุณ", noteZh: "说明航程并表示感谢的学生", noteEn: "The student giving the flight duration and thanking her" },
      { role: "C", profile: "annie", noteTh: "นักเรียนผู้บอกเวลาถึงสนามบิน", noteZh: "说明到达时间的学生", noteEn: "The student stating the arrival time" },
    ],
    lines: [
      line(airportRef, { role: "A", speaker: "王一飞", pinyin: "nǐmen de fēijī dào běijīng yào jǐ ge xiǎoshí", hanzi: "你们的飞机到北京要几个小时？", reading: "Nǐmen de fēijī dào Běijīng yào jǐ ge xiǎoshí?", en: "How many hours will your flight take to get to Beijing?", th: "เครื่องบินของพวกเธอถึงปักกิ่งใช้เวลากี่ชั่วโมง?", visual: { zh: "要几个小时", th: "ใช้เวลากี่ชั่วโมง", focus: "72% center" } }),
      line(airportRef, { role: "B", speaker: "白家月", pinyin: "jiǔ ge xiǎoshí", hanzi: "九个小时。", reading: "Jiǔ ge xiǎoshí.", en: "Nine hours.", th: "เก้าชั่วโมง", visual: { zh: "九个小时", th: "เก้าชั่วโมง", focus: "28% center" } }),
      line(airportRef, { role: "A", speaker: "王一飞", pinyin: "wǒ jiārén dōu zài běijīng, xīngqītiān wǒ jiějie yě yǒu shíjiān, tā kěyǐ qù jīchǎng jiē nǐmen, nǐmen yě kěyǐ zhù wǒ jiā", hanzi: "我家人都在北京，星期天我姐姐也有时间，她可以去机场接你们，你们也可以住我家。", reading: "Wǒ jiārén dōu zài Běijīng, xīngqītiān wǒ jiějie yě yǒu shíjiān, tā kěyǐ qù jīchǎng jiē nǐmen, nǐmen yě kěyǐ zhù wǒ jiā.", en: "My family is all in Beijing. My sister is free on Sunday; she can pick you up at the airport, and you can stay at my home.", th: "ครอบครัวฉันอยู่ปักกิ่งทั้งหมด วันอาทิตย์พี่สาวฉันว่าง เธอไปรับพวกเธอที่สนามบินได้ และพวกเธอพักบ้านฉันได้", visual: { zh: "去机场接你们", th: "ไปรับพวกเธอที่สนามบิน", focus: "72% center" } }),
      line(airportRef, { role: "C", speaker: "安妮", pinyin: "wǒmen xīngqīrì zǎoshang bā diǎn dào dàxīng jīchǎng, zǎo bu zǎo", hanzi: "我们星期日早上八点到大兴机场，早不早？", reading: "Wǒmen xīngqīrì zǎoshang bā diǎn dào Dàxīng Jīchǎng, zǎo bu zǎo?", en: "We'll arrive at Daxing Airport at eight on Sunday morning. Is that early?", th: "เราจะถึงสนามบินต้าซิงแปดโมงเช้าวันอาทิตย์ เช้าไปไหม?", visual: { zh: "早上八点到大兴机场", th: "ถึงสนามบินต้าซิงแปดโมงเช้า", focus: "28% center" } }),
      line(airportRef, { role: "A", speaker: "王一飞", pinyin: "bù zǎo", hanzi: "不早。", reading: "Bù zǎo.", en: "Not early.", th: "ไม่เช้าไป", visual: { zh: "不早", th: "ไม่เช้าไป", focus: "72% center" } }),
      line(airportRef, { role: "B", speaker: "白家月", pinyin: "xièxie lǎoshī! nà wǒmen hé nín jiějie zài dàxīng jīchǎng jiàn", hanzi: "谢谢老师！那我们和您姐姐在大兴机场见！", reading: "Xièxie lǎoshī! Nà wǒmen hé nín jiějie zài Dàxīng Jīchǎng jiàn!", en: "Thank you, teacher! Then we'll meet your sister at Daxing Airport!", th: "ขอบคุณอาจารย์ ถ้าอย่างนั้นพวกเราพบพี่สาวอาจารย์ที่สนามบินต้าซิงนะ!", visual: { zh: "大兴机场见", th: "พบกันที่สนามบินต้าซิง", focus: "28% center" } }),
    ],
    qte: {
      after: 6,
      prompt: { th: "ใครสามารถไปรับไป๋เจียเยว่กับแอนนี่ที่สนามบินได้?", zh: "谁可以去机场接白家月和安妮？", en: "Who can pick up Bai Jiayue and Annie at the airport?" },
      options: [
        { value: "王老师的姐姐", zh: "王老师的姐姐", pinyin: "Wáng lǎoshī de jiějie", th: "พี่สาวของอาจารย์หวัง" },
        { value: "李文", zh: "李文", pinyin: "Lǐ Wén", th: "หลี่เหวิน" },
        { value: "陈天中", zh: "陈天中", pinyin: "Chén Tiānzhōng", th: "เฉินเทียนจง" },
      ],
      correct: "王老师的姐姐",
      evidence: "王一飞：我姐姐也有时间，她可以去机场接你们。",
      evidenceTh: "อาจารย์หวัง: พี่สาวฉันว่าง เธอไปรับพวกเธอที่สนามบินได้",
      sourceRef: airportRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “พวกเราพบกันที่สนามบินต้าซิง”", zh: "重组“我们在大兴机场见”", en: "Rebuild “We'll meet at Daxing Airport”" },
      answer: ["我们", "在", "大兴机场", "见！"],
      tiles: ["大兴机场", "见！", "我们", "在"],
      gloss: { 我们: "พวกเรา", 在: "ที่", 大兴机场: "สนามบินต้าซิง", 见: "พบกัน" },
      translationTh: "พวกเราพบกันที่สนามบินต้าซิง",
      translationEn: "We'll meet at Daxing Airport!",
      evidence: "Text 3 · หน้าเล่ม 117",
      sourceRef: airportRef,
    },
  },
];

export const LESSON_HSK1_L15 = {
  id: "hsk1-l15",
  slug: "lesson-15",
  level: "hsk1",
  number: 15,
  featured: false,
  source: {
    title: "新HSK教程 1 · New HSK Course 1",
    lesson: "Lesson 15 · 大兴机场见！",
    printedPages: "112–119",
    pdfPages: "128–135",
    file: "hsk1-2.pdf",
    sourceRef,
  },
  sourceRef,
  title: { zh: "大兴机场见！", pinyin: "Dàxīng Jīchǎng jiàn!", en: "See you at Daxing Airport!", thAid: "พบกันที่สนามบินต้าซิง!" },
  summary: {
    zh: "学习表达旅行意愿和计划，掌握并列复句“……，还/也……”，并了解中国餐桌文化、待客礼仪和首都北京。",
    en: "Learn to express travel intentions and plans, use the coordinate compound pattern …还/也…, and understand Chinese dining culture, hospitality, and Beijing.",
    thAid: "เรียนการบอกความตั้งใจและแผนเดินทาง ใช้ประโยคคู่ขนาน …还/也… และรู้จักวัฒนธรรมโต๊ะอาหาร การต้อนรับแขก และปักกิ่ง",
  },
  translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并使用相关词语表达旅行意愿、计划。", en: "Be able to understand and use relevant vocabulary to express travel intentions and plans.", thAid: "ฟังเข้าใจและใช้คำที่เกี่ยวข้องบอกความตั้งใจและแผนเดินทาง", sourceRef: lessonHsk1L15SourceRef("112", "128") },
    { zh: "掌握并列复句“……，还/也……”。", en: "Master the coordinate compound sentence …, 还/也….", thAid: "ใช้ประโยคคู่ขนาน …，还/也… เพื่อเชื่อมข้อมูลที่สัมพันธ์กัน", sourceRef: lessonHsk1L15SourceRef("112", "128") },
    { zh: "了解中国餐桌文化、待客礼仪。", en: "Understand Chinese dining culture and hospitality etiquette.", thAid: "เข้าใจวัฒนธรรมโต๊ะอาหารจีนและมารยาทการต้อนรับแขก", sourceRef: lessonHsk1L15SourceRef("112", "128") },
    { zh: "了解中国的首都——北京。", en: "Understand Beijing, the capital of China.", thAid: "รู้จักปักกิ่ง เมืองหลวงของจีน", sourceRef: lessonHsk1L15SourceRef("112", "128") },
  ],
  contents: [
    { number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "112", route: "/home/hsk1/lesson-15/preface/", sourceRef: lessonHsk1L15SourceRef("112", "128") },
    { number: "01", title: "在李文家品尝中国菜", titleTh: "ชิมอาหารจีนที่บ้านหลี่เหวิน", detail: "Text 1 · New Words 1–2", pages: "113–114", scene: 1, sourceRef: lessonHsk1L15SourceRef("113-114", "129-130") },
    { number: "02", title: "边吃饭边谈假期计划", titleTh: "คุยแผนวันหยุดระหว่างกินข้าว", detail: "Text 2 · New Words 3–7", pages: "114–115", scene: 2, sourceRef: lessonHsk1L15SourceRef("114-115", "130-131") },
    { number: "03", title: "谈论去北京旅行", titleTh: "คุยเรื่องเดินทางไปปักกิ่ง", detail: "Text 3 · New Words 8–17", pages: "116–117", scene: 3, sourceRef: lessonHsk1L15SourceRef("116-117", "132-133") },
    { number: "04", title: "综合练习与活动", titleTh: "แบบฝึกรวมและกิจกรรม", detail: "Comprehensive Exercises (source trail)", pages: "118–119", sourceRef: lessonHsk1L15SourceRef("118-119", "134-135") },
  ],
  vocabulary,
  grammarFocus: [
    { title: "并列复句“……，还/也……”", titleEn: "Coordinate Compound Sentence …, 还/也…", explanationZh: "并列复句由两个或两个以上逻辑关联、结构对称的小句构成。本课学习“……，还/也……”格式。", explanationEn: "A coordinate compound sentence consists of two or more logically related, structurally parallel clauses. This lesson uses the pattern …, 还/也….", thAid: "ประโยคคู่ขนานเชื่อมอนุประโยคที่สัมพันธ์กันด้วย 还 หรือ 也 เช่น 我喜欢这个，也喜欢那个", examples: ["我喜欢这个，也喜欢那个。", "王老师是北京人，李文也是北京人。", "我喜欢喝中国茶，还喜欢吃中国菜。"], sourceRef: lessonHsk1L15SourceRef("114", "130") },
    { title: "表达旅行意愿和计划", titleEn: "Expressing Travel Intentions and Plans", explanationZh: "可以用“想+去+地点”表达旅行意愿，用时间词说明计划。例如：今年我想去北京。", explanationEn: "Use 想 + 去 + place to express a travel intention, and add a time word to state the plan. For example: 今年我想去北京。", thAid: "ใช้ 想+去+สถานที่ บอกความตั้งใจเดินทาง และใส่คำบอกเวลาเพื่อเป็นแผน เช่น 今年我想去北京", examples: ["今年我想去北京。", "你们都想去哪儿？", "今年我也想去北京。"], sourceRef: lessonHsk1L15SourceRef("114-115", "130-131") },
  ],
  characters,
  scenes,
};
