export const COPY = {
  th: {
    appTitle: "HuaYun 华韵学堂",
    appSubtitle: "ศูนย์รวมบทเรียนภาษาจีน HSK 1 - HSK 3",
    navHome: "หน้าแรก",
    navLessons: "บทเรียนทั้งหมด",
    navGroups: "กลุ่มโปรเจกต์",
    navDashboard: "แดชบอร์ด",
    learnVocab: "คำศัพท์",
    learnGrammar: "ไวยากรณ์",
    learnDialogue: "บทสนทนา",
    quiz: "แบบทดสอบ",
    score: "คะแนน",
    submitQuiz: "ส่งแบบทดสอบ",
    completed: "เสร็จสิ้น",
    inProgress: "กำลังดำเนินการ",
    report: {
      kicker: "รายงานแบบไม่ระบุตัวตน",
      title: "แจ้งปัญหาเพื่อช่วยพัฒนาบทเรียน",
      subtitle: "บอกสิ่งที่เกิดขึ้นและขั้นตอนที่ทำให้พบปัญหา ทีมงานจะนำข้อมูลไปตรวจสอบโดยไม่เก็บตัวตนของคุณ",
      privacyTitle: "ส่งข้อมูลเท่าที่จำเป็น",
      privacyBody: "แบบฟอร์มนี้ไม่ขอชื่อ อีเมล รูปภาพ และไม่เก็บข้อมูลอุปกรณ์หรือ URL อัตโนมัติ กรุณาอย่าใส่ข้อมูลส่วนตัวลงในข้อความ",
      categoryLabel: "ประเภทปัญหา",
      categoryBug: "ระบบหรือปุ่มใช้งานไม่ได้",
      categoryContent: "เนื้อหา พินอิน หรือคำแปล",
      categoryDesign: "การแสดงผลหรือการจัดวาง",
      categorySuggestion: "ข้อเสนอแนะ",
      severityLabel: "ระดับผลกระทบ",
      severityLow: "ต่ำ — ยังเรียนต่อได้",
      severityMedium: "ปานกลาง — รบกวนการเรียน",
      severityHigh: "สูง — เรียนต่อไม่ได้",
      descriptionLabel: "รายละเอียดปัญหา",
      descriptionHint: "อย่างน้อย 10 ตัวอักษร สูงสุด 4,000 ตัวอักษร",
      descriptionPlaceholder: "อธิบายสิ่งที่เห็น สิ่งที่คาดว่าจะเกิด และบทเรียนหรือส่วนที่เกี่ยวข้อง",
      stepsLabel: "ขั้นตอนที่ทำให้พบปัญหา (ไม่บังคับ)",
      stepsHint: "สูงสุด 3,000 ตัวอักษร",
      stepsPlaceholder: "เช่น เปิดบทเรียน → เลือกแบบทดสอบ → กดส่งคำตอบ",
      characterCount: "ตัวอักษร",
      submit: "ส่งรายงาน",
      submitting: "กำลังส่งรายงาน…",
      cancel: "กลับหน้าแรก",
      successTitle: "ส่งรายงานเรียบร้อยแล้ว",
      successBody: "ขอบคุณที่ช่วยให้บทเรียนดีขึ้น รายงานถูกบันทึกแบบไม่ระบุตัวตนแล้ว",
      submitAnother: "ส่งรายงานอีกฉบับ",
      errorTitle: "ยังส่งรายงานไม่ได้",
      retry: "ลองส่งอีกครั้ง",
      descriptionTooShort: "กรุณาอธิบายปัญหาอย่างน้อย 10 ตัวอักษร",
      descriptionTooLong: "รายละเอียดต้องไม่เกิน 4,000 ตัวอักษร",
      stepsTooLong: "ขั้นตอนต้องไม่เกิน 3,000 ตัวอักษร",
      invalidPayload: "ข้อมูลบางส่วนไม่ถูกต้อง กรุณาตรวจสอบแล้วลองอีกครั้ง",
      payloadTooLarge: "รายงานมีขนาดใหญ่เกินไป กรุณาย่อข้อความแล้วลองอีกครั้ง",
      rateLimited: "มีการส่งรายงานถี่เกินไป กรุณารอสักครู่แล้วลองใหม่",
      serverError: "ระบบรับรายงานขัดข้องชั่วคราว กรุณาลองใหม่ภายหลัง",
      networkError: "เชื่อมต่อระบบไม่ได้ กรุณาตรวจสอบอินเทอร์เน็ตแล้วลองใหม่",
    },
  },
  zh: {
    appTitle: "华韵学堂",
    appSubtitle: "HSK 1 - HSK 3 汉语课程中心",
    navHome: "首页",
    navLessons: "所有课程",
    navGroups: "项目小组",
    navDashboard: "仪表板",
    learnVocab: "词汇",
    learnGrammar: "语法",
    learnDialogue: "对话",
    quiz: "测验",
    score: "得分",
    submitQuiz: "提交测验",
    completed: "已完成",
    inProgress: "进行中",
    report: {
      kicker: "匿名报告",
      title: "报告问题，帮助改进课程",
      subtitle: "请说明遇到的情况和复现步骤。团队只会使用必要信息进行排查，不会收集您的身份。",
      privacyTitle: "只提交必要信息",
      privacyBody: "本表单不要求姓名、邮箱或图片，也不会自动收集设备信息或当前网址。请勿在文字中填写个人信息。",
      categoryLabel: "问题类型",
      categoryBug: "系统或按钮无法使用",
      categoryContent: "课程内容、拼音或翻译",
      categoryDesign: "显示或排版问题",
      categorySuggestion: "改进建议",
      severityLabel: "影响程度",
      severityLow: "低 — 仍可继续学习",
      severityMedium: "中 — 影响学习体验",
      severityHigh: "高 — 无法继续学习",
      descriptionLabel: "问题详情",
      descriptionHint: "至少 10 个字符，最多 4,000 个字符",
      descriptionPlaceholder: "请描述实际情况、预期结果以及相关课程或功能",
      stepsLabel: "复现步骤（选填）",
      stepsHint: "最多 3,000 个字符",
      stepsPlaceholder: "例如：打开课程 → 选择测验 → 点击提交答案",
      characterCount: "字符",
      submit: "提交报告",
      submitting: "正在提交…",
      cancel: "返回首页",
      successTitle: "报告已提交",
      successBody: "感谢您帮助改进课程。报告已匿名保存。",
      submitAnother: "再提交一份报告",
      errorTitle: "暂时无法提交报告",
      retry: "再次尝试",
      descriptionTooShort: "请至少填写 10 个字符的问题说明",
      descriptionTooLong: "问题详情不得超过 4,000 个字符",
      stepsTooLong: "复现步骤不得超过 3,000 个字符",
      invalidPayload: "部分信息无效，请检查后重试",
      payloadTooLarge: "报告内容过大，请精简文字后重试",
      rateLimited: "提交过于频繁，请稍后再试",
      serverError: "报告服务暂时不可用，请稍后再试",
      networkError: "无法连接服务器，请检查网络后重试",
    },
  },
  en: {
    appTitle: "HuaYun Learning Hall",
    appSubtitle: "HSK 1 - HSK 3 Chinese Course Center",
    navHome: "Home",
    navLessons: "All lessons",
    navGroups: "Project groups",
    navDashboard: "Dashboard",
    learnVocab: "Vocabulary",
    learnGrammar: "Grammar",
    learnDialogue: "Dialogue",
    quiz: "Quiz",
    score: "Score",
    submitQuiz: "Submit quiz",
    completed: "Completed",
    inProgress: "In progress",
    report: {
      kicker: "Anonymous report",
      title: "Report an issue and improve the lessons",
      subtitle: "Tell us what happened and how to reproduce it. The team only uses the necessary details and does not collect your identity.",
      privacyTitle: "Share only what is needed",
      privacyBody: "This form does not ask for a name, email, or image, and it does not automatically collect device data or the current URL. Do not include personal information in the text.",
      categoryLabel: "Issue category",
      categoryBug: "System or controls not working",
      categoryContent: "Lesson content, pinyin, or translation",
      categoryDesign: "Display or layout",
      categorySuggestion: "Suggestion",
      severityLabel: "Impact",
      severityLow: "Low — learning can continue",
      severityMedium: "Medium — learning is disrupted",
      severityHigh: "High — learning cannot continue",
      descriptionLabel: "Issue details",
      descriptionHint: "10 to 4,000 characters",
      descriptionPlaceholder: "Describe what you saw, what you expected, and the related lesson or feature",
      stepsLabel: "Steps to reproduce (optional)",
      stepsHint: "Up to 3,000 characters",
      stepsPlaceholder: "For example: Open a lesson → choose Quiz → submit an answer",
      characterCount: "characters",
      submit: "Submit report",
      submitting: "Submitting…",
      cancel: "Back to home",
      successTitle: "Report submitted",
      successBody: "Thank you for helping improve the lessons. Your report was saved anonymously.",
      submitAnother: "Send another report",
      errorTitle: "The report could not be sent",
      retry: "Try again",
      descriptionTooShort: "Describe the issue in at least 10 characters",
      descriptionTooLong: "Issue details must be no longer than 4,000 characters",
      stepsTooLong: "Steps must be no longer than 3,000 characters",
      invalidPayload: "Some information is invalid. Check the form and try again.",
      payloadTooLarge: "The report is too large. Shorten the text and try again.",
      rateLimited: "Reports are being sent too frequently. Wait a moment and try again.",
      serverError: "The report service is temporarily unavailable. Try again later.",
      networkError: "The server could not be reached. Check your connection and try again.",
    },
  },
};

export default COPY;
