import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk3.pdf";

export function lessonHsk3L2SourceRef(printedPages, pdfPages) {
  return `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
}

const sourceRef = lessonHsk3L2SourceRef("10-18", "22-30");

const characters = {
  wang: {
    hanzi: "王一雪",
    pinyin: "Wáng Yīxuě",
    nameTh: "หวังอี้เสวี่ย",
    nameEn: "Wang Yixue",
    image: group3AssetPath("/assets/group3/shared/characters/character-wang-yixue.webp"),
  },
  liu: {
    hanzi: "刘明",
    pinyin: "Liú Míng",
    nameTh: "หลิวหมิง",
    nameEn: "Liu Ming",
    image: group3AssetPath("/assets/group3/shared/characters/character-liu-ming.webp"),
  },
  bai: {
    hanzi: "白家月",
    pinyin: "Bái Jiāyuè",
    nameTh: "ไป๋เจียเยว่",
    nameEn: "Bai Jiayue",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp")} 1400w`,
    imageFocus: "30% center",
  },
  liWen: {
    hanzi: "李文",
    pinyin: "Lǐ Wén",
    nameTh: "หลี่เหวิน",
    nameEn: "Li Wen",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp")} 1400w`,
    imageFocus: "56% center",
  },
  shopServer: {
    hanzi: "服务员",
    pinyin: "fúwùyuán",
    nameTh: "พนักงานเสิร์ฟ",
    nameEn: "Waitress",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-v1.webp")} 1400w`,
    imageFocus: "70% center",
  },
};

const vocabularyPages = [
  [1, "菜单", "càidān", "n.", "menu", "เมนู", 11, 23],
  [2, "又", "yòu", "adv.", "and; also (in 又…又…)", "ก็…ก็… (ใช้คู่กันบอกสองลักษณะ)", 11, 23],
  [3, "饿", "è", "adj.", "hungry", "หิว", 11, 23],
  [4, "渴", "kě", "adj.", "thirsty", "กระหายน้ำ", 11, 23],
  [5, "客气", "kèqi", "v./adj.", "be polite; polite", "เกรงใจ / พูดจาเรียบร้อย", 11, 23],
  [6, "饮料", "yǐnliào", "n.", "drink; beverage", "เครื่องดื่ม", 11, 23],
  [7, "好久", "hǎojiǔ", "adj.", "for a long time", "นานมาแล้ว / ไม่ได้…มานาน", 11, 23],
  [8, "服务", "fúwù", "v.", "serve", "บริการ", 13, 25],
  [9, "筷子", "kuàizi", "n.", "chopsticks", "ตะเกียบ", 13, 25],
  [10, "勺子", "sháozi", "n.", "spoon", "ช้อน", 13, 25],
  [11, "碗", "wǎn", "n.", "bowl", "ถ้วย / ชาม", 13, 25],
  [12, "马上", "mǎshàng", "adv.", "immediately", "เดี๋ยวนี้ / ทันที", 13, 25],
  [13, "热情", "rèqíng", "adj.", "warm; enthusiastic", "อบอุ่น / กระตือรือร้น", 13, 25],
  [14, "尝", "cháng", "v.", "taste", "ชิม", 13, 25],
  [15, "记", "jì", "v.", "remember", "จำ", 13, 25],
  [16, "外卖", "wàimài", "n./v.", "takeout; food delivery", "อาหารเดลิเวอรี / ส่งอาหาร", 15, 27],
  [17, "方便", "fāngbiàn", "adj.", "convenient", "สะดวก", 15, 27],
  [18, "不用", "búyòng", "adv.", "need not", "ไม่ต้อง", 15, 27],
  [19, "蛋糕", "dàngāo", "n.", "cake", "เค้ก", 16, 28],
  [20, "简单", "jiǎndān", "adj.", "simple", "ง่าย ๆ", 16, 28],
];

const vocabulary = vocabularyPages.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({
  index,
  hanzi,
  pinyin,
  type,
  en,
  th: thAid,
  thAid,
  page,
  translationKind: "editorial-aid",
  sourceRef: lessonHsk3L2SourceRef(String(page), String(pdfPage)),
}));

function line(source, value) {
  return { ...value, sourceRef: source };
}

const menuRef = lessonHsk3L2SourceRef("11", "23");
const restaurantRef = lessonHsk3L2SourceRef("12-13", "24-25");
const takeoutRef = lessonHsk3L2SourceRef("14-15", "26-27");

const scenes = [
  {
    id: "l2-menu",
    number: "01",
    glyph: "菜",
    title: "在饭馆点菜",
    titleTh: "สั่งอาหารในร้าน",
    titleEn: "Ordering food in the restaurant",
    place: "饭馆",
    placePy: "fànguǎn",
    placeTh: "ร้านอาหาร",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-menu-v1.webp")} 1400w`,
    imageAlt: {
      th: "การสั่งอาหารในร้าน",
      zh: "饭馆点菜照片",
      en: "Ordering food scene",
    },
    source: "Text 1 · หน้าเล่ม 11 · PDF หน้า 23",
    sourcePage: "11",
    sourceRef: menuRef,
    context: "在饭馆，王一雪、刘明、白家月和李文在点菜。",
    contextTh: "ในร้านอาหาร หวังอี้เสวี่ย หลิวหมิง ไป๋เจียเยว่ และหลี่เหวินกำลังสั่งอาหาร",
    contextEn: "At the restaurant, Wang Yixue, Liu Ming, Bai Jiayue, and Li Wen were deciding what to order.",
    characters: [
      { role: "A", profile: "wang", noteTh: "เจ้าภาพที่ให้เพื่อน ๆ สั่งอาหารตามใจ", noteZh: "请大家随便点菜的主人", noteEn: "The host letting everyone order freely" },
      { role: "B", profile: "liWen", noteTh: "เพื่อนที่กินอะไรก็ได้", noteZh: "吃什么都行的同学", noteEn: "The friend who eats anything" },
      { role: "C", profile: "bai", noteTh: "เพื่อนที่หิวและอยากกินชาเขียวกับเกี๊ยว", noteZh: "又饿又渴、想喝绿茶吃饺子的同学", noteEn: "The hungry friend craving green tea and jiaozi" },
    ],
    lines: [
      line(menuRef, { role: "A", speaker: "王一雪", pinyin: "nǐmen kànkan càidān, xiǎng chī diǎnr shénme", hanzi: "家月、李文，你们看看菜单，想吃点儿什么？", reading: "Jiāyuè, Lǐ Wén, nǐmen kànkan càidān, xiǎng chī diǎnr shénme?", en: "Jiayue, Li Wen, take a look at the menu. What would you like to eat?", th: "เจียเยว่ หลี่เหวิน พวกเธอดูเมนูก่อน อยากกินอะไร?", visual: { zh: "看看菜单", th: "ดูเมนู", focus: "46% center" } }),
      line(menuRef, { role: "B", speaker: "李文", pinyin: "wǒ dōu kěyǐ, nǐmen diǎn ba", hanzi: "谢谢一雪姐，我都可以，你们点吧。", reading: "Xièxie Yīxuě jiě, wǒ dōu kěyǐ, nǐmen diǎn ba.", en: "Thanks, Sister Yixue. Anything works for me — you order.", th: "ขอบคุณพี่อี้เสวี่ย ฉันกินอะไรก็ได้ พวกคุณสั่งเลย", visual: { zh: "我都可以", th: "ฉันกินอะไรก็ได้", focus: "58% center" } }),
      line(menuRef, { role: "C", speaker: "白家月", pinyin: "xiànzài hái zhēn shì yòu è yòu kě", hanzi: "飞了这么远，现在还真是又饿又渴。", reading: "Fēi le zhème yuǎn, xiànzài hái zhēn shì yòu è yòu kě.", en: "After flying this far, I’m really hungry and thirsty now.", th: "บินมาไกลขนาดนี้ ตอนนี้ก็หิวแล้วก็กระหายจริง ๆ", visual: { zh: "又饿又渴", th: "หิวและกระหาย", focus: "30% center" } }),
      line(menuRef, { role: "A", speaker: "王一雪", pinyin: "nà duō diǎn diǎnr, bié kèqi", hanzi: "那多点点儿，别客气。你们喝什么饮料？", reading: "Nà duō diǎn diǎnr, bié kèqi. Nǐmen hē shénme yǐnliào?", en: "Then order more — don’t be shy. What would you like to drink?", th: "งั้นสั่งเยอะ ๆ เลย ไม่ต้องเกรงใจ พวกเธอดื่มอะไร?", visual: { zh: "别客气", th: "ไม่ต้องเกรงใจ", focus: "52% center" } }),
      line(menuRef, { role: "C", speaker: "白家月", pinyin: "hǎojiǔ méi hē Zhōngguó chá, yě hǎojiǔ méi chī jiǎozi le", hanzi: "好久没喝中国茶，也好久没吃饺子了。我想喝绿茶、吃饺子，可以吗？", reading: "Hǎojiǔ méi hē Zhōngguó chá, yě hǎojiǔ méi chī jiǎozi le. Wǒ xiǎng hē lǜchá, chī jiǎozi, kěyǐ ma?", en: "I haven’t had Chinese tea or jiaozi in ages. I’d like green tea and jiaozi — is that okay?", th: "ไม่ได้ดื่มชาจีนมานาน ไม่ได้กินเกี๊ยวมานานเหมือนกัน ฉันอยากดื่มชาเขียวกับกินเกี๊ยว ได้ไหม?", visual: { zh: "好久没…了", th: "ไม่ได้…มานาน", focus: "32% center" } }),
      line(menuRef, { role: "A", speaker: "王一雪", pinyin: "méi wèntí. nǐmen kànkan hái xiǎng chī shénme", hanzi: "没问题。你们看看还想吃什么。", reading: "Méi wèntí. Nǐmen kànkan hái xiǎng chī shénme.", en: "No problem. See what else you’d like.", th: "ได้ พวกเธอดูอีกทีว่ายังอยากกินอะไร", visual: { zh: "没问题", th: "ไม่มีปัญหา", focus: "48% center" } }),
    ],
    qte: {
      after: 2,
      prompt: { th: "ตอนนี้ไป๋เจียเยว่รู้สึกอย่างไร?", zh: "白家月现在觉得怎么样？", en: "How does Bai Jiayue feel right now?" },
      options: [
        { value: "又饿又渴", zh: "又饿又渴", pinyin: "yòu è yòu kě", th: "หิวและกระหาย" },
        { value: "又冷又累", zh: "又冷又累", pinyin: "yòu lěng yòu lèi", th: "หนาวและเหนื่อย" },
        { value: "又困又累", zh: "又困又累", pinyin: "yòu kùn yòu lèi", th: "ง่วงและเหนื่อย" },
      ],
      correct: "又饿又渴",
      evidence: "白家月：现在还真是又饿又渴。",
      evidenceTh: "ไป๋เจียเยว่: ตอนนี้หิวและกระหายจริง ๆ",
      sourceRef: menuRef,
    },
    builder: {
      prompt: { th: "เรียงประโยคสั่งเครื่องดื่มกับเกี๊ยวของไป๋เจียเยว่", zh: "重组白家月点绿茶和饺子的句子", en: "Rebuild Bai Jiayue’s order sentence" },
      answer: ["我", "想", "喝", "绿茶", "吃", "饺子"],
      tiles: ["吃", "绿茶", "饺子", "喝", "我", "想"],
      gloss: { 我: "ฉัน", 想: "อยาก", 喝: "ดื่ม", 绿茶: "ชาเขียว", 吃: "กิน", 饺子: "เกี๊ยว" },
      translationTh: "ฉันอยากดื่มชาเขียว กินเกี๊ยว",
      translationEn: "I’d like green tea and jiaozi.",
      evidence: "Text 1 · หน้าเล่ม 11",
      sourceRef: menuRef,
    },
  },
  {
    id: "l2-restaurant",
    number: "02",
    glyph: "筷",
    title: "在饭馆吃饭",
    titleTh: "ทานอาหารในร้าน",
    titleEn: "Having a meal in the restaurant",
    place: "饭馆",
    placePy: "fànguǎn",
    placeTh: "ร้านอาหาร",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-restaurant-v1.webp")} 1400w`,
    imageAlt: {
      th: "การรับประทานอาหารในร้าน",
      zh: "饭馆就餐照片",
      en: "Dining scene",
    },
    source: "Text 2 · หน้าเล่ม 12–13 · PDF หน้า 24–25",
    sourcePage: "13",
    sourceRef: restaurantRef,
    context: "在饭馆，王一雪、刘明、白家月和李文一起吃饭。",
    contextTh: "ในร้านอาหาร ทั้งสี่คนกำลังทานอาหารด้วยกัน",
    contextEn: "At the restaurant, the group was having a meal together.",
    characters: [
      { role: "A", profile: "shopServer", noteTh: "พนักงานเสิร์ฟผู้ส่งเครื่องใช้และแถมผลไม้", noteZh: "送餐具并赠送水果的服务员", noteEn: "The waitress bringing tableware and fruit" },
      { role: "B", profile: "wang", noteTh: "ลูกค้าประจำที่ชมบริการและรสชาติอาหาร", noteZh: "夸奖服务和菜品的常客", noteEn: "The regular customer praising the service" },
      { role: "C", profile: "bai", noteTh: "ลูกค้าที่ชมว่ารสชาติดีทุกจาน", noteZh: "称赞每道菜都好吃的客人", noteEn: "The guest saying every dish is delicious" },
    ],
    lines: [
      line(restaurantRef, { role: "B", speaker: "王一雪", pinyin: "zài gěi wǒmen ná yì shuāng kuàizi, yí ge sháozi hé yí ge wǎn", hanzi: "服务员，再给我们拿一双筷子、一个勺子和一个碗。", reading: "Fúwùyuán, zài gěi wǒmen ná yì shuāng kuàizi, yí ge sháozi hé yí ge wǎn.", en: "Waitress, please bring us another pair of chopsticks, a spoon, and a bowl.", th: "พนักงานคะ ขอเพิ่มตะเกียบหนึ่งคู่ ช้อนหนึ่งคัน และถ้วยหนึ่งใบ", visual: { zh: "一双筷子", th: "ตะเกียบหนึ่งคู่", focus: "44% center" } }),
      line(restaurantRef, { role: "A", speaker: "服务员", pinyin: "qǐng děng yíxià, wǒ mǎshàng qù ná", hanzi: "好的，请等一下，我马上去拿。", reading: "Hǎo de, qǐng děng yíxià, wǒ mǎshàng qù ná.", en: "Okay, wait a moment — I’ll get it right away.", th: "ค่ะ รอสักครู่ ฉันไปหยิบเดี๋ยวนี้", visual: { zh: "马上去拿", th: "ไปหยิบเดี๋ยวนี้", focus: "68% center" } }),
      line(restaurantRef, { role: "B", speaker: "王一雪", pinyin: "zhè jiā fànguǎn de fúwù hěn rèqíng", hanzi: "这家饭馆的服务很热情，菜也都做得很好吃。你们尝尝，看喜不喜欢这些菜。", reading: "Zhè jiā fànguǎn de fúwù hěn rèqíng, cài yě dōu zuò de hěn hǎochī. Nǐmen chángchang, kàn xǐ bu xǐhuan zhèxiē cài.", en: "The service here is very warm, and the dishes are all delicious. Try them and see if you like them.", th: "ร้านนี้บริการอบอุ่นมาก อาหารก็ทำอร่อย พวกเธอลองชิมดูว่าโปรดไหม", visual: { zh: "服务很热情", th: "บริการอบอุ่น", focus: "40% center" } }),
      line(restaurantRef, { role: "C", speaker: "白家月", pinyin: "nǎge cài dōu hǎochī", hanzi: "哪个菜都好吃。您点的这些菜真不错。", reading: "Nǎge cài dōu hǎochī. Nín diǎn de zhèxiē cài zhēn búcuò.", en: "Every dish is delicious. The ones you ordered are really good.", th: "อาหารจานไหนก็อร่อย อาหารที่คุณสั่งมาดีจริง ๆ", visual: { zh: "哪个…都", th: "จานไหนก็…", focus: "32% center" } }),
      line(restaurantRef, { role: "B", speaker: "王一雪", pinyin: "zhèlǐ de fàncài yòu piányi yòu hǎochī", hanzi: "这里的饭菜又便宜又好吃，我们经常来，服务员都记住我们爱吃的菜了。", reading: "Zhèlǐ de fàncài yòu piányi yòu hǎochī, wǒmen jīngcháng lái, fúwùyuán dōu jìzhù wǒmen ài chī de cài le.", en: "The food here is both cheap and tasty. We come often, and the waitress remembers what we like.", th: "อาหารที่นี่ทั้งถูกทั้งอร่อย เรามาบ่อย พนักงานจำได้หมดว่าเราชอบกินอะไร", visual: { zh: "又便宜又好吃", th: "ทั้งถูกทั้งอร่อย", focus: "44% center" } }),
      line(restaurantRef, { role: "A", speaker: "服务员", pinyin: "jīntiān sòng nín yìxiē shuǐguǒ, qǐng màn yòng", hanzi: "王姐，您经常来吃饭，今天送您一些水果，请慢用。", reading: "Wáng jiě, nín jīngcháng lái chīfàn, jīntiān sòng nín yìxiē shuǐguǒ, qǐng màn yòng.", en: "Sister Wang, since you come often, we’d like to give you some fruit today. Enjoy your meal.", th: "พี่หวัง คุณมาทานบ่อย วันนี้แถมผลไม้ให้หน่อย เชิญทานตามสบายนะคะ", visual: { zh: "送您一些水果", th: "แถมผลไม้ให้", focus: "66% center" } }),
    ],
    qte: {
      after: 3,
      prompt: { th: "ร้านนี้บริการเป็นอย่างไร?", zh: "这家饭馆的服务怎么样？", en: "How is the service at this restaurant?" },
      options: [
        { value: "很热情", zh: "很热情", pinyin: "hěn rèqíng", th: "อบอุ่นมาก" },
        { value: "很慢", zh: "很慢", pinyin: "hěn màn", th: "ช้ามาก" },
        { value: "不太好", zh: "不太好", pinyin: "bú tài hǎo", th: "ไม่ค่อยดี" },
      ],
      correct: "很热情",
      evidence: "王一雪：这家饭馆的服务很热情。",
      evidenceTh: "หวังอี้เสวี่ย: ร้านนี้บริการอบอุ่นมาก",
      sourceRef: restaurantRef,
    },
    builder: {
      prompt: { th: "เรียงประโยคขอเครื่องใช้ของหวังอี้เสวี่ย", zh: "重组王一雪要餐具的句子", en: "Rebuild Wang Yixue’s tableware request" },
      answer: ["再", "给", "我们", "拿", "一双", "筷子"],
      tiles: ["我们", "一双", "再", "筷子", "拿", "给"],
      gloss: { 再: "เพิ่มอีก", 给: "ให้", 我们: "พวกเรา", 拿: "หยิบ", 一双: "หนึ่งคู่", 筷子: "ตะเกียบ" },
      translationTh: "ขอตะเกียบเพิ่มอีกหนึ่งคู่",
      translationEn: "Bring us another pair of chopsticks.",
      evidence: "Text 2 · หน้าเล่ม 13",
      sourceRef: restaurantRef,
    },
  },
  {
    id: "l2-takeout",
    number: "03",
    glyph: "外",
    title: "边吃边聊",
    titleTh: "ทานไปคุยไป",
    titleEn: "Chatting over the meal",
    place: "饭馆",
    placePy: "fànguǎn",
    placeTh: "ร้านอาหาร",
    image: group3AssetPath("/assets/group3/lesson-hsk3-l2-takeout-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk3-l2-takeout-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk3-l2-takeout-v1.webp")} 1400w`,
    imageAlt: {
      th: "การสนทนาขณะทานอาหาร",
      zh: "饭馆畅聊照片",
      en: "Chatting at the table",
    },
    source: "Text 3 · หน้าเล่ม 14–15 · PDF หน้า 26–27",
    sourcePage: "15",
    sourceRef: takeoutRef,
    context: "在饭馆，王一雪、刘明、白家月和李文继续边吃边聊。",
    contextTh: "ในร้านอาหาร ทั้งสี่คนทานไปคุยไปต่อ",
    contextEn: "At the restaurant, the group carried on chatting over their meal.",
    characters: [
      { role: "A", profile: "bai", noteTh: "เพื่อนที่ติดใจข้าวไก่และอยากสั่งอีก", noteZh: "爱吃鸡肉饭、想再点的同学", noteEn: "The friend loving the chicken rice" },
      { role: "B", profile: "liWen", noteTh: "เพื่อนที่แนะนำให้เอาเมนูกลับไปดู", noteZh: "建议带走菜单的同学", noteEn: "The friend suggesting taking the menu" },
      { role: "C", profile: "wang", noteTh: "เพื่อนที่แนะนำการสั่งผ่านมือถือและเดลิเวอรี", noteZh: "介绍手机点餐和外卖的同学", noteEn: "The friend introducing mobile ordering and delivery" },
    ],
    lines: [
      line(takeoutRef, { role: "A", speaker: "白家月", pinyin: "zhège jīròu fàn tài hǎochī le", hanzi: "这个鸡肉饭太好吃了，我要再来吃一次。", reading: "Zhège jīròu fàn tài hǎochī le, wǒ yào zài lái chī yí cì.", en: "This chicken rice is so tasty — I’ll come again for another round.", th: "ข้าวไก่จานนี้อร่อยมาก ฉันจะมากินอีกครั้ง", visual: { zh: "再来吃一次", th: "มากินอีกครั้ง", focus: "30% center" } }),
      line(takeoutRef, { role: "B", speaker: "李文", pinyin: "nǐ kěyǐ ná zǒu zhè zhāng càidān", hanzi: "你可以拿走这张菜单，看看下次还吃点儿什么。", reading: "Nǐ kěyǐ ná zǒu zhè zhāng càidān, kànkan xiàcì hái chī diǎnr shénme.", en: "You can take this menu home and see what to order next time.", th: "เธอเอาเมนูนี้กลับไปได้ ดูไว้ว่าครั้งหน้าจะกินอะไร", visual: { zh: "这张菜单", th: "เมนูนี้", focus: "58% center" } }),
      line(takeoutRef, { role: "C", speaker: "王一雪", pinyin: "búyòng ná càidān, zài shǒujī shang jiù néng kàndào", hanzi: "不用拿菜单，在手机上就能看到，也可以选好了让他们给你送。", reading: "Búyòng ná càidān, zài shǒujī shang jiù néng kàndào, yě kěyǐ xuǎn hǎo le ràng tāmen gěi nǐ sòng.", en: "No need to take the menu — you can see it on your phone, or order and have them deliver it.", th: "ไม่ต้องเอาเมนูไป ดูในโทรศัพท์ได้เลย หรือสั่งเสร็จก็ให้เขาส่งมาให้ได้", visual: { zh: "在手机上", th: "บนมือถือ", focus: "44% center" } }),
      line(takeoutRef, { role: "A", speaker: "白家月", pinyin: "tāmen jiā hái néng sòng wàimài", hanzi: "他们家还能送外卖？", reading: "Tāmen jiā hái néng sòng wàimài?", en: "They can deliver takeout too?", th: "ร้านนี้ส่งอาหารได้ด้วยเหรอ?", visual: { zh: "送外卖", th: "ส่งอาหาร", focus: "32% center" } }),
      line(takeoutRef, { role: "C", speaker: "王一雪", pinyin: "xiǎng chī shénme jiù diǎn shénme", hanzi: "对，现在很多饭馆都能送外卖，想吃什么就点什么。", reading: "Duì, xiànzài hěn duō fànguǎn dōu néng sòng wàimài, xiǎng chī shénme jiù diǎn shénme.", en: "Right — many restaurants deliver now, so you can order whatever you feel like.", th: "ใช่ ตอนนี้ร้านอาหารหลายร้านส่งได้ อยากกินอะไรก็สั่งอย่างนั้น", visual: { zh: "想吃什么就点什么", th: "อยากกินอะไรก็สั่งอันนั้น", focus: "46% center" } }),
      line(takeoutRef, { role: "A", speaker: "白家月", pinyin: "nà zhēn shì tài fāngbiàn le", hanzi: "那真是太方便了！", reading: "Nà zhēn shì tài fāngbiàn le!", en: "That’s so convenient!", th: "งั้นก็สะดวกมากเลย!", visual: { zh: "太方便了", th: "สะดวกมาก", focus: "34% center" } }),
    ],
    qte: {
      after: 0,
      prompt: { th: "ไป๋เจียเยว่ทำไมอยากมากินอีกครั้ง?", zh: "白家月为什么要再来吃一次？", en: "Why does Bai Jiayue want to come again?" },
      options: [
        { value: "鸡肉饭太好吃了", zh: "鸡肉饭太好吃了", pinyin: "jīròu fàn tài hǎochī le", th: "ข้าวไก่อร่อยมาก" },
        { value: "饭馆离她家很近", zh: "饭馆离她家很近", pinyin: "fànguǎn lí tā jiā hěn jìn", th: "ร้านใกล้บ้านเธอ" },
        { value: "想见服务员", zh: "想见服务员", pinyin: "xiǎng jiàn fúwùyuán", th: "อยากเจอพนักงาน" },
      ],
      correct: "鸡肉饭太好吃了",
      evidence: "白家月：这个鸡肉饭太好吃了。",
      evidenceTh: "ไป๋เจียเยว่: ข้าวไก่จานนี้อร่อยมาก",
      sourceRef: takeoutRef,
    },
    builder: {
      prompt: { th: "เรียงประโยคชื่อบท “อยากกินอะไรก็สั่งอันนั้น”", zh: "重组“想吃什么就点什么”句型", en: "Rebuild the 想…就… pattern" },
      answer: ["想", "吃", "什么", "就", "点", "什么"],
      tiles: ["点", "什么", "想", "就", "吃", "什么"],
      gloss: { 想: "อยาก", 吃: "กิน", 什么: "อะไร", 就: "ก็", 点: "สั่ง", 什么: "อันนั้น" },
      translationTh: "อยากกินอะไรก็สั่งอันนั้น",
      translationEn: "Order whatever you feel like.",
      evidence: "Text 3 · หน้าเล่ม 15",
      sourceRef: takeoutRef,
    },
  },
];

export const LESSON_HSK3_L2 = {
  id: "hsk3-l2",
  slug: "lesson-2",
  level: "hsk3",
  number: 2,
  featured: false,
  source: {
    title: "新HSK教程 3 · New HSK Course 3",
    lesson: "Lesson 2 · 你们想吃什么就点什么",
    printedPages: "10–18",
    pdfPages: "22–30",
    file: "hsk3.pdf",
    sourceRef,
  },
  sourceRef,
  title: {
    zh: "你们想吃什么就点什么",
    pinyin: "Nǐmen xiǎng chī shénme jiù diǎn shénme",
    en: "You can order whatever you feel like",
    thAid: "พวกเธออยากกินอะไรก็สั่งอันนั้นเลย",
  },
  summary: {
    zh: "在饭馆点菜、用餐和聊外卖，学习“又…又…”和疑问代词的任指用法。",
    en: "Ordering, dining, and chatting about delivery, learn 又…又… and the general-reference use of interrogative pronouns.",
    thAid: "สั่งอาหาร ทาน และคุยเรื่องเดลิเวอรี ฝึก 又…又… และสรรพนามคำถามแบบเจาะจง (任指)",
  },
  translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并谈论餐厅的菜品、服务和个人的饮食习惯。", en: "Be able to understand and talk about restaurant dishes, services, and personal eating habits.", thAid: "ฟังและพูดคุยเรื่องเมนู บริการ และนิสัยการกินของแต่ละคน", sourceRef: lessonHsk3L2SourceRef("10", "22") },
    { zh: "能听懂并使用疑问代词指代任何一个对象。", en: "Be able to understand and use interrogative pronouns to refer to any person or thing.", thAid: "เข้าใจและใช้สรรพนามคำถาม (什么/谁/哪儿/怎么) แบบแทนสิ่งใดก็ได้", sourceRef: lessonHsk3L2SourceRef("10", "22") },
    { zh: "了解中国人就餐时使用的餐具。", en: "Understand the tableware used by Chinese people when dining.", thAid: "รู้จักเครื่องใช้บนโต๊ะอาหารของคนจีน", sourceRef: lessonHsk3L2SourceRef("10", "22") },
  ],
  contents: [
    { number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "10", route: "/home/hsk3/lesson-2/preface/", sourceRef: lessonHsk3L2SourceRef("10", "22") },
    { number: "01", title: "在饭馆点菜", titleTh: "สั่งอาหารในร้าน", detail: "Text 1 · New Words 1–7", pages: "11–12", scene: 1, sourceRef: lessonHsk3L2SourceRef("11-12", "23-24") },
    { number: "02", title: "在饭馆吃饭", titleTh: "ทานอาหารในร้าน", detail: "Text 2 · New Words 8–15", pages: "12–14", scene: 2, sourceRef: lessonHsk3L2SourceRef("12-14", "24-26") },
    { number: "03", title: "边吃边聊", titleTh: "ทานไปคุยไป", detail: "Text 3 · New Words 16–18", pages: "14–15", scene: 3, sourceRef: lessonHsk3L2SourceRef("14-15", "26-27") },
    { number: "04", title: "综合练习与活动", titleTh: "แบบฝึกรวมและกิจกรรม", detail: "Text 4 · Exercises · Activity (source trail)", pages: "16–18", sourceRef: lessonHsk3L2SourceRef("16-18", "28-30") },
  ],
  vocabulary,
  grammarFocus: [
    { title: "并列复句“又…又…”", titleEn: "Coordinate Complex Sentence “又…又…”", explanationZh: "“又…又…”与形容词搭配使用，表示人或事物同时具有两个特点。", explanationEn: "“又…又…” is used before adjectives to indicate that a person or thing has two characteristics at the same time.", thAid: "โครงสร้าง 又 + คุณศัพท์1 + 又 + คุณศัพท์2 ใช้บอกว่ามีสองลักษณะพร้อมกัน", examples: ["我现在还真是又饿又渴。", "那个女孩儿又高又漂亮。", "这个饭馆的菜又便宜又好吃。"], sourceRef: lessonHsk3L2SourceRef("12", "24") },
    { title: "疑问代词的非疑问用法（2）", titleEn: "Non-Interrogative Use of Interrogative Pronouns (2)", explanationZh: "疑问代词“哪、哪儿、什么、谁、怎么”等可以表示任指，句中常用副词“都”与之呼应。", explanationEn: "Interrogative pronouns such as 哪, 什么, 谁, and 怎么 can express general reference, often echoing the adverb 都.", thAid: "สรรพนามคำถามแบบแทนทุกสิ่ง เช่น 谁=ใครก็ได้, 什么=อะไรก็ได้ มักใช้คู่กับ 都", examples: ["哪个菜都好吃。", "这次旅游，我去哪儿都可以。", "我下午有时间，你想什么时候来都没问题。"], sourceRef: lessonHsk3L2SourceRef("13", "25") },
    { title: "疑问代词的非疑问用法（3）", titleEn: "Non-Interrogative Use of Interrogative Pronouns (3)", explanationZh: "两个相同的疑问代词可以表示任指，前后呼应，指同一个人、同一件事、同一种方式等。", explanationEn: "Two identical interrogative pronouns echo each other to refer to the same person, thing, or manner.", thAid: "ใช้สรรพนามคำถามตัวเดียวกันซ้ำสองรอบ หมายถึงสิ่งเดียวกัน เช่น 想吃什么就点什么", examples: ["你们想吃什么就点什么。", "你觉得哪个好看就买哪个。", "你想去哪儿，我们就去哪儿。"], sourceRef: lessonHsk3L2SourceRef("15", "27") },
  ],
  characters,
  scenes,
};
