export const COPY = {
  th: {
    navigation: "เมนูและการใช้งาน",
    groupMenu: "เปิดเมนูเลือกกลุ่ม",
    closeGroupMenu: "ปิดเมนู",
    hubLabel: "ศูนย์เรียนรู้",
    routeLabels: { catalog: "เลือกบทเรียน", practice: "แบบทดสอบการพูด", "practice-exercise": "ทดสอบการพูด", preface: "ภาพรวมบทเรียน", contents: "สารบัญ", vocabulary: "คำศัพท์", home: "หน้าหลัก" },
    brand: "中文练习",
    group: "Zhōngwén Liànxí",
    home: "หน้าหลัก",
    report: "รายงานปัญหา",
    source: "เอกสารอ้างอิง",
    central: "ศูนย์กลาง",
    switchLanguage: "เปลี่ยนภาษา",
    skip: "ข้ามไปยังเนื้อหา",
    light: "เปลี่ยนเป็นโหมดสว่าง",
    dark: "เปลี่ยนเป็นโหมดมืด",
    heroTitle: "เรียนภาษาจีนแบบจำลอง\nฟัง อ่าน แล้วเข้าใจทันที",
    heroBody: "ฝึกภาษาจีนในสถานการณ์จริง ฟังเสียงเจ้าของภาษาพร้อมคำแปล และเล่นเกมทบทวนคำศัพท์แบบง่ายๆ สนุกๆ",
    heroBadge: "",
    heroTitleLine: "แบบฝึกภาษาจีน\nฟัง อ่าน และฝึกโต้ตอบ",
    heroSubLead: "ฝึกฟัง อ่าน และโต้ตอบภาษาจีน",
    heroSubExpl: "ผ่านสถานการณ์จำลองที่เข้าใจง่าย",
    benefitsLabel: "เส้นทางการฝึก",
    benefitOne: "คำศัพท์  •  บทสนทนาสั้น  •  ประโยคใช้จริง",
    benefitTwo: "อ่านพินอิน คำแปล และประโยคใช้จริง",
    benefitThree: "ฝึกโต้ตอบผ่านสถานการณ์จำลอง",
    ctaStart: "เริ่มฝึก",
    ctaLevel: "เลือกระดับ",
    vocabPill: "ดูคำศัพท์",
    start: "📚 เลือกระดับบทเรียน",
    startLessonNow: "🚀 เริ่มเลย (HSK 1 บทที่ 1)",
    browse: "ดูบทเรียนทั้งหมด",
    noStorage: "HSK 1–3 เลือกระดับแล้วเริ่มฝึกได้ทันที",
    howToLabel: "วิธีใช้:",
    howToStart: "กดเริ่มฝึก ฟังเสียง แล้วตอบคำถาม",
    registerKicker: "เริ่มเรียน",
    registerTitle: "กรุณากรอกชื่อคุณ",
    registerPrompt: "ใช้ชื่อ-นามสกุลของคุณ เพื่อเริ่มบทเรียน",
    registerNameLabel: "ชื่อ-นามสกุล",
    registerNamePlaceholder: "เช่น สมชาย ใจดี",
    registerNameRequired: "กรุณากรอกชื่อ-นามสกุล",
    registerContinue: "เริ่มเรียน",
    registerClose: "ปิดหน้าต่าง",
    levelPickerKicker: "เลือกเส้นทางการเรียน",
    levelPickerTitle: "คุณต้องการเริ่มจากระดับไหน",
    levelPickerBody: "เลือกระดับ HSK ที่เหมาะกับคุณ แล้วเลือกบทเรียนที่ต้องการฝึก",
    hsk1Title: "เริ่มต้นพื้นฐาน",
    hsk1Body: "คำศัพท์และบทสนทนาง่าย ๆ",
    hsk2Title: "ฝึกใช้ในชีวิตประจำวัน",
    hsk2Body: "สื่อสารในสถานการณ์ที่หลากหลายขึ้น",
    hsk3Title: "ต่อยอดการสื่อสาร",
    hsk3Body: "อ่านและตอบจากบทสนทนาที่ยาวขึ้น",
    startLearning: "เริ่มเรียน",
    previewContent: "ดูเนื้อหาก่อน",
    lessonEntry: "เข้าสู่บทเรียน",
    exerciseEntry: "ทำแบบทดสอบการพูด",
    practiceHubKicker: "แบบฝึกพูดตามแนว HSKK",
    practiceHubTitle: "เลือกแบบทดสอบการพูด",
    practiceHubBody: "เลือกกิจกรรมฝึกพูดสำหรับระดับ {level} เนื้อหาจะอ้างอิงจากบทเรียนในระดับเดียวกัน",
    repeatSentence: "ฟังแล้วพูดตาม",
    repeatSentenceZh: "听后重复",
    repeatSentenceMeta1: "10 ประโยค",
    repeatSentenceMeta2: "10 วินาที / ข้อ",
    imageDescriptionZh: "看图说话",
    imageDescriptionMeta1: "2 ภาพ",
    imageDescriptionMeta2: "2 นาที / ภาพ",
    questionResponseZh: "回答问题",
    questionResponseMeta1: "2 คำถาม",
    questionResponseMeta2: "2 นาที / ข้อ",
    practiceStart: "เริ่มทดสอบ",
    repeatSentenceDescription: "ฟังประโยคตัวอย่าง แล้วฝึกพูดภาษาจีนตาม",
    imageDescription: "บรรยายภาพ",
    imageDescriptionDescription: "ดูภาพจากบทเรียน แล้วฝึกบรรยายสิ่งที่เห็นเป็นภาษาจีน",
    questionResponse: "ตอบคำถาม",
    questionResponseDescription: "ฟังหรืออ่านคำถาม แล้วฝึกตอบด้วยภาษาจีน",
    practiceNotStarted: "ยังไม่เริ่ม",
    practiceComingSoon: "กำลังเตรียมแบบฝึกหัดนี้",
    practiceComingSoonBody: "เส้นทางพร้อมใช้งานแล้ว ส่วนระบบฝึกพูดจะเพิ่มในระยะถัดไป",
    backToPractice: "กลับไปเลือกแบบทดสอบ",
    practiceInstructions: "วิธีฝึก",
    practiceBegin: "เริ่มแบบฝึก",
    practiceProgress: "ข้อ {current} / {total}",
    listenExample: "ฟังตัวอย่าง",
    startSpeaking: "เริ่มพูด",
    stopSpeaking: "หยุด",
    submitAnswer: "ส่งคำตอบ",
    tryAgain: "ลองอีกครั้ง",
    nextExercise: "ข้อต่อไป",
    recognizedTranscript: "ระบบได้ยิน",
    contentAccuracy: "ความถูกต้องของเนื้อหา",
    completionMetric: "ความครบถ้วน",
    preliminaryResult: "ผลการฝึกเบื้องต้น",
    asrUnsupportedSelfReview: "เบราว์เซอร์นี้ไม่รองรับการถอดเสียงอัตโนมัติ คุณยังสามารถบันทึกและฟังคำตอบของตัวเองได้",
    mediaRecorderUnsupported: "เบราว์เซอร์นี้ไม่รองรับการบันทึกเสียง กรุณาใช้ Chrome หรือ Edge รุ่นปัจจุบัน",
    micPermissionDenied: "ไม่สามารถใช้ไมโครโฟนได้ กรุณาอนุญาตไมโครโฟนแล้วลองอีกครั้ง",
    insecureContextMessage: "ไม่สามารถใช้ไมโครโฟนบนการเชื่อมต่อ HTTP นี้ได้ กรุณาเปิดเว็บไซต์ผ่าน HTTPS",
    mediaDeviceUnavailable: "ไม่พบไมโครโฟนที่พร้อมใช้งาน กรุณาเชื่อมต่ออุปกรณ์แล้วลองอีกครั้ง",
    automaticEvaluationUnavailable: "ไม่สามารถประเมินคำตอบอัตโนมัติได้ในครั้งนี้ ระบบจะไม่ให้คะแนนความสามารถทางภาษาจากปัญหาทางเทคนิค",
    noSpeechDetected: "ยังไม่ได้ยินเสียงพูด ลองพูดอีกครั้งเมื่อไมโครโฟนพร้อม",
    asrTimeoutMessage: "หมดเวลารอฟังเสียง ลองอีกครั้งได้",
    asrErrorMessage: "ระบบถอดเสียงขัดข้อง คุณยังฝึกและฟังเสียงตัวเองได้",
    repeatSummaryTitle: "สรุปการฟังแล้วพูดตาม",
    averageContentAccuracy: "ความถูกต้องของเนื้อหาเฉลี่ย",
    averageCompletion: "ความครบถ้วนเฉลี่ย",
    overallDeterministicScore: "คะแนนแบบกำหนดกฎ",
    practiceAgain: "ฝึกอีกครั้ง",
    recordingPlayback: "ฟังคำตอบของคุณ",
    preparationTime: "เวลาเตรียมตัว",
    speakingTime: "เวลาพูด",
    speechContentAmount: "จำนวนอักษรจีนที่พูด",
    mentionedKeywords: "คำสำคัญที่กล่าวถึง",
    recommendedWords: "คำที่แนะนำให้ลองใช้",
    baselineScore: "คะแนนพื้นฐานจากข้อมูลที่ตรวจวัดได้",
    selfReviewResult: "ฝึกแบบทบทวนตนเอง (ไม่มีคะแนน)",
    practiceCompleted: "ฝึกครบแล้ว",
    repeatInstructionBody: "ฟังประโยคตัวอย่าง แล้วพูดตามภายใน 10 วินาที ระบบจะเปรียบเทียบเฉพาะเนื้อหาที่ถอดเสียงได้",
    imageInstruction: "ดูภาพแล้วพูดบรรยายสิ่งที่เห็นเป็นภาษาจีน",
    questionInstruction: "อ่านคำถามแล้วตอบเป็นภาษาจีน",
    secondsShort: "วินาที",
    minutesShort: "นาที",
    recordingStatus: "กำลังบันทึกเสียง",
    readyToSpeak: "พร้อมแล้ว กดเริ่มพูดได้เลย",
    processingSpeech: "กำลังเตรียมผลการฝึก",
    transcriptUnavailable: "ไม่มีข้อความถอดเสียง",
    correctStatus: "พูดถูกต้อง",
    closeStatus: "เกือบถูก",
    retryStatus: "ลองอีกครั้ง",
    completedCount: "ทำเสร็จ",
    keywordCoverage: "คำสำคัญที่ครอบคลุม",
    responseDuration: "ระยะเวลาคำตอบ",
    finishSpeaking: "พูดเสร็จแล้ว",
    playRecording: "เล่นเสียงที่บันทึก",
    shelfKicker: "ครอบคลุม HSK 1–3",
    shelfTitle: "สามารถเลือกระดับที่ต้องการได้เลย",
    ready: "พร้อมเรียนแล้ว",
    awaiting: "กำลังเตรียมเนื้อหา",
    sourceOnly: "เนื้อหา คำศัพท์ และแบบฝึกหัดอ้างอิงจาก New HSK 1–3",
    frontMatterKicker: "ข้อมูลบทเรียน",
    prefaceTitle: "ภาพรวมและเป้าหมายบทเรียน",
    prefaceBody: "เรียนผ่านสถานการณ์จริง เช่น ซื้อของ สั่งอาหาร และเดินทาง เพื่อฝึกฟัง อ่าน และสนทนาแบบเป็นธรรมชาติ",
    objectiveTitle: "เป้าหมายการเรียนรู้",
    vocabularyTitle: "คำศัพท์ใหม่ในบทนี้",
    vocabularyBody: "รวมคำศัพท์ที่สำคัญทั้งหมด คุณสามารถกดคำไหนก็ได้เพื่อฟังเสียงอ่านภาษาจีน",
    bookSourceNote: "อ้างอิงจาก New HSK (Text 1–3, New Words และ Objectives)",
    openPreface: "🎯 ดูเป้าหมายบทเรียน",
    openContents: "📑 ดูสารบัญ",
    openVocabulary: "🔤 ดูคำศัพท์",
    startReading: "📖 เริ่มบทที่ 1",
    previousPage: "ก่อนหน้า",
    nextPage: "ถัดไป",
    printedPage: "หน้าเรียน",
    catalogKicker: "บทเรียนทั้งหมด ({count} บท)",
    catalogTitle: "เลือกบทเรียนและสถานการณ์",
    catalogBody: "เรียนภาษาจีนผ่านสถานการณ์จำลองแบบง่ายๆ แต่ละบทมีเสียง ฟัง-ตอบ และเกมเรียงประโยค",
    enterScene: "📖 เข้าเรียนบทนี้",
    readLesson: "▶ เริ่มจากฉากที่ 1",
    back: "กลับ",
    roleMap: "ตัวละครในฉาก",
    beforeReading: "🎬 เรื่องราวก่อนเริ่ม",
    beforeReadingBody: "ดูว่าใครคุยกับใคร และเรื่องเกิดขึ้นที่ไหน ก่อนเริ่มบทสนทนา",
    sceneImage: "ภาพสถานการณ์",
    scenePicker: "เลือกฉาก",
    enlargeImage: "🔍 ดูภาพใหญ่",
    closeImage: "ปิดภาพ",
    role: "บทบาท",
    voiceCast: "เสียงพากย์",
    stage: "ฉาก",
    sourcePage: "หน้าหนังสือ",
    begin: "เริ่มบทสนทนา",
    previous: "ก่อนหน้า",
    next: "ถัดไป",
    finishScene: "จบฉาก",
    continueScene: "ไปฉากต่อไป",
    restart: "เริ่มใหม่",
    completed: "🎉 ทำได้ดีมาก! คุณจบฉากนี้แล้ว",
    completedBody: "คุณผ่านการเช็กความเข้าใจและเรียงประโยคภาษาจีนได้สำเร็จแล้ว",
    bonusGames: "🎮 เล่นเกมทบทวน",
    qte: "⚡ คำถามสั้น",
    seconds: "วินาที",
    pause: "หยุดชั่วคราว",
    resume: "เล่นต่อ",
    correct: "✅ ถูกต้อง!",
    wrong: "❌ ยังไม่ถูก ลองฟังอีกครั้ง",
    timeout: "⏰ หมดเวลา! ดูคำตอบด้านล่างแล้วลองใหม่ได้",
    evidence: "📖 ข้อความอ้างอิง:",
    retry: "ลองอีกครั้ง",
    continue: "เรียนต่อ",
    qteRestart: "เริ่มใหม่",
    builder: "🧩 เรียงประโยคภาษาจีน",
    builderHint: "แตะคำศัพท์ด้านล่างตามลำดับให้เป็นประโยคที่ถูกต้อง",
    check: "✅ ตรวจคำตอบ",
    undo: "↩️ ลบคำสุดท้าย",
    reset: "🔄 ล้างใหม่",
    builderCorrect: "🎉 ถูกต้อง! ประโยคนี้สมบูรณ์แล้ว",
    builderWrong: "⚠️ ลำดับยังไม่ถูก ลองสังเกตว่าใครทำอะไรที่ไหน แล้วเรียงใหม่อีกครั้ง",
    currentLine: "ประโยคปัจจุบัน",
    thaiMeaning: "คำแปลไทย",
    translationOn: "เปิดคำแปลไทย",
    translationOff: "ปิดคำแปลไทย",
    speak: "🔊 ฟังเสียงภาษาจีน",
    timerOn: "เปิดจับเวลา (15 วิ)",
    timerOff: "ไม่ใช้เวลา",
    exitReader: "กลับหน้าบทเรียน",
    buyer: "ลูกค้า / ผู้ซื้อ",
    educationalUnavailable: "ยังไม่มีคำแปลภาษาอังกฤษที่ตรวจสอบแล้ว",
    frontMatterNavigation: "เมนูบทเรียน",
    marketLabel: "สถานการณ์จำลอง",
    marketStartLine1: "เริ่ม",
    marketStartLine2: "บทเรียน",
    seller: "พนักงานขาย",
    visualMemory: "ภาพสถานการณ์",
    about: "เกี่ยวกับโปรเจกต์",
    aboutClose: "ปิด",
    objectivesLabel: "เป้าหมาย",
    languageFocusLabel: "ไวยากรณ์",
    vocabularyLabel: "คำศัพท์",
    lessonLabel: "บทที่",
    sceneLabel: "ฉากที่",
    newWordsLabel: "คำศัพท์ใหม่",
    sceneCompleteLabel: "จบฉากที่",
    hskCourseLabel: "หลักสูตร New HSK",
    footerTitle: "中文练习 (Zhōngwén Liànxí) - เรียนภาษาจีนแบบโต้ตอบ",
    footerGroupInfo: "เรียนคำศัพท์และบทสนทนา HSK 1–3 ผ่านสถานการณ์จริง พร้อมเสียงเจ้าของภาษา เกมทบทวน และโหมดสวมบทบาท",
    footerCourse: "หลักสูตร New HSK ระดับ 1–3",
    footerMembersTitle: "ทีมพัฒนา",
    footerMember1: "1. ศุภกร เปรมมะโน (โก้)",
    footerMember2: "2. พิสิษฐ์พงษ์ บุญเรือง (อาร์ม)",
    footerMember3: "3. เพชรระพีพัฒน์ นันตรัตน์ (เพชร)",
    autoplayBegin: "▶ เล่นอัตโนมัติ",
    manualBegin: "👆 อ่านเองทีละประโยค",
    autoplayHint: "ระบบจะเล่นเสียงและเลื่อนประโยคให้อัตโนมัติ",
    storyPlaybackControls: "ตัวควบคุมการเล่น",
    playbackPlaying: "กำลังเล่น...",
    playbackPaused: "หยุดแล้ว",
    playbackChallenge: "กรุณาตอบคำถามให้เสร็จก่อนเรียนต่อ",
    playbackSoundBlocked: "เบราว์เซอร์ปิดเสียงไว้ กดเพื่อเปิดเสียง",
    lineProgress: "ประโยคที่",
    sceneProgress: "ความคืบหน้า",
    nowSpeaking: "กำลังพูด",
    upNext: "ต่อไป",
    previousLine: "ก่อนหน้า",
    nextLine: "ถัดไป",
    pausePlayback: "หยุดเสียง",
    resumePlayback: "เล่นต่อ",
    replayLine: "ฟังซ้ำ",
    soundOn: "เปิดเสียง",
    soundOff: "ปิดเสียง",
    enableSound: "เปิดเสียง",
    playbackSpeed: "ความเร็วเสียง",
    showPlaybackDetails: "แสดงตัวควบคุม",
    hidePlaybackDetails: "ซ่อนตัวควบคุม",
    rolePickerTitle: "เลือกบทบาท",
    rolePickerBody: "เลือกตัวละครที่คุณอยากสวมบทบาท แล้วเริ่มบทสนทนาแบบ 3D",
    roleplayRole: "บทบาท",
    rolePickerNote: "เลือกบทบาทแล้วสลับ 3D/2D ได้ตลอด · กด Spacebar หรือ F เพื่อเล่น/หยุด",
    cancel: "ยกเลิก / กลับ",
    roleplayWait: "กดเล่นเพื่อเริ่มบทสนทนา",
    youLabel: "คุณ",
    roleplayView: "โหมดสวมบทบาท",
    dragToLook: "คลิกหรือเลื่อนเมาส์เพื่อหมุนมุมมอง 3D",
    modeLabel: "โหมดมุมมอง",
    mode3d: "มุมมอง 3D",
    mode2d: "มุมมอง 2D",
    exitRoleplay: "ออกจากโหมดสวมบทบาท",
    pressF: "กด F หรือ Space เพื่อเล่น/หยุด",
    guide: "วิธีใช้",
    dontShowAgain: "ไม่ต้องแสดงอีก",
    step: "ขั้นที่",
    tips: "💡 เคล็ดลับ",
  },
  zh: {
    navigation: "菜单和操作",
    groupMenu: "打开菜单",
    closeGroupMenu: "关闭菜单",
    hubLabel: "学习中心",
    routeLabels: { catalog: "选择课程", practice: "口语练习", "practice-exercise": "练习", preface: "课程简介", contents: "目录", vocabulary: "生词", home: "首页" },
    brand: "中文练习",
    group: "Zhōngwén Liànxí",
    home: "首页",
    report: "问题反馈",
    source: "学习资料",
    central: "中心",
    switchLanguage: "切换语言",
    skip: "跳过到内容",
    light: "切换浅色模式",
    dark: "切换深色模式",
    heroTitle: "用真实情境学中文\n听、看、说，一次学会",
    heroBody: "通过真实场景练习中文，听母语发音，查看中文和释义，轻松完成学习与复习。",
    heroBadge: "",
    heroTitleLine: "中文练习\n听、读与互动对话",
    heroSubLead: "ฝึกฟัง อ่าน และโต้ตอบภาษาจีน",
    heroSubExpl: "ผ่านสถานการณ์จำลองที่เข้าใจง่าย",
    benefitsLabel: "练习路径",
    benefitOne: "คำศัพท์  •  บทสนทนาสั้น  •  ประโยคใช้จริง",
    benefitTwo: "阅读带拼音和翻译的中文，理解词汇和句型",
    benefitThree: "选择角色，在模拟对话中练习互动回应",
    ctaStart: "开始练习",
    ctaLevel: "选择等级",
    vocabPill: "看生词",
    start: "📚 选择课程等级",
    startLessonNow: "🚀 立即开始（HSK 1 第 1 课）",
    browse: "查看全部课程",
    noStorage: "HSK 1–3 · 选择等级即可开始练习",
    howToLabel: "使用方法：",
    howToStart: "点击开始，听声音，然后回答问题",
    registerKicker: "开始学习",
    registerTitle: "请输入你的姓名",
    registerPrompt: "填写姓名后开始课程",
    registerNameLabel: "姓名",
    registerNamePlaceholder: "例如：王小明",
    registerNameRequired: "请输入姓名",
    registerContinue: "开始学习",
    registerClose: "关闭窗口",
    levelPickerKicker: "选择学习路径",
    levelPickerTitle: "你想从哪个等级开始？",
    levelPickerBody: "选择适合你的 HSK 等级，再挑选想练习的课程。",
    hsk1Title: "基础入门",
    hsk1Body: "简单词语和日常对话",
    hsk2Title: "日常交流",
    hsk2Body: "练习更多生活场景",
    hsk3Title: "提升表达",
    hsk3Body: "阅读更长的对话并回答",
    startLearning: "开始学习",
    previewContent: "先看内容",
    lessonEntry: "进入课程",
    exerciseEntry: "练习",
    practiceHubKicker: "HSKK 启发式口语练习",
    practiceHubTitle: "选择练习",
    practiceHubBody: "选择 {level} 口语练习，内容引用同级课程资料。",
    repeatSentence: "听后复述",
    repeatSentenceZh: "听后重复",
    repeatSentenceMeta1: "10 个句子",
    repeatSentenceMeta2: "10 秒 / 题",
    imageDescriptionZh: "看图说话",
    imageDescriptionMeta1: "2 张图片",
    imageDescriptionMeta2: "2 分钟 / 图",
    questionResponseZh: "回答问题",
    questionResponseMeta1: "2 个问题",
    questionResponseMeta2: "2 分钟 / 题",
    practiceStart: "开始练习",
    repeatSentenceDescription: "听示范句，然后练习用中文复述。",
    imageDescription: "看图说话",
    imageDescriptionDescription: "观察课程图片，并用中文描述看到的内容。",
    questionResponse: "回答问题",
    questionResponseDescription: "听或阅读问题，然后用中文回答。",
    practiceNotStarted: "未开始",
    practiceComingSoon: "本练习正在准备中",
    practiceComingSoonBody: "练习路径已经可用，口语引擎将在下一阶段加入。",
    backToPractice: "返回练习选择",
    practiceInstructions: "练习说明",
    practiceBegin: "开始练习",
    practiceProgress: "第 {current} / {total} 题",
    listenExample: "听示范",
    startSpeaking: "开始说话",
    stopSpeaking: "停止",
    submitAnswer: "提交回答",
    tryAgain: "再试一次",
    nextExercise: "下一题",
    recognizedTranscript: "系统识别到",
    contentAccuracy: "内容准确度",
    completionMetric: "句子完整度",
    preliminaryResult: "初步练习结果",
    asrUnsupportedSelfReview: "此浏览器不支持自动语音转写。你仍可录音并回听自己的回答。",
    mediaRecorderUnsupported: "此浏览器不支持录音，请使用最新版 Chrome 或 Edge。",
    micPermissionDenied: "无法使用麦克风。请允许麦克风权限后重试。",
    insecureContextMessage: "此 HTTP 连接无法使用麦克风，请通过 HTTPS 打开网站。",
    mediaDeviceUnavailable: "未找到可用的麦克风，请连接设备后重试。",
    automaticEvaluationUnavailable: "本次无法进行自动评估。系统不会因技术问题给语言能力计零分。",
    noSpeechDetected: "没有检测到语音，请在麦克风就绪后重试。",
    asrTimeoutMessage: "等待语音超时，可以重新尝试。",
    asrErrorMessage: "自动转写暂时不可用，你仍可练习并回听录音。",
    repeatSummaryTitle: "听后复述总结",
    averageContentAccuracy: "平均内容准确度",
    averageCompletion: "平均完整度",
    overallDeterministicScore: "规则评分",
    practiceAgain: "再练一次",
    recordingPlayback: "回听你的回答",
    preparationTime: "准备时间",
    speakingTime: "说话时间",
    speechContentAmount: "识别到的汉字数",
    mentionedKeywords: "提到的关键词",
    recommendedWords: "建议尝试的词语",
    baselineScore: "基于可测数据的基础分",
    selfReviewResult: "自我复习模式（不计分）",
    practiceCompleted: "练习完成",
    repeatInstructionBody: "听示范句，并在 10 秒内复述。系统只比较自动转写出的内容。",
    imageInstruction: "看图并用中文描述你看到的内容",
    questionInstruction: "阅读问题并用中文回答",
    secondsShort: "秒",
    minutesShort: "分钟",
    recordingStatus: "正在录音",
    readyToSpeak: "准备好了，点击开始说话",
    processingSpeech: "正在生成练习结果",
    transcriptUnavailable: "没有自动转写文本",
    correctStatus: "内容正确",
    closeStatus: "很接近",
    retryStatus: "再试一次",
    completedCount: "已完成",
    keywordCoverage: "关键词覆盖",
    responseDuration: "回答时长",
    finishSpeaking: "说完了",
    playRecording: "播放录音",
    shelfKicker: "涵盖 HSK 1–3",
    shelfTitle: "选择想学的等级",
    ready: "可以开始学习",
    awaiting: "正在准备内容",
    sourceOnly: "内容、词汇和练习都参考 New HSK 1–3",
    frontMatterKicker: "课程信息",
    prefaceTitle: "课程简介和目标",
    prefaceBody: "通过真实场景学习，如买东西、点餐和旅行，练习听说和阅读。",
    objectiveTitle: "学习目标",
    vocabularyTitle: "本课生词",
    vocabularyBody: "这里是本课重点词汇，点击任意词都可以听中文发音。",
    bookSourceNote: "参考教材 New HSK（Text 1–3, New Words 和 Objectives）",
    openPreface: "🎯 查看课程目标",
    openContents: "📑 查看目录",
    openVocabulary: "🔤 查看生词",
    startReading: "📖 从第 1 场景开始",
    previousPage: "上一页",
    nextPage: "下一页",
    printedPage: "教材页",
    catalogKicker: "全部课程（{count} 课）",
    catalogTitle: "选择课程和场景",
    catalogBody: "通过简洁的情境学习中文，每个场景都配有声音、理解题和组句练习。",
    enterScene: "📖 进入这个场景",
    readLesson: "▶ 从第 1 场景开始",
    back: "返回",
    roleMap: "场景角色",
    beforeReading: "🎬 开始前先看准备",
    beforeReadingBody: "先确认谁在说话、发生在什么地方，再开始对话。",
    sceneImage: "场景图",
    scenePicker: "选择场景",
    enlargeImage: "🔍 看大图",
    closeImage: "关闭",
    role: "角色",
    voiceCast: "声音",
    stage: "场景",
    sourcePage: "教材页码",
    begin: "开始对话",
    previous: "上一句",
    next: "下一句",
    finishScene: "完成场景",
    continueScene: "进入下一场",
    restart: "重来",
    completed: "🎉 很好！你完成这个场景了",
    completedBody: "你已经完成理解检查，并成功拼出中文句子。",
    bonusGames: "🎮 玩小游戏复习",
    qte: "⚡ 快速理解题",
    seconds: "秒",
    pause: "暂停",
    resume: "继续",
    correct: "✅ 正确！",
    wrong: "❌ 不对，再看看",
    timeout: "⏰ 时间到！看下面的提示后再试一次",
    evidence: "📖 参考句子：",
    retry: "再试一次",
    continue: "继续学习",
    qteRestart: "重新开始",
    builder: "🧩 组句练习",
    builderHint: "按顺序点击下方词语，拼成正确句子",
    check: "✅ 检查答案",
    undo: "↩️ 删掉上一个",
    reset: "🔄 重置",
    builderCorrect: "🎉 正确！这句很完整",
    builderWrong: "⚠️ 顺序还不对，再看看谁在做什么，再试一次",
    currentLine: "当前句子",
    thaiMeaning: "释义",
    translationOn: "开启释义",
    translationOff: "关闭释义",
    speak: "🔊 播放中文发音",
    timerOn: "打开计时（15 秒）",
    timerOff: "不计时",
    exitReader: "返回课程列表",
    buyer: "顾客",
    educationalUnavailable: "暂无更多参考释义",
    frontMatterNavigation: "课程导航",
    marketLabel: "情境模拟",
    marketStartLine1: "开始",
    marketStartLine2: "课程",
    seller: "售货员",
    visualMemory: "情境图",
    about: "关于项目",
    aboutClose: "关闭",
    objectivesLabel: "目标",
    languageFocusLabel: "语法",
    vocabularyLabel: "生词",
    lessonLabel: "第",
    sceneLabel: "场景",
    newWordsLabel: "生词",
    sceneCompleteLabel: "已完成场景",
    hskCourseLabel: "新 HSK 课程",
    footerTitle: "中文练习 (Zhōngwén Liànxí) - 中文学习与角色扮演",
    footerGroupInfo: "用真实场景、语音和小游戏学习 HSK 1–3 词汇，轻松上手中文。",
    footerCourse: "新 HSK 1–3 课程",
    footerMembersTitle: "开发团队",
    footerMember1: "1. Supakorn Premmanon (Ko)",
    footerMember2: "2. Pitsitpong Boonrueang (Arm)",
    footerMember3: "3. Phetrapeepat Nantarat (Phet)",
    autoplayBegin: "▶ 自动播放",
    manualBegin: "👆 手动阅读",
    autoplayHint: "系统会自动播放声音并滚动到下一句",
    storyPlaybackControls: "播放控制",
    playbackPlaying: "正在播放...",
    playbackPaused: "已暂停",
    playbackChallenge: "请先完成题目，然后继续学习",
    playbackSoundBlocked: "浏览器拦截了音频，点这里打开",
    lineProgress: "当前句子",
    sceneProgress: "学习进度",
    nowSpeaking: "正在说话",
    upNext: "下一句",
    previousLine: "上一句",
    nextLine: "下一句",
    pausePlayback: "暂停播放",
    resumePlayback: "继续播放",
    replayLine: "重听",
    soundOn: "打开声音",
    soundOff: "关闭声音",
    enableSound: "打开声音",
    playbackSpeed: "播放速度",
    showPlaybackDetails: "显示控制",
    hidePlaybackDetails: "隐藏控制",
    rolePickerTitle: "选择角色",
    rolePickerBody: "选择你想扮演的角色，进入 3D 对话体验。",
    roleplayRole: "角色",
    rolePickerNote: "选择角色后可随时切换 3D/2D · 按空格或 F 播放/暂停",
    cancel: "取消 / 返回",
    roleplayWait: "点播放开始对话",
    youLabel: "你",
    roleplayView: "角色扮演视角",
    dragToLook: "拖动鼠标查看 3D 场景",
    modeLabel: "视角模式",
    mode3d: "3D 视角",
    mode2d: "2D 视角",
    exitRoleplay: "退出角色扮演",
    pressF: "按 F 或空格播放/暂停",
    guide: "使用说明",
    dontShowAgain: "不再显示",
    step: "第",
    tips: "💡 小提示",
  },
  en: {
    navigation: "Menu & controls",
    groupMenu: "Open group menu",
    closeGroupMenu: "Close menu",
    hubLabel: "Learning hub",
    routeLabels: { catalog: "Choose lesson", practice: "Speaking practice", "practice-exercise": "Exercise", preface: "Lesson overview", contents: "Contents", vocabulary: "Vocabulary", home: "Home" },
    brand: "中文练习",
    group: "Zhōngwén Liànxí",
    home: "Home",
    report: "Report",
    source: "Study source",
    central: "Center",
    switchLanguage: "Switch language",
    skip: "Skip to content",
    light: "Switch to light mode",
    dark: "Switch to dark mode",
    heroTitle: "Learn Chinese in real situations\nListen, read, and understand faster",
    heroBody: "Practice everyday Chinese with native audio, clear translations, and short review games that are easy and fun.",
    heroBadge: "",
    heroTitleLine: "Practice Chinese\nListen, read, and respond",
    heroSubLead: "ฝึกฟัง อ่าน และโต้ตอบภาษาจีน",
    heroSubExpl: "ผ่านสถานการณ์จำลองที่เข้าใจง่าย",
    benefitsLabel: "Your practice path",
    benefitOne: "คำศัพท์  •  บทสนทนาสั้น  •  ประโยคใช้จริง",
    benefitTwo: "Read Chinese with pinyin and translations to understand vocabulary and sentence patterns",
    benefitThree: "Choose a role and practice responding in simulated conversations",
    ctaStart: "Start practicing",
    ctaLevel: "Choose level",
    vocabPill: "View Words",
    start: "📚 Choose your level",
    startLessonNow: "🚀 Start now (HSK 1 Lesson 1)",
    browse: "Browse all lessons",
    noStorage: "HSK 1–3 · Choose your level and start practicing right away",
    howToLabel: "How it works:",
    howToStart: "Start a lesson, listen, then answer",
    registerKicker: "Start learning",
    registerTitle: "Please enter your name",
    registerPrompt: "Enter your name to begin the lesson",
    registerNameLabel: "Name",
    registerNamePlaceholder: "e.g. Alex Chen",
    registerNameRequired: "Please enter your name",
    registerContinue: "Start lesson",
    registerClose: "Close dialog",
    levelPickerKicker: "Choose your path",
    levelPickerTitle: "Which level would you like to start with?",
    levelPickerBody: "Choose an HSK level, then pick a lesson to practice.",
    hsk1Title: "Start with the basics",
    hsk1Body: "Simple words and everyday dialogue",
    hsk2Title: "Everyday communication",
    hsk2Body: "Practice a wider range of situations",
    hsk3Title: "Build confidence",
    hsk3Body: "Read longer dialogue and respond",
    startLearning: "Start learning",
    previewContent: "Preview content",
    lessonEntry: "Enter lessons",
    exerciseEntry: "Practice exercises",
    practiceHubKicker: "HSKK-inspired speaking practice",
    practiceHubTitle: "Choose an exercise",
    practiceHubBody: "Choose a {level} speaking activity built from lessons at the same level.",
    repeatSentence: "Repeat a sentence",
    repeatSentenceZh: "听后重复",
    repeatSentenceMeta1: "10 sentences",
    repeatSentenceMeta2: "10s / sentence",
    imageDescriptionZh: "看图说话",
    imageDescriptionMeta1: "2 images",
    imageDescriptionMeta2: "2 mins / image",
    questionResponseZh: "回答问题",
    questionResponseMeta1: "2 questions",
    questionResponseMeta2: "2 mins / question",
    practiceStart: "Start practice",
    repeatSentenceDescription: "Listen to a model sentence, then practise saying it in Chinese.",
    imageDescription: "Describe an image",
    imageDescriptionDescription: "Look at a lesson image and describe what you see in Chinese.",
    questionResponse: "Answer a question",
    questionResponseDescription: "Listen to or read a question, then answer it in Chinese.",
    practiceNotStarted: "Not started",
    practiceComingSoon: "This exercise is being prepared",
    practiceComingSoonBody: "The route is ready. The speaking engine will be added in a later phase.",
    backToPractice: "Back to practice",
    practiceInstructions: "How to practice",
    practiceBegin: "Start exercise",
    practiceProgress: "Item {current} / {total}",
    listenExample: "Listen to example",
    startSpeaking: "Start speaking",
    stopSpeaking: "Stop",
    submitAnswer: "Submit answer",
    tryAgain: "Try again",
    nextExercise: "Next item",
    recognizedTranscript: "Recognized transcript",
    contentAccuracy: "Content accuracy",
    completionMetric: "Sentence completion",
    preliminaryResult: "Preliminary practice result",
    asrUnsupportedSelfReview: "This browser does not support automatic transcription. You can still record and review your answer.",
    mediaRecorderUnsupported: "This browser cannot record audio. Please use a current version of Chrome or Edge.",
    micPermissionDenied: "The microphone is unavailable. Allow microphone access, then try again.",
    insecureContextMessage: "The microphone cannot be used over this HTTP connection. Open the site through HTTPS.",
    mediaDeviceUnavailable: "No available microphone was found. Connect a device, then try again.",
    automaticEvaluationUnavailable: "Automatic evaluation was unavailable for this attempt. A technical capture problem will not be scored as a language failure.",
    noSpeechDetected: "No speech was detected. Try again when the microphone is ready.",
    asrTimeoutMessage: "Listening timed out. You can try again.",
    asrErrorMessage: "Automatic transcription is unavailable. You can still practice and review your recording.",
    repeatSummaryTitle: "Repeat sentence summary",
    averageContentAccuracy: "Average content accuracy",
    averageCompletion: "Average completion",
    overallDeterministicScore: "Rule-based score",
    practiceAgain: "Practice again",
    recordingPlayback: "Review your answer",
    preparationTime: "Preparation time",
    speakingTime: "Speaking time",
    speechContentAmount: "Recognized Chinese characters",
    mentionedKeywords: "Keywords mentioned",
    recommendedWords: "Words to try next",
    baselineScore: "Baseline score from measurable signals",
    selfReviewResult: "Self-review practice (unscored)",
    practiceCompleted: "Practice complete",
    repeatInstructionBody: "Listen to the example, then repeat it within 10 seconds. The system compares only recognized content.",
    imageInstruction: "Look at the image and describe what you see in Chinese",
    questionInstruction: "Read the question and answer in Chinese",
    secondsShort: "seconds",
    minutesShort: "minutes",
    recordingStatus: "Recording",
    readyToSpeak: "Ready. Start speaking when you are comfortable.",
    processingSpeech: "Preparing your practice result",
    transcriptUnavailable: "No automatic transcript",
    correctStatus: "Content correct",
    closeStatus: "Almost there",
    retryStatus: "Try again",
    completedCount: "Completed",
    keywordCoverage: "Keyword coverage",
    responseDuration: "Response duration",
    finishSpeaking: "Finished speaking",
    playRecording: "Play recording",
    shelfKicker: "Covers HSK 1–3",
    shelfTitle: "Choose a learning level",
    ready: "Ready to learn",
    awaiting: "Preparing content",
    sourceOnly: "Lessons and vocabulary are based on New HSK 1–3",
    frontMatterKicker: "Lesson info",
    prefaceTitle: "Lesson overview and goals",
    prefaceBody: "Learn through real-life scenes like shopping, ordering food, and travel to practice natural conversation.",
    objectiveTitle: "Learning goals",
    vocabularyTitle: "New words in this lesson",
    vocabularyBody: "A list of key words. Tap any word to hear native Chinese pronunciation.",
    bookSourceNote: "Based on New HSK (Text 1–3, New Words, and Objectives)",
    openPreface: "🎯 View lesson goals",
    openContents: "📑 View contents",
    openVocabulary: "🔤 View vocabulary",
    startReading: "📖 Start lesson 1",
    previousPage: "Previous",
    nextPage: "Next",
    printedPage: "Textbook page",
    catalogKicker: "All lessons ({count})",
    catalogTitle: "Choose a lesson and scene",
    catalogBody: "Learn through simple simulated situations. Each scene includes audio, quick checks, and sentence practice.",
    enterScene: "📖 Enter this scene",
    readLesson: "▶ Start from scene 1",
    back: "Back",
    roleMap: "Characters in scene",
    beforeReading: "🎬 Scene preview",
    beforeReadingBody: "Check who is speaking and where the scene is happening before you start.",
    sceneImage: "Scene image",
    scenePicker: "Choose a scene",
    enlargeImage: "🔍 View larger",
    closeImage: "Close",
    role: "Role",
    voiceCast: "Voice cast",
    stage: "Scene",
    sourcePage: "Book page",
    begin: "Start dialogue",
    previous: "Previous",
    next: "Next",
    finishScene: "Finish scene",
    continueScene: "Go to next scene",
    restart: "Restart",
    completed: "🎉 Nice job! You completed this scene",
    completedBody: "You finished the check and built the sentence correctly.",
    bonusGames: "🎮 Play review games",
    qte: "⚡ Quick quiz",
    seconds: "seconds",
    pause: "Pause",
    resume: "Resume",
    correct: "✅ Correct!",
    wrong: "❌ Not quite. Try again.",
    timeout: "⏰ Time's up! Review the example and try again.",
    evidence: "📖 Reference sentence:",
    retry: "Try again",
    continue: "Continue",
    qteRestart: "Restart",
    builder: "🧩 Sentence builder",
    builderHint: "Tap the words in order to make the correct sentence",
    check: "✅ Check answer",
    undo: "↩️ Undo",
    reset: "🔄 Reset",
    builderCorrect: "🎉 Correct! The sentence is complete.",
    builderWrong: "⚠️ Not quite. Look at who does what and try again.",
    currentLine: "Current line",
    thaiMeaning: "Translation",
    translationOn: "Show translation",
    translationOff: "Hide translation",
    speak: "🔊 Play Chinese audio",
    timerOn: "Use timer (15s)",
    timerOff: "No timer",
    exitReader: "Back to lessons",
    buyer: "Customer",
    educationalUnavailable: "No verified translation is available yet.",
    frontMatterNavigation: "Lesson nav",
    marketLabel: "Scenario",
    marketStartLine1: "Start",
    marketStartLine2: "lesson",
    seller: "Seller",
    visualMemory: "Scene image",
    about: "About project",
    aboutClose: "Close",
    objectivesLabel: "Goals",
    languageFocusLabel: "Grammar",
    vocabularyLabel: "Vocabulary",
    lessonLabel: "Lesson",
    sceneLabel: "Scene",
    newWordsLabel: "New words",
    sceneCompleteLabel: "Scene complete",
    hskCourseLabel: "New HSK course",
    footerTitle: "Zhōngwén Liànxí (中文练习) - Interactive Chinese learning",
    footerGroupInfo: "Learn HSK vocabulary through real-life scenes, clear audio, and short review games.",
    footerCourse: "New HSK Levels 1–3",
    footerMembersTitle: "Development team",
    footerMember1: "1. Supakorn Premmanon (Ko)",
    footerMember2: "2. Pitsitpong Boonrueang (Arm)",
    footerMember3: "3. Phetrapeepat Nantarat (Phet)",
    autoplayBegin: "▶ Autoplay",
    manualBegin: "👆 Read by yourself",
    autoplayHint: "Audio plays automatically and the app moves to the next line.",
    storyPlaybackControls: "Playback controls",
    playbackPlaying: "Playing...",
    playbackPaused: "Paused",
    playbackChallenge: "Please finish the challenge before continuing.",
    playbackSoundBlocked: "Audio is blocked by the browser. Click to enable it.",
    lineProgress: "Line",
    sceneProgress: "Progress",
    nowSpeaking: "Speaking now",
    upNext: "Next",
    previousLine: "Previous",
    nextLine: "Next",
    pausePlayback: "Pause audio",
    resumePlayback: "Resume audio",
    replayLine: "Replay",
    soundOn: "Sound on",
    soundOff: "Sound off",
    enableSound: "Enable sound",
    playbackSpeed: "Playback speed",
    showPlaybackDetails: "Show controls",
    hidePlaybackDetails: "Hide controls",
    rolePickerTitle: "Choose a role",
    rolePickerBody: "Pick a character to roleplay and enter a 3D dialogue scene.",
    roleplayRole: "Role",
    rolePickerNote: "Choose a role and switch between 3D/2D anytime · Press Space or F to play or pause",
    cancel: "Cancel / back",
    roleplayWait: "Press play to start",
    youLabel: "You",
    roleplayView: "Roleplay view",
    dragToLook: "Click or drag to look around in 3D",
    modeLabel: "View mode",
    mode3d: "3D view",
    mode2d: "2D view",
    exitRoleplay: "Exit roleplay",
    pressF: "Press F or Space to play/pause",
    guide: "Guide",
    dontShowAgain: "Do not show again",
    step: "Step",
    tips: "💡 Tips",
  },
};
