export const COPY = {
  th: {
    navigation: "เมนูและการใช้งาน",
    groupMenu: "เปิดเมนูเลือกกลุ่ม",
    closeGroupMenu: "ปิดเมนู",
    hubLabel: "ศูนย์เรียนรู้",
    routeLabels: { catalog: "เลือกบทเรียน", preface: "ภาพรวมบทเรียน", contents: "สารบัญ", vocabulary: "คำศัพท์", home: "หน้าหลัก" },
    brand: "中文练习 (Zhōngwén Liànxí)",
    group: "กลุ่มที่ 3 (Group 03)",
    home: "หน้าหลัก",
    report: "รายงานปัญหา",
    source: "เอกสารอ้างอิง",
    central: "ศูนย์กลาง",
    switchLanguage: "เปลี่ยนภาษา",
    skip: "ข้ามไปยังเนื้อหา",
    light: "เปลี่ยนเป็นโหมดสว่าง",
    dark: "เปลี่ยนเป็นโหมดมืด",
    heroKicker: "INTERACTIVE CHINESE LEARNING · HSK 1–3",
    heroTitle: "เรียนภาษาจีนแบบจำลอง\nฟัง อ่าน แล้วเข้าใจทันที",
    heroBody: "ฝึกภาษาจีนในสถานการณ์จริง ฟังเสียงเจ้าของภาษาพร้อมคำแปล และเล่นเกมทบทวนคำศัพท์แบบง่ายๆ สนุกๆ",
    start: "📚 เลือกระดับบทเรียน",
    startLessonNow: "🚀 เริ่มเลย (HSK 1 บทที่ 1)",
    browse: "ดูบทเรียนทั้งหมด",
    noStorage: "✨ ใช้งานฟรี ไม่ต้องสมัคร",
    methodRead: "1. 🎧 ฟังและอ่าน",
    methodReadBody: "ฟังบทสนทนาแต่ละประโยคพร้อมตัวอักษรจีน พินอิน และคำแปลแบบชัดเจน",
    methodThink: "2. ⚡ ตรวจความเข้าใจ",
    methodThinkBody: "ตอบคำถามสั้นๆ หลังฟัง เพื่อเช็กว่าคุณเข้าใจเรื่องนี้มากแค่ไหน",
    methodBuild: "3. 🧩 เรียงประโยคและเล่นเกม",
    methodBuildBody: "เลือกคำศัพท์แล้วเรียงเป็นประโยคภาษาจีนให้ถูกต้อง พร้อมเกมทบทวนที่ทำให้จำง่ายขึ้น",
    shelfKicker: "ครอบคลุม HSK 1–3",
    shelfTitle: "เลือกระดับที่ต้องการเรียน",
    ready: "พร้อมเรียนแล้ว",
    awaiting: "กำลังเตรียมเนื้อหา",
    sourceOnly: "เนื้อหา คำศัพท์ และแบบฝึกหัดอ้างอิงจาก New HSK 1–3",
    frontMatterKicker: "ข้อมูลบทเรียน",
    prefaceTitle: "ภาพรวมและเป้าหมายบทเรียน",
    prefaceBody: "เรียนผ่านสถานการณ์จริง เช่น ซื้อของ สั่งอาหาร และเดินทาง เพื่อฝึกฟัง อ่าน และสนทนาแบบเป็นธรรมชาติ",
    objectiveTitle: "เป้าหมายการเรียนรู้",
    contentsTitle: "สารบัญบทเรียน",
    contentsBody: "เลือกหัวข้อที่ต้องการเรียน เช่น คำศัพท์ บทสนทนา และแบบฝึกหัดท้ายบท",
    vocabularyTitle: "คำศัพท์ใหม่ในบทนี้",
    vocabularyBody: "รวมคำศัพท์ที่สำคัญทั้งหมด คุณสามารถกดคำไหนก็ได้เพื่อฟังเสียงอ่านภาษาจีน",
    bookSourceNote: "อ้างอิงจาก New HSK (Text 1–3, New Words และ Objectives)",
    openPreface: "🎯 ดูเป้าหมายบทเรียน",
    openContents: "📑 ดูสารบัญ",
    openVocabulary: "🔤 ดูคำศัพท์",
    startReading: "📖 เริ่มบทที่ 1",
    previousPage: "ก่อนหน้า",
    nextPage: "ถัดไป",
    printedPage: "หน้าเรียน",
    catalogKicker: "บทเรียนทั้งหมด ({count} บท)",
    catalogTitle: "เลือกบทเรียนและสถานการณ์",
    catalogBody: "เรียนภาษาจีนผ่านสถานการณ์จำลองแบบง่ายๆ แต่ละบทมีเสียง ฟัง-ตอบ และเกมเรียงประโยค",
    enterScene: "📖 เข้าเรียนบทนี้",
    readLesson: "▶ เริ่มจากฉากที่ 1",
    back: "กลับ",
    roleMap: "ตัวละครในฉาก",
    beforeReading: "🎬 เรื่องราวก่อนเริ่ม",
    beforeReadingBody: "ดูว่าใครคุยกับใคร และเรื่องเกิดขึ้นที่ไหน ก่อนเริ่มบทสนทนา",
    sceneImage: "ภาพสถานการณ์",
    scenePicker: "เลือกฉาก",
    enlargeImage: "🔍 ดูภาพใหญ่",
    closeImage: "ปิดภาพ",
    role: "บทบาท",
    voiceCast: "เสียงพากย์",
    stage: "ฉาก",
    sourcePage: "หน้าหนังสือ",
    begin: "เริ่มบทสนทนา",
    previous: "ก่อนหน้า",
    next: "ถัดไป",
    finishScene: "จบฉาก",
    continueScene: "ไปฉากต่อไป",
    restart: "เริ่มใหม่",
    completed: "🎉 ทำได้ดีมาก! คุณจบฉากนี้แล้ว",
    completedBody: "คุณผ่านการเช็กความเข้าใจและเรียงประโยคภาษาจีนได้สำเร็จแล้ว",
    bonusGames: "🎮 เล่นเกมทบทวน",
    qte: "⚡ คำถามสั้น",
    seconds: "วินาที",
    pause: "หยุดชั่วคราว",
    resume: "เล่นต่อ",
    correct: "✅ ถูกต้อง!",
    wrong: "❌ ยังไม่ถูก ลองฟังอีกครั้ง",
    timeout: "⏰ หมดเวลา! ดูคำตอบด้านล่างแล้วลองใหม่ได้",
    evidence: "📖 ข้อความอ้างอิง:",
    retry: "ลองอีกครั้ง",
    continue: "เรียนต่อ",
    qteRestart: "เริ่มใหม่",
    builder: "🧩 เรียงประโยคภาษาจีน",
    builderHint: "แตะคำศัพท์ด้านล่างตามลำดับให้เป็นประโยคที่ถูกต้อง",
    check: "✅ ตรวจคำตอบ",
    undo: "↩️ ลบคำสุดท้าย",
    reset: "🔄 ล้างใหม่",
    builderCorrect: "🎉 ถูกต้อง! ประโยคนี้สมบูรณ์แล้ว",
    builderWrong: "⚠️ ลำดับยังไม่ถูก ลองสังเกตว่าใครทำอะไรที่ไหน แล้วเรียงใหม่อีกครั้ง",
    currentLine: "ประโยคปัจจุบัน",
    thaiMeaning: "คำแปลไทย",
    translationOn: "เปิดคำแปลไทย",
    translationOff: "ปิดคำแปลไทย",
    speak: "🔊 ฟังเสียงภาษาจีน",
    timerOn: "เปิดจับเวลา (15 วิ)",
    timerOff: "ไม่ใช้เวลา",
    exitReader: "กลับหน้าบทเรียน",
    buyer: "ลูกค้า / ผู้ซื้อ",
    educationalUnavailable: "ยังไม่มีคำแปลภาษาอังกฤษที่ตรวจสอบแล้ว",
    frontMatterNavigation: "เมนูบทเรียน",
    marketLabel: "สถานการณ์จำลอง",
    marketStartLine1: "เริ่ม",
    marketStartLine2: "บทเรียน",
    seller: "พนักงานขาย",
    visualMemory: "ภาพสถานการณ์",
    about: "เกี่ยวกับโปรเจกต์",
    aboutClose: "ปิด",
    objectivesLabel: "เป้าหมาย",
    languageFocusLabel: "ไวยากรณ์",
    contentsLabel: "สารบัญ",
    vocabularyLabel: "คำศัพท์",
    lessonLabel: "บทที่",
    sceneLabel: "ฉากที่",
    newWordsLabel: "คำศัพท์ใหม่",
    sceneCompleteLabel: "จบฉากที่",
    hskCourseLabel: "หลักสูตร New HSK",
    footerTitle: "中文练习 (Zhōngwén Liànxí) - เรียนภาษาจีนแบบโต้ตอบ",
    footerGroupInfo: "เรียนคำศัพท์และบทสนทนา HSK 1–3 ผ่านสถานการณ์จริง พร้อมเสียงเจ้าของภาษา เกมทบทวน และโหมดสวมบทบาท",
    footerCourse: "หลักสูตร New HSK ระดับ 1–3 · พัฒนาโดยกลุ่มที่ 3",
    footerMembersTitle: "ทีมพัฒนา (กลุ่มที่ 3)",
    footerMember1: "1. ศุภกร เปรมมะโน (โก้)",
    footerMember2: "2. พิสิษฐ์พงษ์ บุญเรือง (อาร์ม)",
    footerMember3: "3. เพชรระพีพัฒน์ นันตรัตน์ (เพชร)",
    autoplayBegin: "▶ เล่นอัตโนมัติ",
    manualBegin: "👆 อ่านเองทีละประโยค",
    autoplayHint: "ระบบจะเล่นเสียงและเลื่อนประโยคให้อัตโนมัติ",
    storyPlaybackControls: "ตัวควบคุมการเล่น",
    playbackPlaying: "กำลังเล่น...",
    playbackPaused: "หยุดแล้ว",
    playbackChallenge: "กรุณาตอบคำถามให้เสร็จก่อนเรียนต่อ",
    playbackSoundBlocked: "เบราว์เซอร์ปิดเสียงไว้ กดเพื่อเปิดเสียง",
    lineProgress: "ประโยคที่",
    sceneProgress: "ความคืบหน้า",
    nowSpeaking: "กำลังพูด",
    upNext: "ต่อไป",
    previousLine: "ก่อนหน้า",
    nextLine: "ถัดไป",
    pausePlayback: "หยุดเสียง",
    resumePlayback: "เล่นต่อ",
    replayLine: "ฟังซ้ำ",
    soundOn: "เปิดเสียง",
    soundOff: "ปิดเสียง",
    enableSound: "เปิดเสียง",
    playbackSpeed: "ความเร็วเสียง",
    showPlaybackDetails: "แสดงตัวควบคุม",
    hidePlaybackDetails: "ซ่อนตัวควบคุม",
    rolePickerTitle: "เลือกบทบาท",
    rolePickerBody: "เลือกตัวละครที่คุณอยากสวมบทบาท แล้วเริ่มบทสนทนาแบบ 3D",
    roleplayRole: "บทบาท",
    rolePickerNote: "เลือกบทบาทแล้วสลับ 3D/2D ได้ตลอด · กด Spacebar หรือ F เพื่อเล่น/หยุด",
    cancel: "ยกเลิก / กลับ",
    roleplayWait: "กดเล่นเพื่อเริ่มบทสนทนา",
    youLabel: "คุณ",
    roleplayView: "โหมดสวมบทบาท",
    dragToLook: "คลิกหรือเลื่อนเมาส์เพื่อหมุนมุมมอง 3D",
    modeLabel: "โหมดมุมมอง",
    mode3d: "มุมมอง 3D",
    mode2d: "มุมมอง 2D",
    exitRoleplay: "ออกจากโหมดสวมบทบาท",
    pressF: "กด F หรือ Space เพื่อเล่น/หยุด",
    guide: "วิธีใช้",
    howToPlay: "💡 วิธีเล่นและแนะนำการใช้งาน",
    gotIt: "เข้าใจแล้ว เริ่มเลย! 🚀",
    guideClose: "ปิด",
    dontShowAgain: "ไม่ต้องแสดงอีก",
    step: "ขั้นที่",
    tips: "💡 เคล็ดลับ",
  },
  zh: {
    navigation: "菜单和操作",
    groupMenu: "打开菜单",
    closeGroupMenu: "关闭菜单",
    hubLabel: "学习中心",
    routeLabels: { catalog: "选择课程", preface: "课程简介", contents: "目录", vocabulary: "生词", home: "首页" },
    brand: "中文练习 (Zhōngwén Liànxí)",
    group: "第 3 组",
    home: "首页",
    report: "问题反馈",
    source: "学习资料",
    central: "中心",
    switchLanguage: "切换语言",
    skip: "跳过到内容",
    light: "切换浅色模式",
    dark: "切换深色模式",
    heroKicker: "INTERACTIVE CHINESE LEARNING · HSK 1–3",
    heroTitle: "用真实情境学中文\n听、看、说，一次学会",
    heroBody: "通过真实场景练习中文，听母语发音，查看中文和释义，轻松完成学习与复习。",
    start: "📚 选择课程等级",
    startLessonNow: "🚀 立即开始（HSK 1 第 1 课）",
    browse: "查看全部课程",
    noStorage: "✨ 免费使用，不用登录",
    methodRead: "1. 🎧 听和读",
    methodReadBody: "逐句听对话，并同时看到中文、拼音和释义。",
    methodThink: "2. ⚡ 检查理解",
    methodThinkBody: "听完后快速回答问题，确认自己是否理解内容。",
    methodBuild: "3. 🧩 组句和游戏",
    methodBuildBody: "按顺序选择词语，组合成正确句子，并通过小游戏巩固记忆。",
    shelfKicker: "涵盖 HSK 1–3",
    shelfTitle: "选择想学的等级",
    ready: "可以开始学习",
    awaiting: "正在准备内容",
    sourceOnly: "内容、词汇和练习都参考 New HSK 1–3",
    frontMatterKicker: "课程信息",
    prefaceTitle: "课程简介和目标",
    prefaceBody: "通过真实场景学习，如买东西、点餐和旅行，练习听说和阅读。",
    objectiveTitle: "学习目标",
    contentsTitle: "课程目录",
    contentsBody: "选择你想学的内容，包括词汇、对话和练习题。",
    vocabularyTitle: "本课生词",
    vocabularyBody: "这里是本课重点词汇，点击任意词都可以听中文发音。",
    bookSourceNote: "参考教材 New HSK（Text 1–3, New Words 和 Objectives）",
    openPreface: "🎯 查看课程目标",
    openContents: "📑 查看目录",
    openVocabulary: "🔤 查看生词",
    startReading: "📖 从第 1 场景开始",
    previousPage: "上一页",
    nextPage: "下一页",
    printedPage: "教材页",
    catalogKicker: "全部课程（{count} 课）",
    catalogTitle: "选择课程和场景",
    catalogBody: "通过简洁的情境学习中文，每个场景都配有声音、理解题和组句练习。",
    enterScene: "📖 进入这个场景",
    readLesson: "▶ 从第 1 场景开始",
    back: "返回",
    roleMap: "场景角色",
    beforeReading: "🎬 开始前先看准备",
    beforeReadingBody: "先确认谁在说话、发生在什么地方，再开始对话。",
    sceneImage: "场景图",
    scenePicker: "选择场景",
    enlargeImage: "🔍 看大图",
    closeImage: "关闭",
    role: "角色",
    voiceCast: "声音",
    stage: "场景",
    sourcePage: "教材页码",
    begin: "开始对话",
    previous: "上一句",
    next: "下一句",
    finishScene: "完成场景",
    continueScene: "进入下一场",
    restart: "重来",
    completed: "🎉 很好！你完成这个场景了",
    completedBody: "你已经完成理解检查，并成功拼出中文句子。",
    bonusGames: "🎮 玩小游戏复习",
    qte: "⚡ 快速理解题",
    seconds: "秒",
    pause: "暂停",
    resume: "继续",
    correct: "✅ 正确！",
    wrong: "❌ 不对，再看看",
    timeout: "⏰ 时间到！看下面的提示后再试一次",
    evidence: "📖 参考句子：",
    retry: "再试一次",
    continue: "继续学习",
    qteRestart: "重新开始",
    builder: "🧩 组句练习",
    builderHint: "按顺序点击下方词语，拼成正确句子",
    check: "✅ 检查答案",
    undo: "↩️ 删掉上一个",
    reset: "🔄 重置",
    builderCorrect: "🎉 正确！这句很完整",
    builderWrong: "⚠️ 顺序还不对，再看看谁在做什么，再试一次",
    currentLine: "当前句子",
    thaiMeaning: "释义",
    translationOn: "开启释义",
    translationOff: "关闭释义",
    speak: "🔊 播放中文发音",
    timerOn: "打开计时（15 秒）",
    timerOff: "不计时",
    exitReader: "返回课程列表",
    buyer: "顾客",
    educationalUnavailable: "暂无更多参考释义",
    frontMatterNavigation: "课程导航",
    marketLabel: "情境模拟",
    marketStartLine1: "开始",
    marketStartLine2: "课程",
    seller: "售货员",
    visualMemory: "情境图",
    about: "关于项目",
    aboutClose: "关闭",
    objectivesLabel: "目标",
    languageFocusLabel: "语法",
    contentsLabel: "目录",
    vocabularyLabel: "生词",
    lessonLabel: "第",
    sceneLabel: "场景",
    newWordsLabel: "生词",
    sceneCompleteLabel: "已完成场景",
    hskCourseLabel: "新 HSK 课程",
    footerTitle: "中文练习 (Zhōngwén Liànxí) - 中文学习与角色扮演",
    footerGroupInfo: "用真实场景、语音和小游戏学习 HSK 1–3 词汇，轻松上手中文。",
    footerCourse: "新 HSK 1–3 课程 · 由第 3 组开发",
    footerMembersTitle: "开发团队（第 3 组）",
    footerMember1: "1. Supakorn Premmanon (Ko)",
    footerMember2: "2. Pitsitpong Boonrueang (Arm)",
    footerMember3: "3. Phetrapeepat Nantarat (Phet)",
    autoplayBegin: "▶ 自动播放",
    manualBegin: "👆 手动阅读",
    autoplayHint: "系统会自动播放声音并滚动到下一句",
    storyPlaybackControls: "播放控制",
    playbackPlaying: "正在播放...",
    playbackPaused: "已暂停",
    playbackChallenge: "请先完成题目，然后继续学习",
    playbackSoundBlocked: "浏览器拦截了音频，点这里打开",
    lineProgress: "当前句子",
    sceneProgress: "学习进度",
    nowSpeaking: "正在说话",
    upNext: "下一句",
    previousLine: "上一句",
    nextLine: "下一句",
    pausePlayback: "暂停播放",
    resumePlayback: "继续播放",
    replayLine: "重听",
    soundOn: "打开声音",
    soundOff: "关闭声音",
    enableSound: "打开声音",
    playbackSpeed: "播放速度",
    showPlaybackDetails: "显示控制",
    hidePlaybackDetails: "隐藏控制",
    rolePickerTitle: "选择角色",
    rolePickerBody: "选择你想扮演的角色，进入 3D 对话体验。",
    roleplayRole: "角色",
    rolePickerNote: "选择角色后可随时切换 3D/2D · 按空格或 F 播放/暂停",
    cancel: "取消 / 返回",
    roleplayWait: "点播放开始对话",
    youLabel: "你",
    roleplayView: "角色扮演视角",
    dragToLook: "拖动鼠标查看 3D 场景",
    modeLabel: "视角模式",
    mode3d: "3D 视角",
    mode2d: "2D 视角",
    exitRoleplay: "退出角色扮演",
    pressF: "按 F 或空格播放/暂停",
    guide: "使用说明",
    howToPlay: "💡 游戏和使用说明",
    gotIt: "知道了，开始吧！ 🚀",
    guideClose: "关闭",
    dontShowAgain: "不再显示",
    step: "第",
    tips: "💡 小提示",
  },
  en: {
    navigation: "Menu & controls",
    groupMenu: "Open group menu",
    closeGroupMenu: "Close menu",
    hubLabel: "Learning hub",
    routeLabels: { catalog: "Choose lesson", preface: "Lesson overview", contents: "Contents", vocabulary: "Vocabulary", home: "Home" },
    brand: "Zhōngwén Liànxí (中文练习)",
    group: "Group 3",
    home: "Home",
    report: "Report",
    source: "Study source",
    central: "Center",
    switchLanguage: "Switch language",
    skip: "Skip to content",
    light: "Switch to light mode",
    dark: "Switch to dark mode",
    heroKicker: "INTERACTIVE CHINESE LEARNING · HSK 1–3",
    heroTitle: "Learn Chinese in real situations\nListen, read, and understand faster",
    heroBody: "Practice everyday Chinese with native audio, clear translations, and short review games that are easy and fun.",
    start: "📚 Choose your level",
    startLessonNow: "🚀 Start now (HSK 1 Lesson 1)",
    browse: "Browse all lessons",
    noStorage: "✨ Free to use · No sign-up needed",
    methodRead: "1. 🎧 Listen and read",
    methodReadBody: "Follow each sentence with Chinese text, pinyin, and clear translations.",
    methodThink: "2. ⚡ Check your understanding",
    methodThinkBody: "Answer a few quick questions after each section to see how much you understand.",
    methodBuild: "3. 🧩 Build sentences and play",
    methodBuildBody: "Put the words in the right order and review with short mini-games.",
    shelfKicker: "Covers HSK 1–3",
    shelfTitle: "Choose a learning level",
    ready: "Ready to learn",
    awaiting: "Preparing content",
    sourceOnly: "Lessons and vocabulary are based on New HSK 1–3",
    frontMatterKicker: "Lesson info",
    prefaceTitle: "Lesson overview and goals",
    prefaceBody: "Learn through real-life scenes like shopping, ordering food, and travel to practice natural conversation.",
    objectiveTitle: "Learning goals",
    contentsTitle: "Lesson contents",
    contentsBody: "Pick what you want to study, including vocabulary, dialogue, and practice tasks.",
    vocabularyTitle: "New words in this lesson",
    vocabularyBody: "A list of key words. Tap any word to hear native Chinese pronunciation.",
    bookSourceNote: "Based on New HSK (Text 1–3, New Words, and Objectives)",
    openPreface: "🎯 View lesson goals",
    openContents: "📑 View contents",
    openVocabulary: "🔤 View vocabulary",
    startReading: "📖 Start lesson 1",
    previousPage: "Previous",
    nextPage: "Next",
    printedPage: "Textbook page",
    catalogKicker: "All lessons ({count})",
    catalogTitle: "Choose a lesson and scene",
    catalogBody: "Learn through simple simulated situations. Each scene includes audio, quick checks, and sentence practice.",
    enterScene: "📖 Enter this scene",
    readLesson: "▶ Start from scene 1",
    back: "Back",
    roleMap: "Characters in scene",
    beforeReading: "🎬 Scene preview",
    beforeReadingBody: "Check who is speaking and where the scene is happening before you start.",
    sceneImage: "Scene image",
    scenePicker: "Choose a scene",
    enlargeImage: "🔍 View larger",
    closeImage: "Close",
    role: "Role",
    voiceCast: "Voice cast",
    stage: "Scene",
    sourcePage: "Book page",
    begin: "Start dialogue",
    previous: "Previous",
    next: "Next",
    finishScene: "Finish scene",
    continueScene: "Go to next scene",
    restart: "Restart",
    completed: "🎉 Nice job! You completed this scene",
    completedBody: "You finished the check and built the sentence correctly.",
    bonusGames: "🎮 Play review games",
    qte: "⚡ Quick quiz",
    seconds: "seconds",
    pause: "Pause",
    resume: "Resume",
    correct: "✅ Correct!",
    wrong: "❌ Not quite. Try again.",
    timeout: "⏰ Time's up! Review the example and try again.",
    evidence: "📖 Reference sentence:",
    retry: "Try again",
    continue: "Continue",
    qteRestart: "Restart",
    builder: "🧩 Sentence builder",
    builderHint: "Tap the words in order to make the correct sentence",
    check: "✅ Check answer",
    undo: "↩️ Undo",
    reset: "🔄 Reset",
    builderCorrect: "🎉 Correct! The sentence is complete.",
    builderWrong: "⚠️ Not quite. Look at who does what and try again.",
    currentLine: "Current line",
    thaiMeaning: "Translation",
    translationOn: "Show translation",
    translationOff: "Hide translation",
    speak: "🔊 Play Chinese audio",
    timerOn: "Use timer (15s)",
    timerOff: "No timer",
    exitReader: "Back to lessons",
    buyer: "Customer",
    educationalUnavailable: "No verified translation is available yet.",
    frontMatterNavigation: "Lesson nav",
    marketLabel: "Scenario",
    marketStartLine1: "Start",
    marketStartLine2: "lesson",
    seller: "Seller",
    visualMemory: "Scene image",
    about: "About project",
    aboutClose: "Close",
    objectivesLabel: "Goals",
    languageFocusLabel: "Grammar",
    contentsLabel: "Contents",
    vocabularyLabel: "Vocabulary",
    lessonLabel: "Lesson",
    sceneLabel: "Scene",
    newWordsLabel: "New words",
    sceneCompleteLabel: "Scene complete",
    hskCourseLabel: "New HSK course",
    footerTitle: "Zhōngwén Liànxí (中文练习) - Interactive Chinese learning",
    footerGroupInfo: "Learn HSK vocabulary through real-life scenes, clear audio, and short review games.",
    footerCourse: "New HSK Levels 1–3 · Built by Group 3",
    footerMembersTitle: "Development team (Group 3)",
    footerMember1: "1. Supakorn Premmanon (Ko)",
    footerMember2: "2. Pitsitpong Boonrueang (Arm)",
    footerMember3: "3. Phetrapeepat Nantarat (Phet)",
    autoplayBegin: "▶ Autoplay",
    manualBegin: "👆 Read by yourself",
    autoplayHint: "Audio plays automatically and the app moves to the next line.",
    storyPlaybackControls: "Playback controls",
    playbackPlaying: "Playing...",
    playbackPaused: "Paused",
    playbackChallenge: "Please finish the challenge before continuing.",
    playbackSoundBlocked: "Audio is blocked by the browser. Click to enable it.",
    lineProgress: "Line",
    sceneProgress: "Progress",
    nowSpeaking: "Speaking now",
    upNext: "Next",
    previousLine: "Previous",
    nextLine: "Next",
    pausePlayback: "Pause audio",
    resumePlayback: "Resume audio",
    replayLine: "Replay",
    soundOn: "Sound on",
    soundOff: "Sound off",
    enableSound: "Enable sound",
    playbackSpeed: "Playback speed",
    showPlaybackDetails: "Show controls",
    hidePlaybackDetails: "Hide controls",
    rolePickerTitle: "Choose a role",
    rolePickerBody: "Pick a character to roleplay and enter a 3D dialogue scene.",
    roleplayRole: "Role",
    rolePickerNote: "Choose a role and switch between 3D/2D anytime · Press Space or F to play or pause",
    cancel: "Cancel / back",
    roleplayWait: "Press play to start",
    youLabel: "You",
    roleplayView: "Roleplay view",
    dragToLook: "Click or drag to look around in 3D",
    modeLabel: "View mode",
    mode3d: "3D view",
    mode2d: "2D view",
    exitRoleplay: "Exit roleplay",
    pressF: "Press F or Space to play/pause",
    guide: "Guide",
    howToPlay: "💡 How to play and use it",
    gotIt: "Got it, let's start! 🚀",
    guideClose: "Close",
    dontShowAgain: "Do not show again",
    step: "Step",
    tips: "💡 Tips",
  },
};

