import { group3AssetPath } from "../../../../config.js";

const SOURCE_FILE = "docs/references/hsk/sources/hsk1-2.pdf";

export function lessonHsk1L3SourceRef(printedPages, pdfPages) {
  return `${SOURCE_FILE}#printed-pages=${printedPages}&pdf-pages=${pdfPages}`;
}

const sourceRef = lessonHsk1L3SourceRef("10-14", "26-30");

const characters = {
  liWen: {
    hanzi: "李文",
    pinyin: "Lǐ Wén",
    nameTh: "หลี่เหวิน",
    nameEn: "Li Wen",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp")} 1400w`,
    imageFocus: "26% center",
  },
  bai: {
    hanzi: "白家月",
    pinyin: "Bái Jiāyuè",
    nameTh: "ไป๋เจียเยว่",
    nameEn: "Bai Jiayue",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp")} 1400w`,
    imageFocus: "74% center",
  },
  annie: {
    hanzi: "安妮",
    pinyin: "Ānnī",
    nameTh: "อันนี่",
    nameEn: "Annie",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp")} 1400w`,
    imageFocus: "26% center",
  },
  chen: {
    hanzi: "陈天中",
    pinyin: "Chén Tiānzhōng",
    nameTh: "เฉินเทียนจง",
    nameEn: "Chen Tianzhong",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp")} 1400w`,
    imageFocus: "74% center",
  },
  wang: {
    hanzi: "王一雪",
    pinyin: "Wáng Yīxuě",
    nameTh: "หวังอี้เสวี่ย",
    nameEn: "Wang Yixue",
    image: group3AssetPath("/assets/group3/shared/characters/character-wang-yixue.webp"),
    imageFocus: "50% center",
  },
  teacherWang: {
    hanzi: "王一飞",
    pinyin: "Wáng Yīfēi",
    nameTh: "อาจารย์หวังอี้เฟย",
    nameEn: "Ms. Wang",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-v1.webp")} 1400w`,
    imageFocus: "74% center",
  },
};

const vocabularyPages = [
  [1, "人", "rén", "n.", "human; person", "คน", 11, 27],
  [2, "的", "de", "part.", "used after an attributive", "ของ / คำแสดงความเป็นเจ้าของ", 11, 27],
  [3, "中国", "Zhōngguó", "n.", "China", "ประเทศจีน", 11, 27],
  [4, "法国", "Fàguó", "n.", "France", "ประเทศฝรั่งเศส", 11, 27],
  [5, "中文", "Zhōngwén", "n.", "Chinese language", "ภาษาจีน", 11, 27],
  [6, "这", "zhè", "pron.", "this", "นี่", 13, 29],
  [7, "谁", "shéi / shuí", "pron.", "who", "ใคร", 13, 29],
  [8, "女朋友", "nǚpéngyou", "n.", "girlfriend", "แฟนสาว", 13, 29],
  [9, "哪", "nǎ", "pron.", "which", "ไหน", 13, 29],
  [10, "国", "guó", "n.", "country", "ประเทศ", 13, 29],
  [11, "她", "tā", "pron.", "she; her", "เธอ", 13, 29],
  [12, "泰国", "Tàiguó", "n.", "Thailand", "ประเทศไทย", 13, 29],
  [13, "喂", "wèi", "int.", "hello; hey (on the phone)", "ฮัลโหล / เอ่อ", 14, 30],
  [14, "姐姐", "jiějie", "n.", "elder sister", "พี่สาว", 14, 30],
  [15, "工作", "gōngzuò", "n.", "job; work", "งาน", 14, 30],
  [16, "还", "hái", "adv.", "still", "ยัง", 14, 30],
  [17, "忙", "máng", "adj.", "busy", "ยุ่ง", 14, 30],
  [18, "吗", "ma", "part.", "question particle (yes-no)", "ไหม (คำถามใช่-ไม่ใช่)", 14, 30],
  [19, "对", "duì", "adj.", "right; correct", "ใช่ / ถูกต้อง", 14, 30],
  [20, "太", "tài", "adv.", "too; excessively", "เกินไป / มากเกินไป", 14, 30],
  [21, "我们", "wǒmen", "pron.", "we; us", "พวกเรา", 14, 30],
  [22, "想", "xiǎng", "v.", "miss; think of", "คิดถึง", 14, 30],
];

const vocabulary = vocabularyPages.map(([index, hanzi, pinyin, type, en, thAid, page, pdfPage]) => ({
  index,
  hanzi,
  pinyin,
  type,
  en,
  th: thAid,
  thAid,
  page,
  translationKind: "editorial-aid",
  sourceRef: lessonHsk1L3SourceRef(String(page), String(pdfPage)),
}));

function line(source, value) {
  return { ...value, sourceRef: source };
}

const campusRef = lessonHsk1L3SourceRef("10", "26");
const photosRef = lessonHsk1L3SourceRef("12", "28");
const videocallRef = lessonHsk1L3SourceRef("13-14", "29-30");

const scenes = [
  {
    id: "h1l3-campus",
    number: "01",
    glyph: "是",
    title: "在校园里聊国籍",
    titleTh: "คุยเรื่องสัญชาติบนมหาวิทยาลัย",
    titleEn: "Talking about nationalities on campus",
    place: "校园",
    placePy: "xiàoyuán",
    placeTh: "มหาวิทยาลัย",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-campus-v1.webp")} 1400w`,
    imageAlt: {
      th: "หลี่เหวินและไป๋เจียเยว่คุยเรื่องสัญชาติระหว่างเดินในมหาวิทยาลัย",
      zh: "李文和白家月在校园里谈论国籍",
      en: "Li Wen and Bai Jiayue talk about nationalities on campus",
    },
    source: "Text 1 · หน้าเล่ม 10 · PDF หน้า 26",
    sourcePage: "10",
    sourceRef: campusRef,
    context: "在校园里，李文和白家月继续聊天儿，聊到国籍。",
    contextTh: "บนมหาวิทยาลัย หลี่เหวินและไป๋เจียเยว่คุยกันต่อ เรื่องสัญชาติ",
    contextEn: "On campus, Li Wen and Bai Jiayue continued chatting, and the topic turned to nationalities.",
    characters: [
      { role: "A", profile: "liWen", noteTh: "นักศึกษาจีนที่แนะนำสัญชาติตัวเอง", noteZh: "介绍自己国籍的学生", noteEn: "The student introducing his nationality" },
      { role: "B", profile: "bai", noteTh: "นักศึกษาฝรั่งเศสที่เล่าถึงครูสอนภาษาจีน", noteZh: "介绍国籍和中文老师的学生", noteEn: "The student introducing her nationality and Chinese teacher" },
    ],
    lines: [
      line(campusRef, { role: "A", speaker: "李文", pinyin: "wǒ shì zhōngguó rén", hanzi: "我是中国人。", reading: "Wǒ shì Zhōngguó rén.", en: "I'm Chinese.", th: "ฉันเป็นคนจีน", visual: { zh: "中国人", th: "คนจีน", focus: "26% center" } }),
      line(campusRef, { role: "B", speaker: "白家月", pinyin: "wǒ shì fàguó rén, wǒ de zhōngwén lǎoshī yě shì zhōngguó rén", hanzi: "我是法国人。我的中文老师也是中国人。", reading: "Wǒ shì Fàguó rén. Wǒ de Zhōngwén lǎoshī yě shì Zhōngguó rén.", en: "I'm French. My Chinese teacher is also Chinese.", th: "ฉันเป็นคนฝรั่งเศส ครูสอนภาษาจีนของฉันก็เป็นคนจีนด้วย", visual: { zh: "也", th: "ก็...ด้วย", focus: "74% center" } }),
    ],
    qte: {
      after: 1,
      prompt: { th: "李文是哪国人?", zh: "李文是哪国人？", en: "What nationality is Li Wen?" },
      options: [
        { value: "中国人", zh: "中国人", pinyin: "Zhōngguó rén", th: "คนจีน" },
        { value: "法国人", zh: "法国人", pinyin: "Fàguó rén", th: "คนฝรั่งเศส" },
        { value: "泰国人", zh: "泰国人", pinyin: "Tàiguó rén", th: "คนไทย" },
      ],
      correct: "中国人",
      evidence: "李文：我是中国人。",
      evidenceTh: "หลี่เหวิน: ฉันเป็นคนจีน",
      sourceRef: campusRef,
    },
    builder: {
      prompt: { th: "เรียงประโยค “ฉันเป็นคนจีน”", zh: "重组“我是中国人”", en: "Rebuild “I'm Chinese”" },
      answer: ["我", "是", "中国", "人"],
      tiles: ["中国", "是", "人", "我"],
      gloss: { 我: "ฉัน", 是: "เป็น", 中国: "จีน", 人: "คน" },
      translationTh: "ฉันเป็นคนจีน",
      translationEn: "I'm Chinese.",
      evidence: "Text 1 · หน้าเล่ม 10",
      sourceRef: campusRef,
    },
  },
  {
    id: "h1l3-photos",
    number: "02",
    glyph: "问",
    title: "在教室里看照片",
    titleTh: "ดูรูปภาพในห้องเรียน",
    titleEn: "Looking at photos in the classroom",
    place: "教室",
    placePy: "jiàoshì",
    placeTh: "ห้องเรียน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-photos-v1.webp")} 1400w`,
    imageAlt: {
      th: "เฉินเทียนจงให้อันนี่ดูรูปแฟนสาวในโทรศัพท์หลังเลิกเรียน",
      zh: "陈天中下课后给安妮看手机里的女朋友照片",
      en: "Chen Tianzhong shows Annie a photo of his girlfriend after class",
    },
    source: "Text 2 · หน้าเล่ม 12 · PDF หน้า 28",
    sourcePage: "12",
    sourceRef: photosRef,
    context: "在教室里，下课后，安妮在看陈天中手机里的照片。",
    contextTh: "ในห้องเรียน หลังเลิกเรียน อันนี่ดูรูปในโทรศัพท์ของเฉินเทียนจง",
    contextEn: "After class in the classroom, Annie was looking at the photos on Chen Tianzhong's phone.",
    characters: [
      { role: "A", profile: "annie", noteTh: "นักเรียนที่ถามว่าภาพนี้คือใคร", noteZh: "询问照片中是谁的学生", noteEn: "The student asking who is in the photo" },
      { role: "B", profile: "chen", noteTh: "นักเรียนที่แนะนำแฟนสาวของตน", noteZh: "介绍女朋友的学生", noteEn: "The student introducing his girlfriend" },
    ],
    lines: [
      line(photosRef, { role: "A", speaker: "安妮", pinyin: "zhè shì shéi", hanzi: "这是谁？", reading: "Zhè shì shéi?", en: "Who is this?", th: "นี่คือใคร?", visual: { zh: "这是谁", th: "นี่คือใคร", focus: "26% center" } }),
      line(photosRef, { role: "B", speaker: "陈天中", pinyin: "zhè shì wǒ nǚpéngyou", hanzi: "这是我女朋友。", reading: "Zhè shì wǒ nǚpéngyou.", en: "This is my girlfriend.", th: "นี่คือแฟนสาวของผม", visual: { zh: "女朋友", th: "แฟนสาว", focus: "74% center" } }),
      line(photosRef, { role: "A", speaker: "安妮", pinyin: "nǐ nǚpéngyou shì nǎ guó rén", hanzi: "你女朋友是哪国人？", reading: "Nǐ nǚpéngyou shì nǎ guó rén?", en: "What nationality is your girlfriend?", th: "แฟนสาวคุณเป็นคนชาติไหน?", visual: { zh: "哪国人", th: "คนชาติไหน", focus: "26% center" } }),
      line(photosRef, { role: "B", speaker: "陈天中", pinyin: "tā yě shì tàiguó rén", hanzi: "她也是泰国人。", reading: "Tā yě shì Tàiguó rén.", en: "She's also Thai.", th: "เธอก็เป็นคนไทยเหมือนกัน", visual: { zh: "也是", th: "ก็เป็น...เหมือนกัน", focus: "74% center" } }),
    ],
    qte: {
      after: 2,
      prompt: { th: "照片里的人是谁?", zh: "照片里的人是谁？", en: "Who is the person in the photo?" },
      options: [
        { value: "陈天中的女朋友", zh: "陈天中的女朋友", pinyin: "Chén Tiānzhōng de nǚpéngyou", th: "แฟนสาวของเฉินเทียนจง" },
        { value: "安妮", zh: "安妮", pinyin: "Ānnī", th: "อันนี่" },
        { value: "白家月", zh: "白家月", pinyin: "Bái Jiāyuè", th: "ไป๋เจียเยว่" },
      ],
      correct: "陈天中的女朋友",
      evidence: "陈天中：这是我女朋友。",
      evidenceTh: "เฉินเทียนจง: นี่คือแฟนสาวของผม",
      sourceRef: photosRef,
    },
    builder: {
      prompt: { th: "เรียงคำถาม “แฟนสาวคุณเป็นคนชาติไหน”", zh: "重组“你女朋友是哪国人”", en: "Rebuild “What nationality is your girlfriend”" },
      answer: ["你女朋友", "是", "哪国人？"],
      tiles: ["哪国人？", "是", "你女朋友"],
      gloss: { 你: "คุณ", 女朋友: "แฟนสาว", 是: "เป็น", 哪国人: "คนชาติไหน" },
      translationTh: "แฟนสาวคุณเป็นคนชาติไหน?",
      translationEn: "What nationality is your girlfriend?",
      evidence: "Text 2 · หน้าเล่ม 12",
      sourceRef: photosRef,
    },
  },
  {
    id: "h1l3-videocall",
    number: "03",
    glyph: "想",
    title: "在家里打视频电话",
    titleTh: "วิดีโอคอลหาใครที่บ้าน",
    titleEn: "A video call from home",
    place: "家里",
    placeTh: "ที่บ้าน",
    image: group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-v1.webp"),
    imageSrcSet: `${group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-720w-v1.webp")} 720w, ${group3AssetPath("/assets/group3/lesson-hsk1-l3-videocall-v1.webp")} 1400w`,
    imageAlt: {
      th: "อาจารย์หวังวิดีโอคอลคุยเรื่องงานและความคิดถึงกับพี่สาวที่บ้าน",
      zh: "王老师在家与姐姐视频通话，聊工作和思念",
      en: "Teacher Wang video-calls her sister at home to talk about work and family",
    },
    source: "Text 3 · หน้าเล่ม 13–14 · PDF หน้า 29–30",
    sourcePage: "13–14",
    sourceRef: videocallRef,
    context: "在家里，王一雪给王一飞打视频电话。",
    contextTh: "ที่บ้าน หวังอี้เสวี่ยวิดีโอคอลหาหวังอี้เฟย",
    contextEn: "At home, Wang Yixue made a video call to Wang Yifei.",
    characters: [
      { role: "A", profile: "wang", noteTh: "พี่สาวที่โทรถามความเป็นอยู่ของน้อง", noteZh: "打电话问候弟弟的姐姐", noteEn: "The elder sister calling to check on her brother" },
      { role: "B", profile: "teacherWang", noteTh: "อาจารย์ที่ตอบคำถามเรื่องงาน", noteZh: "回答工作情况的弟弟", noteEn: "The brother answering about his work" },
    ],
    lines: [
      line(videocallRef, { role: "A", speaker: "王一雪", pinyin: "wèi, yīfēi", hanzi: "喂，一飞！", reading: "Wèi, Yīfēi!", en: "Hi, Yifei!", th: "ฮัลโหล อี้เฟย!", visual: { zh: "喂", th: "ฮัลโหล", focus: "26% center" } }),
      line(videocallRef, { role: "B", speaker: "王一飞", pinyin: "jiějie", hanzi: "姐姐！", reading: "Jiějie!", en: "Sister!", th: "พี่สาว!", visual: { zh: "姐姐", th: "พี่สาว", focus: "74% center" } }),
      line(videocallRef, { role: "A", speaker: "王一雪", pinyin: "nǐ gōngzuò hái máng ma", hanzi: "你工作还忙吗？", reading: "Nǐ gōngzuò hái máng ma?", en: "Are you still busy with work?", th: "งานของคุณยังยุ่งอยู่ไหม?", visual: { zh: "还…吗", th: "ยัง...ไหม", focus: "26% center" } }),
      line(videocallRef, { role: "B", speaker: "王一飞", pinyin: "duì, hái hěn máng, nǐ yě hěn máng ma", hanzi: "对，还很忙。你也很忙吗？", reading: "Duì, hái hěn máng. Nǐ yě hěn máng ma?", en: "Yes, I'm still very busy. Are you busy too?", th: "ใช่ ยังยุ่งมากอยู่ แล้วคุณก็ยุ่งเหมือนกันไหม?", visual: { zh: "也…吗", th: "ก็...ไหม", focus: "74% center" } }),
      line(videocallRef, { role: "A", speaker: "王一雪", pinyin: "wǒ bú tài máng, wǒmen hěn xiǎng nǐ", hanzi: "我不太忙。我们很想你。", reading: "Wǒ bú tài máng. Wǒmen hěn xiǎng nǐ.", en: "I'm not too busy. We miss you a lot.", th: "ฉันไม่ค่อยยุ่งเท่าไร พวกเราคิดถึงคุณมาก", visual: { zh: "想", th: "คิดถึง", focus: "26% center" } }),
      line(videocallRef, { role: "B", speaker: "王一飞", pinyin: "wǒ yě xiǎng nǐmen", hanzi: "我也想你们。", reading: "Wǒ yě xiǎng nǐmen.", en: "I miss you all too.", th: "ผมก็คิดถึงพวกคุณเหมือนกัน", visual: { zh: "也", th: "ก็...เหมือนกัน", focus: "74% center" } }),
    ],
    qte: {
      after: 3,
      prompt: { th: "王一飞现在工作忙吗?", zh: "王一飞现在工作忙吗？", en: "Is Wang Yifei busy with work now?" },
      options: [
        { value: "对，还很忙。", zh: "对，还很忙。", pinyin: "Duì, hái hěn máng.", th: "ใช่ ยังยุ่งมากอยู่" },
        { value: "不太忙。", zh: "不太忙。", pinyin: "Bú tài máng.", th: "ไม่ค่อยยุ่ง" },
        { value: "不，不忙。", zh: "不，不忙。", pinyin: "Bù, bù máng.", th: "ไม่ ไม่อยุ่ง" },
      ],
      correct: "对，还很忙。",
      evidence: "王一飞：对，还很忙。",
      evidenceTh: "หวังอี้เฟย: ใช่ ยังยุ่งมากอยู่",
      sourceRef: videocallRef,
    },
    builder: {
      prompt: { th: "เรียงคำพูดคิดถึงของหวังอี้เสวี่ย", zh: "重组王一雪的思念", en: "Rebuild Wang Yixue's words of missing" },
      answer: ["我们", "很", "想", "你。"],
      tiles: ["很", "你。", "我们", "想"],
      gloss: { 我们: "พวกเรา", 很: "มาก", 想: "คิดถึง", 你: "คุณ" },
      translationTh: "พวกเราคิดถึงคุณมาก",
      translationEn: "We miss you a lot.",
      evidence: "Text 3 · หน้าเล่ม 14",
      sourceRef: videocallRef,
    },
  },
];

export const LESSON_HSK1_L3 = {
  id: "hsk1-l3",
  slug: "lesson-3",
  level: "hsk1",
  number: 3,
  featured: false,
  source: {
    title: "新HSK教程 1 · New HSK Course 1",
    lesson: "Lesson 3 · 我是中国人",
    printedPages: "10–14",
    pdfPages: "26–30",
    file: "hsk1-2.pdf",
    sourceRef,
  },
  sourceRef,
  title: {
    zh: "我是中国人",
    pinyin: "Wǒ shì Zhōngguó rén",
    en: "I'm Chinese",
    thAid: "ฉันเป็นคนจีน",
  },
  summary: {
    zh: "从校园聊到家里，学会用“是”字句介绍国籍和身份，用“吗”提问。",
    en: "From campus chat to a family video call, learn to use 是 sentences to state nationalities and identities, and to ask yes-no questions with 吗.",
    thAid: "จากมหาวิทยาลัยถึงวิดีโอคอลที่บ้าน ฝึกใช้ประโยค 是 แนะนำสัญชาติและตัวตน และตั้งคำถามด้วย 吗",
  },
  translationPolicy: { kind: "editorial-aid", labelTh: "คำแปลไทยเพื่อช่วยเรียน เรียบเรียงจากต้นฉบับ" },
  objectives: [
    { zh: "能听懂并使用“是”字句表达等同或类属。", en: "Be able to understand and use 是 sentences to express equivalence or categorization.", thAid: "เข้าใจและใช้ประโยค 是 เพื่อบอกความเท่ากันหรือประเภท", sourceRef: lessonHsk1L3SourceRef("10", "26") },
    { zh: "掌握结构助词“的”的用法。", en: "Master the use of the structural particle 的.", thAid: "เข้าใจการใช้คำช่วย 的 (แสดงความเป็นเจ้าของ)", sourceRef: lessonHsk1L3SourceRef("10", "26") },
    { zh: "掌握用“吗”的是非问句的用法。", en: "Master the use of the yes-no question with 吗.", thAid: "เข้าใจการใช้คำถามใช่-ไม่ใช่ด้วย 吗", sourceRef: lessonHsk1L3SourceRef("10", "26") },
  ],
  contents: [
    { number: "00", title: "目标与热身", titleTh: "เป้าหมายและการเตรียมบท", detail: "Objectives · Warm-Up", pages: "10", route: "/home/hsk1/lesson-3/preface/", sourceRef: lessonHsk1L3SourceRef("10", "26") },
    { number: "01", title: "在校园里聊国籍", titleTh: "คุยเรื่องสัญชาติบนมหาวิทยาลัย", detail: "Text 1 · New Words 1–5", pages: "10", scene: 1, sourceRef: lessonHsk1L3SourceRef("10", "26") },
    { number: "02", title: "在教室里看照片", titleTh: "ดูรูปภาพในห้องเรียน", detail: "Text 2 · New Words 6–12", pages: "12", scene: 2, sourceRef: lessonHsk1L3SourceRef("12", "28") },
    { number: "03", title: "在家里打视频电话", titleTh: "วิดีโอคอลหาใครที่บ้าน", detail: "Text 3 · New Words 13–22", pages: "13–14", scene: 3, sourceRef: lessonHsk1L3SourceRef("13-14", "29-30") },
    { number: "04", title: "综合练习与活动", titleTh: "แบบฝึกรวมและกิจกรรม", detail: "Xiaoyu's Classroom · Exercises (source trail)", pages: "14", sourceRef: lessonHsk1L3SourceRef("14", "30") },
  ],
  vocabulary,
  grammarFocus: [
    { title: "“是”字句", titleEn: "The 是 Sentence", explanationZh: "“是”字句用来表达等同或类属，基本结构：A是B。例如：我是中国人。", explanationEn: "The 是 sentence expresses equivalence or categorization: A is B. For example: 我是中国人。", thAid: "ประโยค 是 ใช้บอกว่า A คือ B เช่น 我是中国人 (ฉันเป็นคนจีน)", examples: ["我是中国人。", "这是我的老师。", "她也是泰国人。"], sourceRef: lessonHsk1L3SourceRef("10", "26") },
    { title: "结构助词“的”", titleEn: "The Structural Particle 的", explanationZh: "“的”放在定语和中心语之间，表示所属关系。例如：我的中文老师。", explanationEn: "的 sits between an attributive and the noun it modifies, expressing possession or modification. For example: 我的中文老师。", thAid: "的 วางระหว่างคำขยายและคำหลัก แสดงความเป็นเจ้าของ เช่น 我的中文老师 (ครูสอนภาษาจีนของฉัน)", examples: ["我的中文老师", "王老师的学生", "陈天中的女朋友"], sourceRef: lessonHsk1L3SourceRef("10-11", "26-27") },
    { title: "用“吗”的是非问句", titleEn: "Yes-No Questions with 吗", explanationZh: "“吗”是语气助词，放在句末构成是非问句。例如：你工作还忙吗？", explanationEn: "The modal particle 吗 is placed at the end of a sentence to form a yes-no question. For example: 你工作还忙吗？", thAid: "吗 เป็นคำช่วยท้ายประโยคทำเป็นคำถามใช่-ไม่ใช่ เช่น 你工作还忙吗 (งานของคุณยังยุ่งอยู่ไหม)", examples: ["你工作还忙吗？", "你也很忙吗？", "这是谁？"], sourceRef: lessonHsk1L3SourceRef("14", "30") },
  ],
  characters,
  scenes,
};
